### ISSUE TITLE
Publish dir cannot be inside monorepo

### ISSUE THREAD

**Issue by gopeter** [netlify/netlify-plugin-nextjs#103]
**Describe the bug**
I have set the publish dir to `frontend/.next.js`, but once the Next build has finished, the plugin claims that it can't find a `static` folder inside `.next`.

I also set the right `target` and building locally works too (where I get a `static` folder). 

Are monorepos are supported by this plugin?

**Comment by erezrokah** [comment]
Hi @gopeter we might need more information to resolve this issue, but have you tried setting the [base directory](https://docs.netlify.com/configure-builds/get-started/#definitions) to `frontend`?

That tells Netlify to change into that directory before building and should help the plugin find the relevant files.

If that doesn't work can you share a bit more information of the structure of your repo (possibly in a public repository)?
Specifically:
1. Where is the Next.js site `package.json` is located?
2. What is your build command?
3. What is the content of `netlify.toml` if you have one?

**Comment by gopeter** [comment]
Dear @erezrokah, 

thanks for the quick response! I've just made a custom build command (`"build": "cd frontend && yarn build && mv .next ../.next"`) which worked well, but the base directory should do the trick too.

Thanks!
