### ISSUE TITLE
[Bug]: Headers from next.config.js are not being used at all

### ISSUE THREAD

**Issue by sarneeh** [netlify/netlify-plugin-nextjs#1063]
### Summary

The [v4](https://github.com/netlify/netlify-plugin-nextjs/blob/main/docs/release-notes/v4.md) release notes announce `Full support for Next.js rewrites, redirects and headers.` but I can't make the headers work on Netlify deployment.

It does work on `next dev` and `next build && next start`, but it does not work after deploying it on Netlify.

### Steps to reproduce

1. Add `headers` function to `next.config.js`
2. Deploy the app on Netlify
3. The custom headers are not there

### Plugin version

4.0.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```js
    ...
    headers: () => ([
        {
            source: "/fonts/(.*).otf",
            headers: [
                {
                    key: "Cache-Control",
                    value: "public, max-age: 31536000, immutable",
                },
            ],
        },
    ]),
    ...
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by matiasfacio** [comment]
same here

**Comment by ascorbic** [comment]
Hi @sarneeh,
Sorry you're having trouble. I should update the docs to be clearer, but headers only work for Next.js page, not for static files. For static files you need to use Netlify `_headers` files. Apologies for the confusion

**Comment by matiasfacio** [comment]
Hi @ascorbic!

I tried to add headers using next.config.js for a dynamic next.js project, but it didn't work, it does locally, but not when deployed. The only way for me at the moment to make it work is by adding the headers on the netlify.toml file.  Is this the correct way or am I missing something? Thank you!

**Comment by ascorbic** [comment]
@matiasfacio Can you share the files listed in the issue template, plus your `.next/routes-manifest.json` and `.next/prerender-manifest.json`? Check they don't contain anything sensitive.

**Comment by sarneeh** [comment]
@ascorbic Thank you for the clarification! No need to apologize - this is open source, I just went to the source and figured it out it doesn't work the way I think it does 😄  Although I'll leave you folks the docs update as I'm not so experienced with the Netlify platform so I think you'll describe it a lot better 😄

**Comment by ascorbic** [comment]
Fixed in https://github.com/netlify/netlify-plugin-nextjs/pull/1358
