### ISSUE TITLE
[Bug]: Revalidate doesn't work as expected.

### ISSUE THREAD

**Issue by katyperrycbt** [netlify/netlify-plugin-nextjs#1085]
### Summary

I tested this plugin again in the latest version for NextJS, very excited to hear that the plugin has full ISR support. However, I found it not working, no matter how many times F5, clear cache from the browser, change device, purge cache from Cloudflare, tried a lot on Cloudflare but it doesn't bring any change because I thought it caused I found out the caching was sloppy, but I tried again with the release on Vercel, also with the domain through Cloudflare, it worked properly.

I test concurrently at my localhost build and deploy to Vercel. Both change as I want after 60s of 'revalidate', but not on Netlify.

The summary is as follows: with the same setup.
- Localhost: yarn build, then yarn start => revalidate works properly, the pages witness the change.
- Vercel: similarly, pages see changes after I make changes to them.
- Netlify: same setting, but pages stay the same even though I change their data.

### Steps to reproduce

1. On a dynamic page under "pages/", add the following, the URL and response props vary according to your database and structure

Example: under pages/blogs/[slug].js

`export async function getStaticProps({ params }) {
    try {
        const blog = await getBlog(params.slug);
        if (!blog || blog.error) {
            return {
                notFound: true,
                revalidate: 60
            }
        } else {
            const otherData = await getOtherData({ blog });
            return {
                props: { blog, otherData},
                revalidate: 60
            }
        }
    } catch (error) {
        console.log('error in getStaticProps', error);
        return {
            notFound: true,
            revalidate: 60
        }
    }
}
export async function getStaticPaths() {
    try {
        const data = await getListOfPrerenderPages();
        const blogs = data?.length > 0 ? data : [];
        const paths = await Promise.all(blogs.map(async (blog) => ({
            params: { slug: blog.slug },
        })));
        return { paths, fallback: 'blocking' }
    } catch (error) {
        console.log('error in getStaticPaths', error);
        return {
            paths: [],
            fallback: 'blocking'
        }
    }
}`
2. Deploy it to Netlify using Essential Next.js version v4.1.1
3. Run yarn (npm run) build, then yarn (npm) start (make sure to start your server as well).
4. Try to change something in the data in your database and compare the results.

### Plugin version

v4.1.1

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Windows

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
[[plugins]]
package = "@netlify/plugin-nextjs"


```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi @katyperrycbt,
Does it not update at all? e.g. does it update if you check a few minutes later? The revalidate behaviour is a little different than the Next.js default: rather than having the revalidated page available immediately after it has been refreshed, the stale version may be served by some CDN nodes for up to 60s more.
