### ISSUE TITLE
[Bug]: Updating plugin to v4 causes 502 error on some routes

### ISSUE THREAD

**Issue by dabbott** [netlify/netlify-plugin-nextjs#1103]
### Summary

I'm currently running Next 11.1.2, and tried updating this plugin from v3.9.2 to v4.0.0. Some routes, I believe the ones with `getServerSideProps()`, now throw a 502 error.

Is v4 of this plugin supposed to work with Next 11, or should I update to Next 12? (I tried updating to Next 12 and the same routes fail, though with a standard 500 "Internal Server Error" page instead)

What set of versions should I use to try to reproduce this in another repo? Waiting for builds is pretty time-consuming so I'd love some suggestions for narrowing down the issue if you have any ideas.

For now I've downgraded back to v3.9.2 so I can continue to push new builds.

---

Here's the error I get with Next 11:

![Screen Shot 2022-01-05 at 4 24 40 PM](https://user-images.githubusercontent.com/1198882/148308730-de0e6d79-a48b-4437-92f2-cbbf96196873.png)

(👇  the error as json)

```json
{
   "errorType":"Runtime.ImportModuleError",
   "errorMessage":"Error: Cannot find module '/var/task/packages/studio721/.next/server/middleware-manifest.json'\nRequire stack:\n- /var/task/node_modules/next/dist/server/next-server.js\n- /var/task/.netlify/functions-internal/___netlify-handler/handlerUtils.js\n- /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js\n- /var/task/___netlify-handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
   "trace":[
      "Runtime.ImportModuleError: Error: Cannot find module '/var/task/packages/studio721/.next/server/middleware-manifest.json'",
      "Require stack:",
      "- /var/task/node_modules/next/dist/server/next-server.js",
      "- /var/task/.netlify/functions-internal/___netlify-handler/handlerUtils.js",
      "- /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js",
      "- /var/task/___netlify-handler.js",
      "- /var/runtime/UserFunction.js",
      "- /var/runtime/index.js",
      "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
      "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
      "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
      "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
      "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
      "    at Module.load (internal/modules/cjs/loader.js:950:32)",
      "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
      "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
      "    at internal/main/run_main_module.js:17:47"
   ]
}
```

And with Next 12:

![Screen Shot 2022-01-05 at 4 09 06 PM](https://user-images.githubusercontent.com/1198882/148307579-fa81d2a4-758c-4da5-8c71-890297702daf.png)

### Steps to reproduce

1. (I believe) Have a Next 11 project with pages using `getServerSideProps()`
2. Upgrade from plugin v3.9.2 to v4.0.0
3. Navigate to one of those routes

### Plugin version

4.0.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hey. This looks like it's using Next 12 for the server, but it was built with Next 11. The [code that tries to import that file](https://github.com/vercel/next.js/blob/ebf509539c0f4f519923c7780e269872059c384e/packages/next/server/next-server.ts#L315) was introduced in Next 12, but so was the code that generates it. Could you run either `npm ls next` or `yarn why next` depending on your package manager and see if you have multiple versions (and why)?

**Comment by dabbott** [comment]
Good catch! 

I think I had installed Next in the root of my monorepo to fix a failing build issue, and I must've installed the wrong version. 

I think this was the error that I fixed by installing `next` in the root... but installing just `critters` at the root instead seems to work. I don't know what `critters` is but I guess it's used somewhere in the build pipeline 🤔

![Screen Shot 2022-01-06 at 12 13 55 PM](https://user-images.githubusercontent.com/1198882/148445595-f63c65bf-6b7e-4ed8-9d58-5e2bc0f53a66.png)
 
Anyway, the plugin v4 works with both Next 11 and 12 for me now, so I'll close this.

**Comment by ascorbic** [comment]
Great! Is that log from version 3? If not, you should also remove all of the `next_*` functions created by version 3 of the plugin.

**Comment by ascorbic** [comment]
It needs at least 10.0.9

**Comment by redlpd** [comment]
@ascorbic Can you help me with this error

```{"errorType":"Error","errorMessage":"Cannot find module '/var/task/.next/server/middleware-manifest.json'\nRequire stack:\n- /var/task/node_modules/next/dist/server/next-server.js\n- /var/task/.netlify/functions-internal/___netlify-odb-handler/handlerUtils.js\n- /var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js\n- /var/task/___netlify-odb-handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","trace":["Error: Cannot find module '/var/task/.next/server/middleware-manifest.json'","Require stack:","- /var/task/node_modules/next/dist/server/next-server.js","- /var/task/.netlify/functions-internal/___netlify-odb-handler/handlerUtils.js","- /var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js","- /var/task/___netlify-odb-handler.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","   
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15 undefined)","   
   at Function.Module._load (internal/modules/cjs/loader.js:746:27 undefined)","   
   at Module.require (internal/modules/cjs/loader.js:974:19 undefined)","   
   at require .require (internal/modules/cjs/helpers.js:93:18 undefined)","   
   at NextNodeServer.getMiddlewareManifest (/var/task/node_modules/next/dist/server/next-server.js:521:20 undefined)","   
   at new Server .new Server (/var/task/node_modules/next/dist/server/base-server.js:126:40 undefined)","   
   at new NextNodeServer .new NextNodeServer (/var/task/node_modules/next/dist/server/next-server.js:73:9 undefined)","   
   at getBridge .getBridge (/var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js:46:28 undefined)","   
   at handler .handler (/var/task/.netlify/functions-internal/___netlify-odb-handler/___netlify-odb-handler.js:75:46 undefined)","   
   at Runtime.handler (/var/task/node_modules/@netlify/functions/dist/lib/builder.js:41:25 undefined)"]}
   ```

**Comment by Ju99ernaut** [comment]
Experienced the same issue with `next: "11.0.0"` but changing the version to `next: "^11.0.0"` seems to have fixed the issue for me.
