### ISSUE TITLE
[Bug]: ISR Bug when subpage of ISR page is another ISR page

### ISSUE THREAD

**Issue by caleblawrence** [netlify/netlify-plugin-nextjs#1110]
### Summary

Hello I have come across an ISR but where a sub page keeps reverting to stale data even though it's been refreshed. 

Here is the repo: https://github.com/caleblawrence/isr-bug-example
Netlify site: https://elegant-brown-75e87c.netlify.app/

How to reproduce
1. Go to the site. 
2. Click on "Link to another ISR page". 
3. Wait for about 2 minutes for ISR To refresh the time. 
4. Refresh the page to see that ISR has updated the time. 
5. Now open an incognito window (or a brand new window that's not using any cache from your other page)
6. Navigate to the same website and click on "Link to another ISR page" and you'll find the OLD time and not the new one that was refreshed

### Steps to reproduce

see description

### Plugin version

4.1.1

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi @caleblawrence 
Is this not the same scenario as #1061? i.e. the JSON is not updated at the same time as the HTML

**Comment by caleblawrence** [comment]
It's not because of this statement:
> The contract with ISR is that it's eventually-consistent, and new requests will get the new content.

In the reproduction steps even though a page is refreshed when a new user goes to it (simulated by opening an incognito chrome window) it's reverting back to the content at build time. This only appears to happen when you're on page and click a link that takes you to another ISR page.

**Comment by ascorbic** [comment]
I'm afraid I can't reproduce this. I did exactly as you said and I had the updated time. Bear in mind though that there is one issue with your reproduction: when you reload `/post`, you're loading a different file, because it fetches the HTML rather than the JSON. To be sure that it's updated, go into the network panel and see when `post.json` is loaded, open that in another window and refresh that to see.
