### ISSUE TITLE
Feature request: more verbose logs for incremental static regeneration

### ISSUE THREAD

**Issue by whitep4nth3r** [netlify/netlify-plugin-nextjs#1116]
To help diagnose issues with Next.js ISR, or just to have more peace of mind that ISR is actually working, it would be great to see more verbose logs in the Netlify UI when ISR is running/being checked.

Here's a current example of what the logs show when ISR is triggered:

```
3:00:50 PM: 06bd6d82 Duration: 2862.14 ms	Memory Usage: 93 MB	Init Duration: 757.98 ms
```

Here are two examples of the additional data I'd like to see.

For example, when data is being checked/refreshed, the path to the data:

```
[GET] /_next/data/abcdefg/pageName.json
```

Or, if an api function is being called:

```
[GET] /api/functionName
```

**Comment by ascorbic** [comment]
I love this, and honestly it could be for all handler responses. Would be good to include render mode too. Really simple change to add a console log in here somewhere: https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/templates/getHandler.ts#L63-L108
