### ISSUE TITLE
[Bug]: Next.js middlewares are currently broken on Netlify

### ISSUE THREAD

**Issue by ivorpad** [netlify/netlify-plugin-nextjs#1141]
### Summary

Next.js throws an error when `hostname` and `port` are not provided in the custom server since v12.0.5-canary.18 — as a result it breaks middleware in Netlify:

[next.js@base-server.ts#L725-L729](https://github.com/vercel/next.js/blob/2c9c8f76a36f919bae8e10d7965463080f10e277/packages/next/server/base-server.ts#L725-L729)
```js
// For middleware to "fetch" we must always provide an absolute URL
const url = getRequestMeta(params.request, '__NEXT_INIT_URL')!
 if (!url.startsWith('http')) {
   throw new Error(
     'To use middleware you must provide a `hostname` and `port` to the Next.js Server'
   )
}
```

<img width="1230" alt="Screenshot 2022-01-18 at 23 47 04" src="https://user-images.githubusercontent.com/52452/150162424-ae8e1c8d-2740-44f3-9fc2-d4b73140eba0.png">

Ref: https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/templates/getHandler.ts#L46-L50

### Steps to reproduce

1. Fork this simple Next.js app (`npx create-next-app` with one middleware) https://github.com/ivorpad/repro-nextjs-middleware
2. Deploy to Netlify
3. Go to `/api/users`
4. Watch the `___netlify-handler` function logs

### A link to a reproduction repository

https://github.com/ivorpad/repro-nextjs-middleware

### Plugin version

4.2.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
command = "npm run build"
functions = "out_functions"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by gussalesdev** [comment]
I have the same issue here but running the server locally. I did an update to version 12.0.8 yesterday and this error started happening. I rollback to 12.0.7 and worked. Maybe there is some bug in the latest version.

**Comment by ascorbic** [comment]
Thank you both for the detailed report and information. I have a fix ready and should be able to put out a release on Monday.
