### ISSUE TITLE
Deployment broken with Nx

### ISSUE THREAD

**Issue by ebrehault** [netlify/netlify-plugin-nextjs#115]
**Describe the bug**
A typical Next.js app built into an Nx monorepo will be located in a subfolder like `./apps/my-site`.
When the `next.config.js`file is not in the project root folder, the`onBuild` command fails with

```
Error: No static assets found in .next dist (aka no /.next/static). Please check your project configuration. Your next.config.js must be one of `serverless` or `experimental-serverless-trace`. Your build command should include `next build`.

```

Using `base` in `netlify.toml` [build] section does not fix the problem (but it is not the proper approach according the documentation as it is supposed to target a folder containing `package.json`, while an Nx project contains its `package.json` in its root, not in each app folder).

**To Reproduce**
1. Create a monorepo project with Nx
2. Add a Next.js site
3. Publish it on Netlify

**Expected behavior**
The deployment should work

**Versions**
- Next.js: ^10.0.8
- plugin (if installed at fixed version): ^3.0.0

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]
 - netlify/cli version:

**If you're using file-based installation**
- netlify.toml:

```
[build]
  command   = "npm run build"
  publish   = "dist/apps/basic"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by jlengstorf** [comment]
thanks, @ebrehault — we're digging into this!

**Comment by rayriffy** [comment]
@jlengstorf I believe that `next.config.js` should be resolve in publish directory, not directly point to the root of the repository

https://github.com/netlify/netlify-plugin-nextjs/blob/2f564b151552358689ea578563a52f2713345ccd/helpers/getNextConfig.js#L15

**Comment by rayriffy** [comment]
Good news, I found a workaround. What you have to do is to build Next application to root repository instead by passing `--output-path` arguments. [More detail](https://nx.dev/latest/react/guides/nextjs#deploying-to-vercel)

```
yarn nx build basic --output-path=./
```

**Comment by simonpeters** [comment]
@rayriffy your fix doesn't work for me. 

I keep getting this error.

`NX   ERROR  Running target "app:build" failed`

anyone else found a work around?

**Comment by lindsaylevine** [comment]
hey all! thanks for your patience on this. we're finally getting to work on these nx/greater monorepo issues. we're consolidating everyone's issues into #433, so we'll close this in favor of that. please follow along there, but we'll try to circle back here, too, whenever we release support! 🙏

**Comment by ascorbic** [comment]
@ebrehault This is now released, but not enabled by default yet. Could you try it out? You need to `npm install @netlify/plugin-nextjs@latest` and then [look at the docs](https://ntl.fyi/nx-next) to see how it needs to be configured

**Comment by ebrehault** [comment]
@ascorbic it works just fine! thanks 🙏 
It is a bit counterintuitive to target a publish folder inside the app folder (that's not the Nx way…), but I guess that's not a problem :)

**Comment by ascorbic** [comment]
Thanks for the update! Yes, unfortunately we have to do that, as we need to be able to work out where the app folder is, and setting the publish dir allows us to do this. Otherwise we can't find the config file or the output dir

**Comment by ebrehault** [comment]
Yes, well that's definitely not a problem, moreover the error messages we get from the CLI are very accurate so even someone who skipped the docs (as I did :) ) will understand what to do.
Great work!
