### ISSUE TITLE
[Bug]: Netlify CMS/ Next.JS starter template error: The directory "dist" does not contain a Next.js production build

### ISSUE THREAD

**Issue by vnn8248** [netlify/netlify-plugin-nextjs#1184]
### Summary

Using the "one-click" Next.JS blog template with Netlify CMS, the build fails.

Following the steps to connect Github and deploy on Netlify are straightforward and just a couple of clicks.
[https://www.netlifycms.org/docs/start-with-a-template/]

Error from deploy log in Netlify:
────────────────────────────────────────────────────────────────
9:39:13 AM:   Plugin "@netlify/plugin-nextjs" failed                        
9:39:13 AM: ────────────────────────────────────────────────────────────────
9:39:13 AM: ​
9:39:13 AM:   Error message
9:39:13 AM:   Error: The directory "dist" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.
9:39:13 AM:   In most cases it should be set to ".next", unless you have chosen a custom "distDir" in your Next config.
9:39:13 AM:   If you are using "next export" then you should set the environment variable NETLIFY_NEXT_PLUGIN_SKIP to "true".
9:39:13 AM: ​
9:39:13 AM:   Plugin details
9:39:13 AM:   Package:        @netlify/plugin-nextjs
9:39:13 AM:   Version:        4.2.1
9:39:13 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
9:39:13 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
9:39:13 AM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
9:39:13 AM: ​
9:39:13 AM:   Error location
9:39:13 AM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
9:39:13 AM:       at checkNextSiteHasBuilt (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/verification.js:68:16)
9:39:13 AM:       at onBuild (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/index.js:37:50)
9:39:13 AM: ​

### Steps to reproduce

Navigate here
[https://www.netlifycms.org/docs/start-with-a-template/]

Click on the Next.js template
Connect Github
Observe Netlify deploy logs

### Plugin version

4.2.1

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by jadamconnor** [comment]
I get the same error but instead of with "dist" it specifies that my "public" folder is missing the next build.

**Comment by ascorbic** [comment]
@vnn8248 It looks like the template needs updating. Because the site uses `next export`, you need to do as the message says and set `NETLIFY_NEXT_PLUGIN_SKIP` to true. You can set this in the Build > Enviornment section in the site UI.

**Comment by jadamconnor** [comment]
> @jadamconnor If your build command is `next build`, you should set the publish folder to `.next`. If you are using `next export`, follow the intruction about setting `NETLIFY_NEXT_PLUGIN_SKIP`

I am using `next build` and I have not changed its default from .next.

**Comment by ascorbic** [comment]
Could you open another issue, as I think it's different. Please can you include the details requested in the tempkate, particularly the build logs. Thanks.

**Comment by ascorbic** [comment]
Hi @accexs 
Can you let me know where you are setting `NETLIFY_NEXT_PLUGIN_SKIP`? It doesn't seem to be being found.

**Comment by nivvyart** [comment]
This worked for me after updating the build env variable

Here are more details on setting this build variable:
https://docs.netlify.com/configure-builds/common-configurations/#next-js

For apps that use next export to generate static HTML, set the NETLIFY_NEXT_PLUGIN_SKIP [environment variable](https://docs.netlify.com/configure-builds/environment-variables/) to true.

**Comment by hkennyv** [comment]
FYI for anyone else having this problem. I just resolved this on my repo using the following:

-  Set `netlify.toml` to this:

```
[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
publish = ".next"
```

- Update build settings in netlify ui (Deploy settings > Build settings)

```
Build command: yarn build
Publish directory: .next
```

What I had before (was working until today):

```
[build]
    command = "yarn build && yarn export"
    publish = "out"
```

Build settings:

```
Build command: yarn build && yarn export
Publish directory: out
```

**Comment by ascorbic** [comment]
Closing this as it should be fixed by setting `NETLIFY_NEXT_PLUGIN_SKIP`. If this doesn't solve it, please open a new issue

**Comment by codewithmalik** [comment]
Hi, I am trying to deploy nextjs app on netlify. it keeps failing below is the error I got.

<img width="1219" alt="Screenshot 2022-12-03 at 04 49 34" src="https://user-images.githubusercontent.com/4702828/205421254-93ac5ce7-56cb-48cf-9bfc-a003ca245511.png">
<img width="1212" alt="Screenshot 2022-12-03 at 04 49 24" src="https://user-images.githubusercontent.com/4702828/205421251-33f7096d-5ad6-4d97-bdb3-9941b5a87b27.png">

**Comment by ascorbic** [comment]
@codewithmalik That's a Next.js error about a problem with your site, rather than a problem speicifically with building on Netlify. There's a problem with your site in your es1.js page.
