### ISSUE TITLE
[Bug]:  ___netlify-handler fails with boilerplate NX Mono Repo

### ISSUE THREAD

**Issue by Joroze** [netlify/netlify-plugin-nextjs#1278]
### Summary

After minimal NX Workspace setup with a boilerplate NextJS project generated, **___netlify-handler** errors out/fails for all invokations, despite successful deployment.

TLDR: NextJS API Routes are not working, due to **___netlify-handler** errors.

`{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, chdir '/var/task' -> '/var/task/apps/frontend'","trace":["Error: ENOENT: no such file or directory, chdir '/var/task' -> '/var/task/apps/frontend'","    at process.wrappedChdir [as chdir] (internal/bootstrap/switches/does_own_process_state.js:116:14)","    at /var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js:19:13","    at Object.<anonymous> (/var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js:106:3)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:12)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:93:18)","    at Object.<anonymous> (/var/task/___netlify-handler.js:1:18)"]}`

### Steps to reproduce

```
npx create-nx-workspace nx-netlify-test
npx: installed 48 in 2.008s
✔ What to create in the new workspace · next
✔ Application name                    · frontend
✔ Default stylesheet format           · @emotion/styled
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

 >  NX   Nx is creating your v13.9.4 workspace.
```

Add a general api route `/api/index.tsx`
```
export default function handler(req, res) {
  res.status(200).json({
    body: 'Hello world',
  });
}
```

**Deployed** using Netlify Web GUI 

### A link to a reproduction repository

https://github.com/Joroze/nx-netlify-test

### Plugin version

4.2.8

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNx = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

module.exports = withNx(nextConfig);

```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
https://app.netlify.com/sites/delightful-sunburst-c3897b/deploys/623b28398dc14d008c668b54
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
https://delightful-sunburst-c3897b.netlify.app/.netlify/functions/___netlify-handler
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Thanks for the report. This looks like it was a regression introduced in version 4.2.8 of the plugin. Could you try downgrading it to `4.2.9` and see if that fixes it for now?

**Comment by aruke** [comment]
I'm having the same error after upgrading the plugin in UI. 
How do I downgrade the version? Do I have to specify it in `netlify.toml` file?

**Comment by Joroze** [comment]
> Thanks for the report. This looks like it was a regression introduced in version 4.2.8 of the plugin. Could you try downgrading it to `4.2.7` and see if that fixes it for now?
> Hey. You shoudl install it in your package.json. Something like `npm i -D @netlify/plugin-nextjs@4.2.7`

Doing the following fixes my issues. Hopefully latest version of the plugin is fixed soon! Thanks.

**Comment by aruke** [comment]
Same here, downgrading the plugin solved the issue.
I also found the related docs link: https://docs.netlify.com/configure-builds/build-plugins/#manage-plugin-versions

**Comment by iannatividad** [comment]
> Thanks for the report. This looks like it was a regression introduced in version 4.2.8 of the plugin. Could you try downgrading it to `4.2.7` and see if that fixes it for now?

This worked for me. For those who don't have `netlify.toml` currently, no need to add other configs, just add the `[[plugin]]` and it will still build.
