### ISSUE TITLE
[Bug]: Broken images with content-type: binary/octect-stream

### ISSUE THREAD

**Issue by oscarsala** [netlify/netlify-plugin-nextjs#1283]
### Summary

Since the introduction of `netlify-ipx` images with a `content-type: binary/octet-steam` no longer work

https://github.com/netlify/netlify-ipx/issues/10

### Steps to reproduce

Use the Image component with a resource returning a `binary/octect-stream ` content-type

### Plugin version

4.0.0

**Comment by MartijnHols** [comment]
Also broken with `content-type: application/octet-stream`.

**Comment by ascorbic** [comment]
Fixed in https://github.com/netlify/netlify-ipx/pull/16
