### ISSUE TITLE
Enterprise escalation: v4.3.0 plugin installation fails (before build is run) with seeming Node.js out of memory issue

### ISSUE THREAD

**Issue by fool** [netlify/netlify-plugin-nextjs#1287]
Two separate enterprise reports of this failure mode during plugin installation of version 4.3.0 (and I don't see anything in the version 4.3.1 changelog that seems relevant to memory usage, so have not asked for a repro on 4.3.1):

```
11:56:59 AM: ❯ Installing plugins
11:56:59 AM:    - @netlify/plugin-nextjs@4.3.0
12:10:42 PM: ​
12:10:42 PM: ────────────────────────────────────────────────────────────────
12:10:42 PM:   Dependencies installation error                               
12:10:42 PM: ────────────────────────────────────────────────────────────────
12:10:42 PM: ​
12:10:42 PM:   Error message
12:10:42 PM:   Error while installing dependencies in /opt/build/repo/web/.netlify/plugins/
12:10:42 PM: ​
12:10:42 PM:   <--- Last few GCs --->
12:10:42 PM: ​
12:10:42 PM:   [1424:0x5a8d240]   816925 ms: Scavenge 2024.4 (2080.2) -> 2009.2 (2080.2) MB, 3.7 / 0.0 ms  (average mu = 0.158, current mu = 0.030) allocation failure
12:10:42 PM:   [1424:0x5a8d240]   816967 ms: Scavenge 2024.6 (2080.2) -> 2009.4 (2080.4) MB, 4.8 / 0.0 ms  (average mu = 0.158, current mu = 0.030) allocation failure
12:10:42 PM:   [1424:0x5a8d240]   819393 ms: Mark-sweep 2024.7 (2080.4) -> 2008.6 (2080.7) MB, 2393.5 / 0.0 ms  (average mu = 0.173, current mu = 0.190) allocation failure scavenge might not succeed
12:10:42 PM: ​​
12:10:43 PM: Creating deploy upload records
12:10:42 PM:   <--- JS stacktrace --->
12:10:42 PM: ​
12:10:42 PM:   FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
12:10:42 PM:    1: 0xb00d90 node::Abort() [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    2: 0xa1823b node::FatalError(char const*, char const*) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:43 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
12:10:42 PM:    3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    5: 0xea6105  [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    6: 0xea6be6  [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    7: 0xeb4b1e  [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:    9: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:   10: 0xe7990a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:   11: 0x11f2f06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM:   12: 0x15e7819  [npm install @netlify/plugin-nextjs@4.3.0]
12:10:42 PM: ​
12:10:42 PM:   Resolved config
12:10:42 PM:   build:
12:10:42 PM:     base: /opt/build/repo/web
12:10:42 PM:     command: npm run build
12:10:42 PM:     commandOrigin: config
```

Both customers have submitted support tickets so here are the (only visible to netlify employees) tickets with links to affected deploys.  Both customers report this as a behavior change since 4.2.7.

https://netlify.zendesk.com/agent/tickets/88342
https://netlify.zendesk.com/agent/tickets/88343
https://netlify.zendesk.com/agent/tickets/88434
https://netlify.zendesk.com/agent/tickets/88424
https://netlify.zendesk.com/agent/tickets/88364

**Comment by fool** [comment]
(at least) two reports from the forum of same issue: https://answers.netlify.com/t/installing-netlify-plugin-nextjs-4-3-0-hangs-on-site-setup/54136

related slack thread:  https://netlify.slack.com/archives/C02SFV3BGNS/p1648582754848729

**Comment by ascorbic** [comment]
4.3.1 should now be the default. There's nothing specific in there to fix it, but if the problem was something odd with dependencies then this may just be enough of a nudge to fix it

**Comment by morganpartee** [comment]
Hey I updated on the netlify forum, but it works fine when installed as a dev dependency pre-build with version 4.3.1. Something is funky with that cached version I guess?

**Comment by CoolTechYT** [comment]
I am having an issue deploying with this...

```
7:34:47 PM: ❯ Installing plugins
7:34:47 PM:    - @netlify/plugin-nextjs@4.3.1
7:49:38 PM: ​
7:49:38 PM: ────────────────────────────────────────────────────────────────
7:49:38 PM:   Dependencies installation error                               
7:49:38 PM: ────────────────────────────────────────────────────────────────
7:49:38 PM: ​
7:49:38 PM:   Error message
7:49:38 PM:   Error while installing dependencies in /opt/build/repo/.netlify/plugins/
```

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by morganpartee** [comment]
Oh sorry, should've been more clear! At least for me, this fixed the issue @CoolTechYT 

Either `yarn add -D @netlify/plugin-nextjs` or adding ` "@netlify/plugin-nextjs": "4.3.1"` to your package.json under devDependencies! For whatever reason, forcing netlify to install it ahead of time works.

**Comment by xxxooo** [comment]
Netlify plugin setting page should provide version selection for this kind of issue sometimes happened.

**Comment by xxxooo** [comment]
I found this issue is related to netlify cache, not the plugin version.

If the deploy log has
```
Fetching cached dependencies
Starting to download cache of xxx.xMB
Finished downloading cache in xx.xxxs
```
No matter using 4.3.1 or 4.2.8 can deploy successfully.

When the site has no cache 
```
No cached dependencies found. Cloning fresh repo
  or
Failed to fetch cache, continuing with build
```
Using 4.3.1 or 4.2.8 deploy both failed at `Installing plugins`

**Comment by Ronak-59** [comment]
Just tried deploying a git repo normally and it results in same error with `v4.2.8` after waiting for 15 minutes.

![image](https://user-images.githubusercontent.com/8841124/160815541-03f4ba2a-945b-4df6-ac54-ab969de8c3bb.png)

**Comment by xxxooo** [comment]
> Just tried deploying a git repo normally and it results in same error with `v4.2.8` after waiting for 15 minutes.
> 
> ![image](https://user-images.githubusercontent.com/8841124/160815541-03f4ba2a-945b-4df6-ac54-ab969de8c3bb.png)

And this still count build minutes, right ?

**Comment by kamerat** [comment]
I just updated to 4.2.8 and this happened for me too. I also see no option to downgrade in the UI.
<details>
    <summary>image</summary>

![image](https://user-images.githubusercontent.com/11461961/160838338-4fd5dd43-f723-4cd5-acf2-34cc4909e57c.png)

</details>

**Comment by sirion1987** [comment]
@kamerat, How do you defined 4.2.7 version of the plugin?

**Comment by justinluk** [comment]
I ran into this on a project I'm working on and had to manually install v4.2.7 to get builds working again.

**Comment by dassidas** [comment]
We've run into this with our Next deploys on both `4.2.7` and `4.2.8`, but weirdly, not all branches seem to be impacted. Going to try a manual installation of `4.3.1` to see if it fixes the issue. The plugin installation hangs regardless of if we try to deploy with or without the cache.

**Comment by andrewalex** [comment]
Can confirm, same issue on a new site.  
However, I upgraded a previous site from 4.2.7 to 4.2.8 with no issues.

**Comment by xxxooo** [comment]
Seems netlify infura have fix this problem.
I used the same code, the same config and the same setting. It works fine today.

**Comment by ascorbic** [comment]
I'm closing this because there have been no indications that this is still happening. If anybody still experiences it, please open a new issue.
