### ISSUE TITLE
Support next/image

### ISSUE THREAD

**Issue by amacneil** [netlify/netlify-plugin-nextjs#129]
It looks like initial support for `next/image` was requested in `next-on-netlify` in https://github.com/netlify/next-on-netlify/issues/70 and added in https://github.com/netlify/next-on-netlify/pull/138.

Now that `next-on-netlify` is deprecated, it's unclear what the recommended method for serving Next.js images is. 

Current, if the `<Image />` tag is used in a Next.js site, deploys to Netlify fail with:

```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start`, which starts the Image Optimization API.
    - Use Vercel to deploy, which supports Image Optimization.
    - Configure a third-party loader in `next.config.js`.
  Read more: https://err.sh/next.js/export-image-api
```

**Comment by jlengstorf** [comment]
hey, @amacneil! right now you'd need to stop using `next export` to enable `next/image` support, but we _do_ support it now

I think it might be possible to make `next export` work as expected, though, so this is worth digging into. thanks for opening this!

**Comment by amacneil** [comment]
Interesting. I believe I got the export line from your template, so it probably needs updating if that is the case:

https://github.com/netlify-templates/next-starter-jamstack/blob/master/package.json#L6

FWIW, `next export` doesn't work locally either when using `next/image`.

**Comment by cassidoo** [comment]
@amacneil `next/image` isn't meant to work with `next export` in general:
https://nextjs.org/docs/advanced-features/static-html-export#caveats

We do have to update that template, until then, this might be of interest for you:
https://github.com/cassidoo/next-netlify-starter
