### ISSUE TITLE
Add `netlify-plugin` npm keyword

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#13]
Adding the `netlify-plugin` npm `keyword` would help users find this plugin ([see documentation](https://docs.netlify.com/configure-builds/build-plugins/share-plugins/#publish-to-npm)).

**Comment by lindsaylevine** [comment]
https://github.com/netlify/netlify-plugin-nextjs/commit/9c7adfab317f28448593267effaaab6233581185
