### ISSUE TITLE
[Bug]: Plugin "@netlify/plugin-nextjs" 

### ISSUE THREAD

**Issue by enzo-mourany** [netlify/netlify-plugin-nextjs#1361]
### Summary

Plugin "@netlify/plugin-nextjs" failed
Error: The directory "/opt/build/repo/build" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.

### Steps to reproduce

1. Deploy the next JS app with netlify

### Plugin version

4.7.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi @enzo-mourany 
Can you provide some more details of your setup please, including your build command and your `next.config.js`

**Comment by enzo-mourany** [comment]
Sure @ascorbic 

Build command : nom run build
next.config.js : 

`/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig;
`

**Comment by ascorbic** [comment]
Thanks. Can you change your `publish` directory from `build` to `.next`, either in the UI or in the `netlify.toml`

**Comment by enzo-mourany** [comment]
It's work, thanks @ascorbic
