### ISSUE TITLE
Support nextConfig.images.formats

### ISSUE THREAD

**Issue by ascorbic** [netlify/netlify-plugin-nextjs#1374]
The next/image edge function returns AVIF images if the browser supports it. However it can be slower to process than other formats, so may time out (e.g. https://github.com/netlify/netlify-plugin-nextjs/issues/687#issuecomment-1113524399 ). In sites that need to use large images, a workaround could be to add support for [specifying supported image formats](https://nextjs.org/docs/api-reference/next/image#acceptable-formats), and not rewrite to AVIF format if it is disabled. The value could be read from the config and included in the edge function.

**Comment by hughrawlinson** [comment]
I didn't realize that the nextconfig.images.formats config wasn't supported in Netlify, this explains a lot! Thanks! 😄 Subscribing to this issue.
