### ISSUE TITLE
Error creating publish and functions directories for production build

### ISSUE THREAD

**Issue by MikeM2343** [netlify/netlify-plugin-nextjs#141]
**Describe the bug**
1. The build fails on the netlify server saying that the Web/out_functions and Web/out_publish directories do not exist
2. The netlify build process never finishes (stays at "building"), requiring you to "Cancel Deploy"

**To Reproduce**
1. Mono repo containing libraries and the main web app
2. Trigger the deploy that runs a script in the root of the repo that builds the libraries and then builds the main Next app

**Expected behavior**
The app builds without any errors

**Versions**
- Next.js: 10.0.8
- plugin (if installed at fixed version): 3.0.3

**If you're using file-based installation**
**netlify.toml: **
```
[build]
  command   = "yarn lerna run build"
  functions = "Web/out_functions"
  publish   = "Web/out_publish"

[dev]
  functions = "Web/out_functions"
  publish   = "Web/out_publish"
  autoLaunch = false
  command = "yarn run dev"
  targetPort = 3000
  framework = "#custom"

  [[plugins]]
  package = "@netlify/plugin-nextjs" 
```

**Failed Build file**
[NetlifyBuild.log](https://github.com/netlify/netlify-plugin-nextjs/files/6144813/NetlifyBuild.log)

Hello,  

I'm not sure I have the correct netlify.toml configuration for the monorepo.  I'm pretty sure I shouldn't be specifying a base directory because I need to run a script to build both my libraries and the main app from the root of the repo.

Is there any way to test this locally?  I know that when using next-on-netlify, and doing a build, the out_publish and out_functions directories were created on my local system.

Thanks,
Mike

**Comment by MikeM2343** [comment]
I've done a bit more digging and here's what I've found
- the Netlify deploy was not picking up the @netlify/plugin-nextjs plugin from the toml file in the Web directory as per the structure below
- When I added the netlify plugin via the Netlify UI and reran the deploy, I got a different error as indicated in this log:
  [NetlifyBuild2.log](https://github.com/netlify/netlify-plugin-nextjs/files/6151974/NetlifyBuild2.log)
- I tried running "netlify build" locally.  With debugging, I found that the plugin.onBuild was passed the proper PUBLISH_DIR, and FUNCTIONS_SRC constants (Web\out_publish and Web\out_functions) as per the toml file, but that the publish and functions properties of netlifyConfig had an extra 'Web' directory part in it.  i.e. <rootDir>\\Web\\Web\\out_publish.  This may not be the case in a web-based deploy, but it does seem to be the case for netlify build.  The netlifyConfig also had 'base' set to <rootDir>\\Web

My monorepo directory structure
```
/
| -- libs/
|    | -- lib1
|    | -- lib2
|    | -- ...
| -- Web/
|    | -- src/
|    | -- netlify.toml
|    | -- package.json 
| -- package.json (for lerna stuff)
```

**Comment by lindsaylevine** [comment]
hey @MikeM2343! thanks for your patience on this. we're finally getting to work on these greater monorepo issues. we're consolidating everyone's issues into #433, so we'll close this in favor of that. please follow along there, but we'll try to circle back here, too, whenever we release support! 🙏
