### ISSUE TITLE
[Bug]: next.js deploy broken on netlify

### ISSUE THREAD

**Issue by coreymaroney** [netlify/netlify-plugin-nextjs#1444]
### Summary

Upon default build the following error is received.
`In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app`

### Steps to reproduce

1. Deploy standard next.js server on netlify
2. Build will fail with plugin-nextjs
3. Specific error is `In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app`

### Plugin version

latest

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

Default configuration

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi. Can you share the full build logs, and `next.config.js` please? The message you shared just says where the error was, not what it was.

**Comment by ericapisani** [comment]
Hi @coreymaroney ,

Due to inactivity on this issue, we're going to close this for the time being. If you're still experiencing issues, please provide the information @ascorbic mentioned above, and feel free to reopen this.
