### ISSUE TITLE
Support for redirects and rewrites

### ISSUE THREAD

**Issue by joaogarin** [netlify/netlify-plugin-nextjs#147]
**Is your feature request related to a problem? Please describe.**
I would like to merge existing projects to netlify, But we already are using Nextjs default rewrites and redirects..is it on the roadmap to support them? or is it always going to be a netlify redirect / rewrites features.

**Describe the solution you'd like**
Use NextJs features (redirects, rewrites, image etc) without any platform specific behavior

**Describe alternatives you've considered**
No real alternative. 

**Additional context**
Right now we self host our applications. We would just keep doing that or consider some other alternative that supports nextjs as is (like vercel or others) although we already pay for Netlify (for other projects where we are super happy with it), we would just like to have it all in one place.

**Comment by lindsaylevine** [comment]
hey @joaogarin! i see you also commented on https://github.com/netlify/netlify-plugin-nextjs/issues/150. will close this as a duplicate and keep in mind your ask for this feature. given [finn's comment](https://github.com/netlify/netlify-plugin-nextjs/issues/150#issuecomment-652056892), i'm not sure at the moment how we'd be able to provide full support.
