### ISSUE TITLE
[Bug]: Images not being handled via edge functions when visitor access is protected

### ISSUE THREAD

**Issue by pauloamgomes** [netlify/netlify-plugin-nextjs#1489]
### Summary

I have a next.js website (next 12.2.3) with the edge functions enabled, however, when Netlify access control is on (global password) images are not be processed using the edge function.

### Steps to reproduce

1. Enable access control
2. Visit the website and confirm using the network inspector image format.
No avif/webp images are returned.
3. Disable access control
4. Visit the website and confirm using the network inspector image format.
Avif/webp images are returned.

### Plugin version

4.12.2

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ascorbic** [comment]
Hi. Currently edge functions are [not supported](https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/limits/#feature-limitations) when using site-wide password protection. This will change before they leave beta.

**Comment by pauloamgomes** [comment]
Thanks @ascorbic for the info, was not able to find it in the docs but it's clear now, closing.
