### ISSUE TITLE
Support next.config.js redirects, rewrites, headers

### ISSUE THREAD

**Issue by scopsy** [netlify/netlify-plugin-nextjs#150]
First of all, thank you for the amazing work with this package!

Currently when defining experimental rewrites in `next.config.js` they are not respected in netlify and throw 404 error from netlify. Any chance they can be supported? 

example of the config file:
```
module.exports = {
  target: 'serverless',
  experimental: {
    redirects() {
      const redirects = [
        {
          // Redirect root link with trailing slash to non-trailing slash, avoids 404 - See https://github.com/vercel/next.js/discussions/10651#discussioncomment-8270
          source: '/:locale/',
          destination: '/:locale',
          permanent: process.env.NEXT_PUBLIC_APP_STAGE !== 'development', // Do not use permanent redirect locally to avoid browser caching when working on it
        },
        {
          // Redirect link with trailing slash to non-trailing slash (any depth), avoids 404 - See https://github.com/vercel/next.js/discussions/10651#discussioncomment-8270
          source: '/:locale/:path*/',
          destination: '/:locale/:path*',
          permanent: true
        },
      ];

      return redirects;
    },
    rewrites() {
      const rewrites = [
        {
          source: '/',
          destination: '/api/autoRedirectToLocalisedPage',
        },
        {
          source: `/:locale((?!${noRedirectBasePaths.join('|')})[^/]+)(.*)`,
          destination: '/api/autoRedirectToLocalisedPage',
        },
      ];

      return rewrites;
    },
  },
};

```

**Comment by odenirdev** [comment]
i have the same problem of @scopsy

**Comment by odenirdev** [comment]
i need the rewrites next.config.js

**Comment by TimNZ** [comment]
To be clear: custom header in next.config.js are not supported?


```
headers: async () => {
	return [
		{
		source: "/(.*\\.(?:jpg|jpeg|png|gif))",
		headers: [
		{
			key: "Cache-Control",
			value: "public, max-age=3600",
		},
	],
	},
	]
	},
```

**Comment by tbgse** [comment]
Hi all,

jumping on this issue because we're facing a possibly related problem: We want to create a rewrite to our api routes using the netlify.toml file, looking like this:

```
[[redirects]]
  from = "/custom-api-route/*"
  to = ""/api/:splat"
  status = 200
```

However, it seems like all of the requests to `/custom-api/*` end up with a 404 status. Possibly because the nextjs api routes itself are already configured as rewrites in the generated toml file by the nextjs plugin for netlify?

Is this a known issue or am I doing something wrong? When I configure non-api route redirects in the netlify.toml file, everything works as expected 🤔

**Comment by ascorbic** [comment]
Fixed in version 4

**Comment by wildabeast** [comment]
I cannot for the life of me get a CSP set on the root page of my nextjs/netlify app. 

next.config.js:
```
    async headers() {
      return [
        {
          source: '/',
          headers: [
            {
              key: 'Content-Security-Policy',
              value: "default-src 'self';",
            },
          ]
        }
      ];
    },
```

netlify.toml
```
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
```

_headers
```
/*
  Content-Security-Policy: default-src 'self';
```

**Comment by adshodgson** [comment]
> I cannot for the life of me get a CSP header set on the root page of my nextjs/netlify app.
> 
> next.config.js:
> 
> ```
>     async headers() {
>       return [
>         {
>           source: '/',
>           headers: [
>             {
>               key: 'Content-Security-Policy',
>               value: "default-src 'self';",
>             },
>           ]
>         }
>       ];
>     },
> ```
> 
> netlify.toml
> 
> ```
> [[headers]]
>   for = "/*"
>   [headers.values]
>     Content-Security-Policy = "default-src 'self';"
> ```
> 
> _headers
> 
> ```
> /*
>   Content-Security-Policy: default-src 'self';
> ```
> 
> Any guidance? thx

Having similar issue, any resolution?

**Comment by Hexi1997** [comment]
> > I cannot for the life of me get a CSP header set on the root page of my nextjs/netlify app.
> > next.config.js:
> > ```
> >     async headers() {
> >       return [
> >         {
> >           source: '/',
> >           headers: [
> >             {
> >               key: 'Content-Security-Policy',
> >               value: "default-src 'self';",
> >             },
> >           ]
> >         }
> >       ];
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > netlify.toml
> > ```
> > [[headers]]
> >   for = "/*"
> >   [headers.values]
> >     Content-Security-Policy = "default-src 'self';"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _headers
> > ```
> > /*
> >   Content-Security-Policy: default-src 'self';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any guidance? thx
> 
> Having similar issue, any resolution?



> > I cannot for the life of me get a CSP header set on the root page of my nextjs/netlify app.
> > next.config.js:
> > ```
> >     async headers() {
> >       return [
> >         {
> >           source: '/',
> >           headers: [
> >             {
> >               key: 'Content-Security-Policy',
> >               value: "default-src 'self';",
> >             },
> >           ]
> >         }
> >       ];
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > netlify.toml
> > ```
> > [[headers]]
> >   for = "/*"
> >   [headers.values]
> >     Content-Security-Policy = "default-src 'self';"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _headers
> > ```
> > /*
> >   Content-Security-Policy: default-src 'self';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any guidance? thx
> 
> Having similar issue, any resolution?

Hey, Have you solved this problem? I encountered it too
