### ISSUE TITLE
Improve next/image performance

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/netlify-plugin-nextjs#155]
This issue follows up https://github.com/netlify/next-on-netlify/issues/70. Initial support for next/image was merged in https://github.com/netlify/next-on-netlify/pull/138. However, that initial support is not performant since the Netlify function will re-run on every request without any caching.

Our next step is to improve this performance with caching. This will depend on internal work at Netlify. Please follow this issue for updates on next/image performance!! :)

**Comment by juliefleet** [comment]
Hey @lindsaylevine,
Any update on a release date for this feature? 🙏
Thanks!

**Comment by GBrachetta** [comment]
Looking forward to the release.

Just deployed a Next.js app to Netlify with 2 very small `<Image />` components (no more than 50KB each) and they take a ridiculous amount of time to render: up to 3s for 36Kb after `<Image />` optimisation!

**Comment by lindsaylevine** [comment]
@GBrachetta @juliefleet and everyone - thanks so much for your patience! last week we had two lucky folks from this thread test out our solution. on/around april 13th, we'll be able to finally offer it to everyone. 👀 hang tight!

**Comment by kpfromer** [comment]
I have been watching this thread for a bit and I am super excited! Thanks for all the hard work @lindsaylevine !

**Comment by GBrachetta** [comment]
Thank you @lindsaylevine, looking forward to test it and compare it with Vercel's native solution.

Will this require any action from us once it's been released (rebuild/redeploy or reinstallation of the plugin)?

**Comment by lindsaylevine** [comment]
@GBrachetta

if you have your plugin installed at a fixed version (i.e. you npm installed it), then you'll need to upgrade the plugin version with the new release (when it happens).

if you just have the plugin installed via your .toml file or the UI or it's auto installed on your site, then you're good to go and no action necessary!

**Comment by lindsaylevine** [comment]
hello all! for those who haven't seen: today netlify announced our first step towards solving the problems ISR/ISG originally set out to solve.

https://www.netlify.com/blog/2021/04/14/faster-builds-for-large-sites-on-netlify-with-on-demand-builders-now-in-early-access/
https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/

what i can offer you today is a tagged release of our plugin:
`npm install --save @netlify/plugin-nextjs@experimental-odb`

this release uses on-demand builders to dramatically improve next/image performance by caching next/image requests.

it is my hope to ship this as the primary release after a week or two of testing. at that time, i will close this issue :).

please let me know if you have any feedback or questions!! <3

**Comment by MaximeHeckel** [comment]
🎉 🎉  The improvements the team is making on this are just amazing!

I was testing one of the other experimental-release for next/image support but the `@netlify/plugin-nextjs@experimental-odb` has significantly improved the loading speed of my images!! It's getting closer to the point where I could use this in prod 🙌 

Question:
1. Is there going to be some sort of support for .gifs ? (It's not a huge deal honestly but just wondering because now they are rendering as static images)
2. I still have sometimes the following error:

```
errorMessage: "Response payload size (12809084 bytes) exceeded maximum allowed payload size (6291556 bytes)."
errorType: "Function.ResponseSizeTooLarge"
```

However the underlying image is relatively "small" : 777kB. Any tips to handle these use cases? Could it be because the resolution of this image is fairly high?

**Comment by lindsaylevine** [comment]
@MaximeHeckel :D 

1. i can look into the gif support, i think i accidentally left it out by mistake
2. what width height and quality are you passing for this image? not sure :/

**Comment by MaximeHeckel** [comment]
@lindsaylevine 

1. Oh awesome! If by any chance gif support is not planned in the short term that's also totally fine 
2. The [original image](https://github.com/MaximeHeckel/blog.maximeheckel.com/blob/next/public/static/images/sunshine-settings-panel.png) is 1288 × 1254 and 373 KB. Regarding the props that I'm passing to the next image component: 

```
  src="/static/images/sunshine-settings-panel.png"
  layout="responsive"
  width={700}
  height={675}
   quality={50}
```

**Comment by AlexandraKlein** [comment]
> 🎉 🎉 The improvements the team is making on this are just amazing!
> 
> I was testing one of the other experimental-release for next/image support but the `@netlify/plugin-nextjs@experimental-odb` has significantly improved the loading speed of my images!! It's getting closer to the point where I could use this in prod 🙌
> 

Agreed! Quite an improvement! Thanks team!
