### ISSUE TITLE
Custom Netlify Redirects Overwritten

### ISSUE THREAD

**Issue by juanpprieto** [netlify/netlify-plugin-nextjs#158]
**Describe the bug**
netlify-plugin-nextjs seems to overwrite custom ` _redirects` file rules

**To Reproduce**
1. Add custom rules to: `public/_redirects`
2. netlify build
3. Check `out_publish/_redirects` includes only `# Next-on-Netlify Redirects`....

**Expected behavior**
I would expect to see the custom redirect rules merged in at the very top of the `out_publish/_redirects` file

**Versions**
- Next.js: `"next": "^10.0.3"`
- plugin (if installed at fixed version): `"@netlify/plugin-nextjs": "^3.0.0"`

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]:  `Mac`
 - netlify/cli version: `netlify-cli@3.10.5`

**If you're using file-based installation**
- netlify.toml:

```
# netlify.toml

[build]
  # base = "storefront/"
  command   = "yarn build"
  publish   = "storefront/out_publish"
  functions = "storefront/out_functions"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"

# needs to be included before
[[plugins]]
  package = "/plugins/my-custom-plugin"
   [plugins.inputs]
    build_dir_path = "storefront"
    build_dir = ".next"
    json_dir = "public/json"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

### Custom _redirects
```
#### PRODUCTS REDIRECTS START ####
/json/products/navy-feel-good-short-sleeve-shirt /json/products/navy-feel-good-short-sleeve-shirt___2021-03-16T22:24:05Z.json 200
.......
#### PRODUCTS REDIRECTS END ####
```

**Comment by lindsaylevine** [comment]
@juanpprieto hey! the plugin doesn't override - it reads your custom redirects from the _root_ of your project. if you put your `_redirects` file at the root of your project, instead of `public/_redirects`, it should work. lmk!

**Comment by juanpprieto** [comment]
@lindsaylevine amazing that worked! thanks

I had a feeling it was simply ignoring it (from being in the wrong path) rather than overwriting it.

Feel free to close and thanks once again for the quick response.

**Comment by lindsaylevine** [comment]
@juanpprieto haha yeah of course!!! happy to help!!

**Comment by zomars** [comment]
I'm glad I've found your comment @lindsaylevine ! I think it can be confusing for someone [following the docs](https://docs.netlify.com/routing/redirects/) like me:

> Save a plain text file called _redirects to the publish directory of your site. You can find _redirects file syntax details below.

Maybe we can add a note there that it may vary if you're using a framework like Next.js since we're not using the "publish directory" in here.
