### ISSUE TITLE
Adding Plugin from UI doesn't work but manual config does

### ISSUE THREAD

**Issue by benibienz** [netlify/netlify-plugin-nextjs#165]
**Describe the bug**
I moved my site over from `next-on-netlify` to this (because `next-on-netlify` broke). I deleted all the config and tried the "one click" install using the Netlify UI. This failed for multiple reasons. Adding back in in the `next.config.js` and manually adding the plugin using the `netlify.toml` file worked for me.

**To Reproduce**
1. Add the plugin from the Netlify UI
2. Add `next.config.js` with `target: "serverless",` (otherwise it doesn't work)
3. Deploy and get:
```
10:11:56 AM:   2. onBuild command from @netlify/plugin-nextjs                
10:11:56 AM: ────────────────────────────────────────────────────────────────
10:11:56 AM: ​
10:11:56 AM: ** Running Next on Netlify package **
10:11:56 AM: 🚀 Next on Netlify 🚀
10:11:56 AM: 🌍️ Copying public/ folder to /opt/build/repo
10:11:57 AM: ​
10:11:57 AM: ────────────────────────────────────────────────────────────────
10:11:57 AM:   Plugin "@netlify/plugin-nextjs" internal error                
10:11:57 AM: ────────────────────────────────────────────────────────────────
10:11:57 AM: ​
10:11:57 AM:   Error message
10:11:57 AM:   Error: No static assets found in .next dist (aka no /.next/static). Please check your project configuration. Your next.config.js must be one of `serverless` or `experimental-serverless-trace`. Your build command should include `next build`.
```

**Expected behavior**
It should "just work".

**Versions**
- Next.js: 10.0.9
- plugin (if installed at fixed version): latest

**Comment by lindsaylevine** [comment]
hey @benibienz! thanks for opening this issue, happy to help! i labeled it low priority because i just create a new site from scratch using create-next-app at next 10.0.9 linked to a git repo and i'm not able to reproduce your issue.

can you share your netlify.toml with us please? i'm guessing you're missing a build command?

**Comment by benibienz** [comment]
I'm fine with it being low priority because I have everything working anyway using the manual config. Just reporting.

[This page](https://www.netlify.com/blog/2020/12/07/announcing-one-click-install-next.js-build-plugin-on-netlify/) claims you don't need a `netlify.toml` at all, but it seems like you do? 

Or maybe this happened because I changed to this from a site previously using `next-on-netlify`. It's a little ambiguous [here](https://github.com/netlify/next-on-netlify/blob/main/MIGRATING.md) that you absolutely have to keep the `netlify.toml` file (it links to the UI-based setup which doesn't require the file).

**Comment by lindsaylevine** [comment]
@benibienz yes thats great feedback!! we can work to make it clearer once we figure out for sure what's up with your situation! when you're creating a new site from scratch in the UI (or even in the CLI), netlify outright asks you for a build command. without it, we don't know how to build your app. you can define that in your site's site settings in the UI or in netlify.toml. that's why the error message you see ends with "Your build command should include `next build`.". if you add your build command (likely `npm run build`) to your site settings along with the one-click installation, you should be good to go! i asked for your toml in my previous comment because i assumed you'd have kept it for the command :)

**Comment by sahilrajput03** [comment]
```bash
.....
 Your next.config.js must set the "target" property to one of: serverless, experimental-serverless-trace. Update the
11:15:42 PM:       target property to allow this plugin to run.

....

11:15:42 PM:   Error message
11:15:42 PM:   Deploy did not succeed: Deploy directory 'out' does not exist
...
```
I got above similar behaviour when i added the [next.config.js] file to my brand new repo created wtih [this way](https://app.netlify.com/start/deploy?repository=https://github.com/cassidoo/next-netlify-starter&utm_source=blog&utm_medium=nextstarter-cs&utm_campaign=devex) as demonstrated on [article - Announcing one-click install Next.js Build Plugin on Netlify](https://www.netlify.com/blog/2020/12/07/announcing-one-click-install-next.js-build-plugin-on-netlify/). Though I only wanted to enable cors on nextjs site but got this weird log, so i follwed what the error's path to solve that..!

But as suggested in the log that I need to add property `target: "serverless"` in my next.config.js file, it got fixed and my cors works too!

**Is there any downside to using this `target: "serverless"` property in my next.config.js file** as nextjs docs doesn't talk about this property at all anywhere!

Thanks!

**Comment by benibienz** [comment]
> @benibienz yes thats great feedback!! we can work to make it clearer once we figure out for sure what's up with your situation! when you're creating a new site from scratch in the UI (or even in the CLI), netlify outright asks you for a build command. without it, we don't know how to build your app. you can define that in your site's site settings in the UI or in netlify.toml. that's why the error message you see ends with "Your build command should include `next build`.". if you add your build command (likely `npm run build`) to your site settings along with the one-click installation, you should be good to go! i asked for your toml in my previous comment because i assumed you'd have kept it for the command :)

OK I understand. This stuff is super easy with Netlify usually, I just got confused when I changed my config and I couldn't remember how I set it up in the first place. I'll stick to always using the `netlify.toml` file from now on to avoid confusing my future self! Thanks for your help!

**Comment by lindsaylevine** [comment]
@sahilrajput03 check this out: https://nextjs.org/blog/next-8#serverless-nextjs. a serverless target is 100% necessary for nextjs to run on netlify.

@benibienz all good!!! we ofc tried to make the migration from next-on-netlify to the plugin for existing sites as simple as possible, but it's definitely not the most straightforward. always happy to help!!!
