### ISSUE TITLE
Netlify using outdated plugin-nextjs version 1.1.3

### ISSUE THREAD

**Issue by truescotian** [netlify/netlify-plugin-nextjs#166]
**Describe the bug**

**To Reproduce**
1. Plugin added from Netlify UI
2. Deploy to github
3. See outdated plugin on last line:
```
11:04:12 AM: ────────────────────────────────────────────────────────────────
11:04:12 AM:   Netlify Build                                                 
11:04:12 AM: ────────────────────────────────────────────────────────────────
11:04:12 AM: ​
11:04:12 AM: ❯ Version
11:04:12 AM:   @netlify/build 9.11.1
11:04:12 AM: ​
11:04:12 AM: ❯ Flags
11:04:12 AM:   apiHost: api.netlify.com
11:04:12 AM:   cacheDir: /opt/build/cache
11:04:12 AM:   deployId: 605600af45c127000749dda3
11:04:12 AM:   mode: buildbot
11:04:12 AM:   testOpts:
11:04:12 AM:     silentLingeringProcesses: ''
11:04:12 AM: ​
11:04:12 AM: ❯ Current directory
11:04:12 AM:   /opt/build/repo
11:04:12 AM: ​
11:04:12 AM: ❯ Config file
11:04:12 AM:   No config file was defined: using default values.
11:04:12 AM: ​
11:04:12 AM: ❯ Context
11:04:12 AM:   production
11:04:12 AM: ​
11:04:12 AM: ❯ Loading plugins
11:04:12 AM:    - @netlify/plugin-nextjs@1.1.3 from Netlify app
11:04:12 AM: ​
11:04:12 AM: ❯ Outdated plugins
11:04:12 AM:    - @netlify/plugin-nextjs@1.1.3: latest version is 3.0.3 which is incompatible with next@<10.0.6
```

**Expected behavior**
I expected that as per the README file, version 3 is used with Nextjs.

**Versions**
 - nextjs version: 10.0.1
- plugin (if installed at fixed version): Used Essentials Nextjs through Netlify UI

**If you're using the CLI to build**
 - OS: Ubuntu
 - netlify cli version: netlify-cli/3.13.4 linux-x64 node-v10.2.0

**If you're using file-based installation**
I am not as the readme says it is not needed.

**Comment by lindsaylevine** [comment]
@truescotian hey greg! fair feedback, i'll add something in the README about next version compatibility. unfortunately, next.js made a very public breaking change in a minor semver version (10.0.6), causing us to force next.js users using version < 10.0.6 onto the last working version of our plugin before we had to accommodate the 10.0.6 breaking change. see: https://github.com/netlify/plugins/blob/master/site/plugins.json#L431. if you want the latest plugin, upgrade your project to next.js >= 10.0.6. let me know if that makes sense!
