### ISSUE TITLE
Ability to access files from the build inside functions (primarily for ISR and Preview mode)

### ISSUE THREAD

**Issue by joelvarty** [netlify/netlify-plugin-nextjs#180]
As part of the build process we are storing lots of JSON data in the .next folder.  

We'd like to be able to access this folder again as part of the Preview or ISR flow when this same code runs as a function.

Also, is there a /tmp folder we can use as part of the function runtime here?

**Comment by lindsaylevine** [comment]
hey @joelvarty! thanks for opening this up. this is a known issue so i'm gonna send us over to that one (https://github.com/netlify/netlify-plugin-nextjs/issues/153) and close this one up :). see my last comment there: https://github.com/netlify/netlify-plugin-nextjs/issues/153#issuecomment-784861364. i'm happy to direct you towards our temp solution until a greater netlify-wide one is supported!
