### ISSUE TITLE
Default callbackWaitsForEmptyEventLoop to false?

### ISSUE THREAD

**Issue by FinnWoelm** [netlify/netlify-plugin-nextjs#190]
Hi y'all! Amazing plugin. Love how it now works completely out of the box with zero setup 🤩 :heart: 

I just ran into the `Task timed out after 10.01 seconds` issue:

```
{"errorMessage":"2021-04-03T07:42:16.336Z 3be439c6-d16e-42d2-859f-a66bffe9135e Task timed out after 10.01 seconds"}
```

I know this is caused because, by default, AWS lambda waits for empty event loop. And this needs to be explicitly turned off for some libraries (firebase, faunadb). See: https://github.com/netlify/next-on-netlify/issues/66#issuecomment-719988804

Is there any harm in turning off this waiting-for-empty-event-loop-behavior by default for the Netlify Functions created by this plugin?

It would solve issues like this: https://stackoverflow.com/questions/65243013/next-on-netlify-function-times-out-10s-when-deployed-renders-in-0-3s-locally

The fact that it works out of the box with Vercel makes me think that there might be no harm in turning this off as the default. Perhaps one of you actually knows what the implications would be?

The implementation would be a very simple one-liner in https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/templates/netlifyFunction.js:

```js
context.callbackWaitsForEmptyEventLoop = false;
```

Look forward to hearing your thoughts! :)

**Comment by lindsaylevine** [comment]
@FinnWoelm oh hey finn

**Comment by lindsaylevine** [comment]
after some internal discussion, seems like we may add an option to turn `callbackWaitsForEmptyEventLoop` "off" (aka set it to false) as a plugin input.

**Comment by FinnWoelm** [comment]
Ok, that's a pretty good solution. I'm still trying to better understand what this thing actually means...

I just saw that there's an async version of the function handler, that doesn't use callback at all: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html#nodejs-prog-model-handler-callback (see Async handlers).

I wonder if this whole question would be solved by just switching to async handler. AWS docs say this:
> For non-async handlers, function execution continues until the event loop is empty or the function times out. The response isn't sent to the invoker until all event loop tasks are finished. If the function times out, an error is returned instead. You can configure the runtime to send the response immediately by setting context.callbackWaitsForEmptyEventLoop to false. 
(source: same link as above)

If I get a chance, I'll do some experimentation...

**Comment by FinnWoelm** [comment]
Netlify also advertises the non-callback async handler:

![image](https://user-images.githubusercontent.com/7606194/114073834-058b3600-98a4-11eb-94a2-76bac319bea9.png)

https://www.netlify.com/products/functions/

**Comment by speakk** [comment]
What's a relatively easy way to test this before it gets implemented? This is a pretty huge blocker for us at the moment.

**Comment by lindsaylevine** [comment]
@speakk whoa! wild to see you comment this because it's next up on my to-do list. i will get to it this week, but for now, you could use patch-package like described in this comment: https://github.com/netlify/netlify-plugin-nextjs/issues/191#issuecomment-813690286

hang tight!

**Comment by speakk** [comment]
Awesome, thank you muchly! :)

**Comment by lindsaylevine** [comment]
@speakk do you have a repo to test a fix/branch against?
