### ISSUE TITLE
Error: Cannot find module on ISR when using dynamic imports

### ISSUE THREAD

**Issue by zomars** [netlify/netlify-plugin-nextjs#209]
**Describe the bug**

Using Incremental Static Regeneration seems to be breaking when using dynamic imported components.

**To Reproduce**
1. Make a page that uses `getStaticProps` and `getStaticPaths`
2. Add a dynamic component using `next/dynamic`
3. Enable `revalidate: 1` in `getStaticProps`

**Expected behavior**

It is expected to show the pre-rendered paged, instead I get this error:

<details>
<summary>Here's the error output:</summary>

```
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: Cannot find module '../../chunks/886.4ea9d7ad9b7228e07a29.js'\nRequire stack:\n- /var/task/src/netlify/functions/next_pages_slug/nextPage/index.js\n- /var/task/src/netlify/functions/next_pages_slug/renderNextPage.js\n- /var/task/src/netlify/functions/next_pages_slug/next_pages_slug.js\n- /var/task/next_pages_slug.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: Cannot find module '../../chunks/886.4ea9d7ad9b7228e07a29.js'",
    "Require stack:",
    "- /var/task/src/netlify/functions/next_pages_slug/nextPage/index.js",
    "- /var/task/src/netlify/functions/next_pages_slug/renderNextPage.js",
    "- /var/task/src/netlify/functions/next_pages_slug/next_pages_slug.js",
    "- /var/task/next_pages_slug.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}
```

</details>

**Versions**
- Next.js: latest
- plugin (if installed at fixed version): @netlify/plugin-nextjs

**Comment by lindsaylevine** [comment]
@zomars hey! can i see your package.json and netlify.toml if you have one? links to your site's build/deploy logs would also be great!

**Comment by zomars** [comment]
Sure @lindsaylevine !

Here's a deployed url of the previous commit:

https://607095a7c76a4b00085000e7--jobsite-contentful.netlify.app/pages/internal/new-industry-page

And here's the one with revalidate enabled:

https://jobsite-contentful.netlify.app/pages/internal/new-industry-page

Here's my `netlify.toml`:

```
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = "out"
```

And my relevant dependencies in `package.json`:

```
"next": "latest",
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

**Comment by lindsaylevine** [comment]
@zomars ahh apologies! for build/deploy logs i meant a url that looks like: https://app.netlify.com/sites/{yoursitename}/deploys/60627d070f34e32724df2f89

i'm pretty sure i know what's going on already though :( related to next's recent webpack change. this was the previous bug https://github.com/netlify/next-on-netlify/issues/121 - notice it's looking _one_ directory up whereas your error is looking _two_ directories up 🤦 . we'll figure it out though!

**Comment by zomars** [comment]
@lindsaylevine my bad! I've updated the above urls. Thank you for your time! 🙏

**Comment by zomars** [comment]
@lindsaylevine Is there a known work around I could use? Maybe downgrading webpack? Or disabling ISR altogether in the mean time?

**Comment by lindsaylevine** [comment]
@zomars i think you could downgrade next to the last major release?

**Comment by zomars** [comment]
@lindsaylevine that would be from 10 to 9?

**Comment by lindsaylevine** [comment]
ahh my bad i should have been more specific! @zomars "major" release wasn't a good answer; in my head i meant "working" release 😅 . the breaking webpack change in next.js went out in https://github.com/vercel/next.js/releases/tag/v10.0.9 so <= 10.0.8 _should_ work for you?

**Comment by Nexum** [comment]
I encountered the same problem with the new odb build :(
maybe this helps, i was on the verge of creating my own issue for this but i rather add to this one 👍 

https://github.com/Nexum/netlify-plugin-nextjs-odb-dynamic-bug

**Comment by zomars** [comment]
Awesome @lindsaylevine ! It this available now to deploy?

**Comment by lindsaylevine** [comment]
@zomars good question! in theory we shouldnt close the issue until its actually deployed/released (vs when it gets merged). this will go out in our next release. i can make sure it goes out by EOD tomorrow :)

**Comment by zomars** [comment]
Thanks you for the response!

**Comment by lindsaylevine** [comment]
@zomars this should be out now in 3.3.0!
