### ISSUE TITLE
Prebuild error when using pnpm

### ISSUE THREAD

**Issue by CryogenicPlanet** [netlify/netlify-plugin-nextjs#219]
**Describe the bug**
I am using `pnpm` on a nextjs repository and followed the steps here https://answers.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759 and https://github.com/netlify/build/issues/1633#issuecomment-712863250 this was working fine with `next-on-netlify`

However now with this plugin, I run into an error that says `next` is not installed on the prebuild by the plugin, which runs before my custom prebuild which installs the packages.

Also, this might be better categorized as a feature request, not entirely sure which it falls under exactly

![image](https://user-images.githubusercontent.com/10355479/114473651-48d20580-9c12-11eb-9b17-3af46ca69ea0.png)

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a `next` project with `pnpm` and the below `netlify.toml`
2. Push to netlify and build without cache. (I think it worked the first few times for me because it has next cached from `yarn` before, we just migrated over)
3. Should see the error in the console

This repo can be used to reproduce the bug https://github.com/CryogenicPlanet/netlify-next-prebuild-bug

**Expected behaviour**
A workaround or suggestion to use `pnpm` with this new plugin would be great or a way to disable the plugins prebuild

**Versions**
- Next.js: latest
- plugin (if installed at fixed version): 3.1.0

**If you're using file-based installation** 
```
// netlify.toml
[build]
  command   = "npm run build"
  publish   = "out"
[build.environment]
  NPM_FLAGS="--prefix=/dev/null"  
[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by mhatvan** [comment]
Encountering the same issue. Please prioritize this higher as it is a major blocker when using pnpm with next.

**Comment by ascorbic** [comment]
With the new plugin version you can use the workaround, though with one change: instead of `--prefix=/dev/null`, pass `--version` as the flag. Of course native pnpm support would be best, but this is the best solution for now
