### ISSUE TITLE
Multiple cookie headers not serialized correctly on HTTP/2

### ISSUE THREAD

**Issue by frigus02** [netlify/netlify-plugin-nextjs#255]
**Describe the bug**

It looks like cookies are not correctly serialized when the browser sends multiple cookie headers over HTTP/2.

Over HTTP/2 multiple cookies shows up comma separated (e.g. `first=1,second=2`) in `req.headers.cookie` in server-side code. This means cookie libraries such as [cookie](https://www.npmjs.com/package/cookie) are unable to parse them correctly.

The behaviour seems to have changed recently. Our site worked fine a few days ago. Although we can't pinpoint it exactly. We reproduced this with older versions as well (netlify v6.1.6, netlify-cli v3.4.7, next-on-netlify v2.8.7). Could something have changed in Netlify recently?

**To Reproduce**

We made a minimal example project: https://github.com/frigus02/test-netlify-plugin-nextjs-cookies

Steps to reproduce are in the readme. It shows different behaviour when run locally and deployed on Netlify.

It's currently deployed under: https://test-netlify-plugin-nextjs-cookies.netlify.app

**Expected behavior**

`req.headers.cookie` should be `first=1; second=2` even when the browser sends multiple cookie headers with HTTP/2.

**Investigation**

We investigated further and saw in Wireshark, that browsers send multiple cookie headers when using HTTP/2:

```
cookie: first=1
cookie: second=2
```

but only 1 header with using HTTP/1.1:

```
cookie: first=1; second=2
```

This distinction is _not_ visible in browser devtools, sadly. But it seems to be according to the spec.

We think the code that serializes with a comma instead of semicolon is this line:

https://github.com/netlify/netlify-plugin-nextjs/blob/46526f955240dfcd1f65c4ecfa0c563ce2b1362d/src/lib/templates/createRequestObject.js#L64

**Versions**

- Next.js: 10.2.0
- plugin: 3.2.0

**If you're using the CLI to build**

 - OS: macOS
 - netlify/cli version: 3.24.3

**If you're using file-based installation**

- netlify.toml: https://github.com/frigus02/test-netlify-plugin-nextjs-cookies/blob/91b3311848ae46b4933eef603fa33d6aaca6c81d/netlify.toml

**Comment by lindsaylevine** [comment]
@frigus02 hey! https://answers.netlify.com/t/bug-netlify-functions-event-headers-cookie-sometimes-suddenly-used-comma-instead-of-semicolon/36793/12 does this look like your same issue? are you still seeing it or has it resolved for you as well?

**Comment by frigus02** [comment]
Hi @lindsaylevine. This does sound exactly like the issue we were seeing, yes. Thanks for the quick response.

The test site under https://test-netlify-plugin-nextjs-cookies.netlify.app/ doesn't have the issue anymore. I will test our real site tomorrow and report back. But I assume it's fixed and we can close this issue.

**Comment by lindsaylevine** [comment]
@frigus02 of course! shoutout to @mraerino who did the navigating of this issue. i'll close for now but if for some reason your real site doesn't work we can always reopen!
