### ISSUE TITLE
TypeError: isDynamicRoute is not a function

### ISSUE THREAD

**Issue by AustinShelby** [netlify/netlify-plugin-nextjs#265]
**Describe the bug**
When trying to build my next.js site on Netlify, I will get the following error:

```
10:25:24 PM: ────────────────────────────────────────────────────────────────
10:25:24 PM:   Plugin "@netlify/plugin-nextjs" internal error                
10:25:24 PM: ────────────────────────────────────────────────────────────────
10:25:24 PM: ​
10:25:24 PM:   Error message
10:25:24 PM:   TypeError: isDynamicRoute is not a function
10:25:24 PM: ​
10:25:24 PM:   Plugin details
10:25:24 PM:   Package:        @netlify/plugin-nextjs
10:25:24 PM:   Version:        3.2.1
10:25:24 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
10:25:24 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
10:25:24 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
10:25:24 PM: ​
10:25:24 PM:   Error location
10:25:24 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
10:25:24 PM:       at /opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/pages/withoutProps/redirects.js:30:10
10:25:24 PM:       at async asyncForEach (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/helpers/asyncForEach.js:3:5)
10:25:24 PM:       at async getRedirects (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/pages/withoutProps/redirects.js:24:3)
10:25:24 PM:       at async setupRedirects (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/steps/setupRedirects.js:41:9)
10:25:24 PM:       at async build (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:31:3)
10:25:24 PM:       at async nextOnNetlify (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:75:5)
10:25:24 PM:       at async onBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:67:5)
10:25:24 PM:       at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3)
10:25:24 PM:       at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
10:25:24 PM:       at async process.<anonymous> (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
```

Four days ago it built correctly but then it was using `@netlify/plugin-nextjs@3.0.3` so maybe it's related to the plugin version.

**Expected behavior**
The site should build correctly.

**Versions**
- Next.js: `10.0.9`

**Comment by ionpetro** [comment]
Same error here

**Comment by jason-dark** [comment]
+1 same here, my site was building fine only a couple of hours ago. I only made minor changes to CSS and now get this build error. My build works fine locally.

**Comment by wltgreenwood** [comment]
+1 same error for me. Was working when I last built it around 12 hours ago. Latest changes was for some minor text.

**Comment by justincavery** [comment]
Same issue. Last successful build at 19:48 GMT, last one failed at 22:05 (now)

**Comment by AndreasNilsson123** [comment]
+1 same here

**Comment by kidmortal** [comment]
+1 and i didnt even change any code tbh

**Comment by mannycolon** [comment]
Same here

**Comment by TomaszSwiatek** [comment]
Same for me

**Comment by einSelbst** [comment]
I'm also experiencing this. 
I have this plugin installed via `package.json` in version 3.2.0 so I wonder why the netlify ci is using 3.2.1.
I thought adding a plugin to `package.json` was the way to control the version.

Is there any advice about how to roll back a netlify plugin?

**Comment by lindsaylevine** [comment]
oh my GOODNESS. FRIENDS. i was on a call. hi i'm releasing this fix now. fyi for future: advice on rolling back is to lock it to the last working version (you can check our releases).

**Comment by lindsaylevine** [comment]
OKAY 3.2.2 should be out now. please let me know if you continue to have issues! apologies for the delay and thanks so much for your patience ❤️ . i'll also add a note in the README about how to manually "roll back" in the event of the plugin breaking.

**Comment by lindsaylevine** [comment]
https://github.com/netlify/netlify-plugin-nextjs#faq !

**Comment by einSelbst** [comment]
> https://github.com/netlify/netlify-plugin-nextjs#faq !

Thanks @lindsaylevine . Actually I think my version was not pinned because I had it as a dev dependency. I moved it to non-dev with a `^3.2.0` and this indeed forced the version on netlify. Just mention this because I see in the faq that it also installs it as a dev dep. 
Anyway, thanks for the quick help!

**Comment by lindsaylevine** [comment]
you're right thank you @einSelbst ! i think -D only works for CLI 😅 appreciate the tip!!!
