### ISSUE TITLE
Allow users to select the netlify-plugin-nextjs the want to use so that breaking changes made to the latest version don't mess up my work

### ISSUE THREAD

**Issue by mannycolon** [netlify/netlify-plugin-nextjs#268]
**Is your feature request related to a problem? Please describe.**

Today v3.2.2 cause all new deploys to fail (see here: https://github.com/netlify/netlify-plugin-nextjs/pull/267) because deploys use the latest version, if we could choose what version to use this could mitigate these kinds of problems.

**Describe the solution you'd like**
Allow users to choose what version to use.

**Comment by lindsaylevine** [comment]
https://github.com/netlify/netlify-plugin-nextjs#faq this is answered here now!

**Comment by lindsaylevine** [comment]
in case that link ever changes:

>A: Check out the plugin's releases. You can manually install npm install -D @netlify/plugin-nextjs@3.x.x at the last working version. Once a new working release is out, you can uninstall the plugin at this locked version (npm uninstall -D @netlify/plugin-nextjs), which will re-enable Netlify's build system to use the latest plugin version by default.
