### ISSUE TITLE
Update docs for existing Next.js websites on Netlify to include basic build settings

### ISSUE THREAD

**Issue by DaveBitter** [netlify/netlify-plugin-nextjs#271]
**Is your feature request related to a problem? Please describe.**
I had an existing site on Netlify that didn't use this awesome plugin yet where I just used Next.js static site generation (SSG). For that, you usually configure two deploy settings in Netlify:
- Build command: `npm run build && npm run export`
- Publish directory: `out`

What I didn't realize is that I needed to change the build command to just `npm run build` and leave the publish directory blank. It might be an obvious thing for people, but I couldn't find this documented anywhere.

**Describe the solution you'd like**
I think it would be great to document these two deploy settings in the README under `Installation and Configuration -> UI-based installation for existing Next.js sites`. I'm more than happy to pick this up.

**Describe alternatives you've considered**
An alternative is to close this issue and have it as a reference. I tried searching the issues for this and couldn't find it.

**Additional context**
n/A

Thanks for this awesome plugin!

**Comment by lindsaylevine** [comment]
@DaveBitter would love for you to open a PR with what you'd like to see!!!

**Comment by Nicoowr** [comment]
That'd be great!
On a side note, what you suggested did not work for me, I had to use a custom `netlify.toml` file, with this config to make it work:
`[build]
command = "next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"`

I also had to specify `target: "serverless"` in `next.config.js`

**Comment by lindsaylevine** [comment]
@Nicoowr 

```
[build]
command = "npm run build"
publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"
```

works for thousands of sites!

if you wanna send over a repo demonstrating that it doesnt work for you, id be happy to dig into it!

**Comment by lindsaylevine** [comment]
@DaveBitter hey dave are you wanting to open a PR for this? otherwise i can take care of it!

**Comment by Nicoowr** [comment]
@lindsaylevine yes it seems that the problem comes from our own website settings. I'll dig into it :) 
Anyway, the mentioned config in the docs works for new apps from scratch!

**Comment by DaveBitter** [comment]
I'm so sorry for responding this late! I see that you already merged a change to the docs. Perfect 👌
