### ISSUE TITLE
API route as Netlify function 502s

### ISSUE THREAD

**Issue by omarryhan** [netlify/netlify-plugin-nextjs#296]
**Describe the bug**
Plugin internal error when deploying a serverless Next.js app on Netlify. 
The error is: Error: No static assets found in .next dist (aka no /.next/static).

Full error message:

```bash
Plugin "@netlify/plugin-nextjs" internal error

Error: No static assets found in .next dist (aka no /.next/static). Please check your project configuration. Your next.config.js must be one of serverless or experimental-serverless-trace. Your build command should include next build.

In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
at copyNextAssets (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/steps/copyNextAssets.js:14:11)
at async build (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:25:3)
at async nextOnNetlify (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/index.js:75:5)
at async onBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:67:5)
at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3)
at async handleEvent (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
at async process. (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
```

**To Reproduce**
I first did nothing but install the plugin from Netlify's UI.
Then it showed me an info message in the deployment logs that I should set the `target` property in next.config.js to be either `serverless` or `experimental-serverless-trace`. I set it to `serverless`.
It then showed me the error posted above.

Link to the app: https://github.com/omarryhan/trendzz/ 
Link to the failed deployment: https://app.netlify.com/sites/trendzz/deploys/609b8568b7933100072efaad 

**Expected behavior**
Deploy without an error.

**Versions**
- Next.js: ^10.2.0

**Comment by vitorcamachoo** [comment]
Please check this solution: https://github.com/netlify/netlify-plugin-nextjs/issues/115#issuecomment-806029105

**Comment by omarryhan** [comment]
Sorry, not sure what this has to do with `nx`.
Also, his build dir is set to `"dist/apps/basic"`. Mine is the default, so it should work without manually changing the build dir.

**Comment by lindsaylevine** [comment]
@omarryhan do you have a build command set in the UI? i see the github repo you linked doesnt have a netlify.toml aka the other place where it could be set, like so:

```toml
[build]
  command = "npm run build"
```

**Comment by vitorcamachoo** [comment]
> @omarryhan do you have a build command set in the UI? i see the github repo you linked doesnt have a netlify.toml aka the other place where it could be set, like so:
> 
> ```toml
> [build]
>   command = "npm run build"
> ```
> 

Under a NX workspace, how I should define build command?

**Comment by lindsaylevine** [comment]
@vitorcamachoo under the article you linked on your own issue (we should prob move this conversation there): 
(https://www.netlify.com/blog/2020/04/21/deploying-nx-monorepos-to-netlify/)
<img width="833" alt="Screen Shot 2021-05-12 at 7 15 06 PM" src="https://user-images.githubusercontent.com/57350178/118055641-77004d80-b356-11eb-801c-c2ea6bd78e89.png">

**Comment by omarryhan** [comment]
> Do you have a build command set in the UI? 

No @lindsaylevine. The only thing I have set in the UI is that I added the plugin.

![Screenshot_20210513-061730__01.jpg](https://user-images.githubusercontent.com/27153525/118076769-210dc300-b3b3-11eb-8f02-6ea1ac754092.jpg)

> i see the github repo you linked doesnt have a netlify.toml

There used to be one, but I removed it.

I thought `npm run build` is be ran by default. I'll try adding it now.

**Comment by omarryhan** [comment]
I added it. Now the static files are deployed correctly but the functions aren't.

Link to the most recent deployment: https://app.netlify.com/sites/trendzz/deploys/609ca9a36003565c0101970a

Link to the website: trendzz.netlify.app

**Comment by lindsaylevine** [comment]
@omarryhan ah that should fix it for you! i'd love feedback for our docs/README about how to make it clearer that every netlify site needs a build command specified somewhere!

**Comment by lindsaylevine** [comment]
oh oops i didn't see your second comment one sec

**Comment by lindsaylevine** [comment]
i'm confused what exactly is the problem with your functions?

**Comment by omarryhan** [comment]
This is from my dev console:

![image](https://user-images.githubusercontent.com/27153525/118079740-fd4d7b80-b3b8-11eb-9810-9cd1d517b72c.png)
![image](https://user-images.githubusercontent.com/27153525/118079778-0e968800-b3b9-11eb-8729-47aa6a327fd2.png)

I'm confused too. Not sure what's causing the Bad Gateway error. Maybe because the Netlify's Edge servers aren't actually running the function?

The same function runs fine on Vercel (https://trendzz.vercel.app/api/repositories?language=)

**Comment by omarryhan** [comment]
> @omarryhan ah that should fix it for you! i'd love feedback for our docs/README about how to make it clearer that every netlify site needs a build command specified somewhere!

@lindsaylevine I think it'd be better if users didn't need to to manually add the build command in either the UI or netlify.toml. However, I'll be happy to make a PR highlighting this caveat :)

**Comment by lindsaylevine** [comment]
do you see the function in your site's functions tab? if so what do the logs say? :)

**Comment by lindsaylevine** [comment]
quickest way for me to diagnose is to set up a repo that reproduces it tho!

**Comment by omarryhan** [comment]
Yes, it's there. It also picked up my request when I tried to trigger a function call from the website.

Here are the logs:

```
7:55:21 AM: ca9141fc INFO   [request] /api/repositories
7:55:22 AM: ca9141fc Duration: 1063.07 ms	
```

And this is the endpoint: https://trendzz.netlify.app/.netlify/functions/next_api_repositories

**Comment by omarryhan** [comment]
![Screenshot_20210513-080042__01.jpg](https://user-images.githubusercontent.com/27153525/118084646-5c16f300-b3c1-11eb-99f4-cd146de7465b.jpg)

**Comment by lindsaylevine** [comment]
can you get me a repo that reproduces this? i have no idea why this'd work on vercel but effectively time out on netlify 🤔

**Comment by omarryhan** [comment]
The repo is open source: https://github.com/omarryhan/trendzz

Or would you like me to recreate the issue in a new repo?

**Comment by lindsaylevine** [comment]
omg it was in the original post hahaha sorry i need to sleep lmao. will look asap!!!

**Comment by omarryhan** [comment]
> I have no idea why this'd work on vercel but effectively time out on netlify

I speculate that the problem has to do with how the functions are being deployed by Netlify. Netlify is probably expecting the functions to be in the `functions` dir instead of the `app/api` dir.

Should I try and see if changing that fixes it?

**Comment by omarryhan** [comment]
No problem 😄. Tyt

**Comment by lindsaylevine** [comment]
@omarryhan if you take out the `res.end()` in api/repositories does it work for you? 🤔

**Comment by lindsaylevine** [comment]
i can confirm now this definitely works for me. why? i'm not quite sure at the moment 😄 but definitely something to do with our compat layer and _possibly_ related to https://github.com/netlify/netlify-plugin-nextjs/issues/190

**Comment by omarryhan** [comment]
It worked!
I was thinking there's no way I could've figured this bug out. Then I looked at your commit history in your fork 😄. You almost stripped the whole repo out.
Kudos to you.

Thanks a lot for the help.

**Comment by lindsaylevine** [comment]
@omarryhan hahah i was sure it was something unique to your config but nope! hope you enjoyed my commit names :D. such a random thing. if/when i figure out the res.end weirdness ill try to remember to report back here. thanks for your patience and help!!
