### ISSUE TITLE
Response payload exceeded for some images in next/image

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/netlify-plugin-nextjs#308]
cc @maximeheckel

<img width="793" alt="Screen Shot 2021-05-14 at 5 49 01 AM" src="https://user-images.githubusercontent.com/57350178/118282165-fcd9e100-b49b-11eb-8b10-15d2787f071b.png">

if anyone sees and is experiencing this issue as well, please do let us know so we can prioritize accordingly!

**Comment by ascorbic** [comment]
I'm not sure there's anything we can do about this, other than handle the error more gracefully. There is a 6MB hard limit of response payloads from Lambdas, so if it is generating iamges larger than this then it will throw an error. I suggest that we resolve this by returning a better error message if the image is too large.

**Comment by lindsaylevine** [comment]
assuming this isn't an issue on vercel, does this mean we shouldn't be using Lambdas for image stuff? would it be possible to do the same strategy as svg/gif (catch this error and return the Location header)?

**Comment by ascorbic** [comment]
I think it's reasonable to just error out. I can't think of a reason to ever have a 6MB image in an img tag

**Comment by lindsaylevine** [comment]
cool, you wanna add this to your open PR or save for another time? 😃

**Comment by ascorbic** [comment]
I'll do it in another one
