### ISSUE TITLE
Remove/replace uses of fs-extra

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/netlify-plugin-nextjs#320]
per: https://github.com/netlify/netlify-plugin-nextjs/pull/280#issuecomment-839653032

**Comment by ascorbic** [comment]
I don't think we should remove it. There are lots of useful functions in there. We should just stick to a compatible version until we drop Node 10 support (which we should do when Next does)

**Comment by lindsaylevine** [comment]
that's fine w me! let's close this then and leave the renovate PR open til node 10 support is dropped?

**Comment by erezrokah** [comment]
@lindsaylevine you can close the PR to tell renovate to ignore that specific update.
When you're ready to merge it you can re-request it via https://github.com/netlify/netlify-plugin-nextjs/issues/121.

Keeping it open also works
