### ISSUE TITLE
Revalidate doesn't work always with Netlify Functions

### ISSUE THREAD

**Issue by saidattax** [netlify/netlify-plugin-nextjs#321]
**Describe the bug**
I have a page which has an option `revalidate: 5,`. It works fine with `netlify dev`. However, when I deploy it and run on netlify, the serverless functions are not being triggered on refresh after 5 seconds.

I made a small test using codesanbox server and a next js site which shows the current time. The time is calculated on the server and sent to the next js app which is handled using `getStaticProps`. There's also a couple of routes sent via the server to `getStaticPaths`

**To Reproduce**
1. Go to [Codesandbox Server](https://codesandbox.io/s/keen-mahavira-3uvfc?file=/index.js) (required)
1. Go to https://goofy-galileo-ba9249.netlify.app/
2. Refresh
3. If it works, refresh again
4. Time does not update after 5 seconds between refreshes

Link to Github Repo: https://github.com/saidattax/next-js-test

**Expected behavior**
Everytime on refresh, atleast after 5 seconds, the serverless function should trigger to get the latest `getStaticProps`

**Versions**
- Next.js: 10.2.0
- plugin (if installed at fixed version): 3.3.0

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]
 - netlify/cli version:

**If you're using file-based installation**
- netlify.toml:

```
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[context.production.environment]
  NEXT_SERVERLESS = "true"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
 ```

**Comment by lindsaylevine** [comment]
@saidattax hey! thank you so much for opening such a wonderful and detailed issue. we really appreciate the time and thoughtfulness you spent. unfortunately this has been a request/known issue on the platform for nearly a year 😲 (see https://github.com/netlify/netlify-plugin-nextjs/issues/151). this is netlify's most recent work to address this issue: https://github.com/netlify/netlify-plugin-nextjs/issues/151#issuecomment-819806060. for this reason, i'll close your issue, but feel free to direct any additional comments/feedback to #151!! ❤️

**Comment by saidattax** [comment]
Hey @lindsaylevine ! Thanks for getting back. However, I have another project where I use the same `revalidate` and the netlify function is indeed called on every request within 5 seconds.

It can also be seen in it's function logs, that it works. `next_pname`

Here's the deploy id `609e5727d93f45bc37e4e932` for that project.

Any idea how it's working there but not in this one? Did I do something there that I missed here?

Thanks

**Comment by saidattax** [comment]
@lindsaylevine 

Also, a different issue I found, 

In my [package.json](https://github.com/saidattax/next-js-test/blob/main/package.json) I have fixed the version of the plugin 

```
    "devDependencies": {
        "@netlify/plugin-nextjs": "3.2.2"
    }
```    

But in the build, it is taking the latest version? 🤔

```
4:28:33 PM: ❯ Installing plugins
4:28:33 PM:    - @netlify/plugin-nextjs@3.3.0
4:28:54 PM: ​
4:28:54 PM: ❯ Loading plugins
4:28:54 PM:    - @netlify/plugin-nextjs@3.3.0 from netlify.toml
```

Here's the deploy id `60a39dbfcd1460de0e4c6613`

This is supposed to say `@netlify/plugin-nextjs@3.2.2` , right?

**Comment by lindsaylevine** [comment]
@saidattax 

1. i think what your describing is just SSR, aka what we do in place of ISR. if a next project has `revalidate` set, we simply SSR that page instead of the prerendered html.


2. you'd need to install it as a prod dependency, not a dev dep! i just checked our README and realized we have `-D` in there so lemme go replace that rn! (see https://github.com/netlify/netlify-plugin-nextjs#faq though fyi!)

**Comment by lindsaylevine** [comment]
ok, i see now. your site in the original issue body is *not* updating. this is because, i believe, you're using fallback: true, which means (as of the most recent plugin version) we cache the first function response. if you take that out, it should work as you expect.

**Comment by saidattax** [comment]
Thank you so much for the help @lindsaylevine ! That fixes it :)

**Comment by lindsaylevine** [comment]
yay!! happy to help ❤️ :D
