### ISSUE TITLE
Can't access locale files in public directory from nested routes using getServerSideProps

### ISSUE THREAD

**Issue by hrahimi270** [netlify/netlify-plugin-nextjs#359]
**Describe the bug**
I'm using the built-in feature of internationalization of Nextjs. I don't want to use other third-party modules for translations of my app.
So I decided to put my translations in `/public/locales` and access them using `getServerSideProps` for dynamic pages and `getStaticProps` for static pages.
Static pages work fine. But dynamic pages not working and they are not able to access the file using `getServerSideProps`.
This is the error I have on netlify:

<img width="1364" alt="Screen Shot 2021-05-30 at 12 11 25 PM" src="https://user-images.githubusercontent.com/38007163/120096354-3703dd80-c140-11eb-86f0-f6a1a12354f3.png">

Also, I'm trying to get my translations simply by this lines of codes in both pages:
```js
const dir = path.resolve('./public/locales')
const filePath = `${dir}/${locale}.json`;
const buffer = fs.readFileSync(filePath);
const translations = JSON.parse(buffer.toString());
```

**Expected behavior**
Have my translations in both Static and Dynamic pages.

**Versions**
- Next.js: 10.2.0
- @netlify/plugin-nextjs: 3.3.0

**Comment by lindsaylevine** [comment]
hey @hrahimi270 ! good news, we just recently released support for this :). check out this section of the README: https://github.com/netlify/netlify-plugin-nextjs#local-files-in-runtime. throwing "public" in included_files should solve your problem! if that works for you, we could possibly update this issue to a feature request asking for public to be included by default? let me know!

**Comment by hrahimi270** [comment]
Hey @lindsaylevine. Thanks for the response.
Actually, I did this before when I have this problem in all of the pages (both static and dynamic). But the problem still remains in dynamic pages.
As you can see in the picture, the app tries to load the locale files from `/var/task/public/locales/fa.json`.
But once I logged the path that loads the locale files from static pages, and it was something else.
I think in dynamic pages, `path.resolve()` have a different behaviour :D not sure about that.

**Comment by lindsaylevine** [comment]
@hrahimi270 hmm, can you try path.resolve(`process.cwd(), './public/locales')? or maybe not using path.resolve? i can't remember at the moment what the correct usage. [this](https://github.com/isaachinman/next-i18next/blob/7474c937a0ea049670786df6f784c6f713b12bfc/src/serverSideTranslations.ts#L88) uses process.cwd() and i know we had a next-i18next issue that worked with included_files as public/*. if that doesn't work, if you wanted to give me a repo to try to figure out, i could maybe better help that way!

**Comment by hrahimi270** [comment]
Then I will test `path.resolve(process.cwd(), '/public/locales')` just like the link that you mentioned.
If it didn't work, I will create a reproduce repo to check it closely (: 
Thanks.

**Comment by hrahimi270** [comment]
Hey @lindsaylevine.
I did test `path.resolve(process.cwd(), '/public/locales')` but was not successful. So, I created a reproduce repo that you can have a look closely.
https://github.com/hrahimi270/next-netlify-reproduce

Also, deployed it on Netlify to see the error when clicking on brands.
https://quirky-williams-edd128.netlify.app/

Thanks for your time.

**Comment by eduardoboucas** [comment]
Hi @hrahimi270! Thanks for the detailed report and the reproduction repo — these were super helpful.

Can you try to add to your build an environment variable named `NETLIFY_EXPERIMENTAL_FUNCTION_HANDLER_V2` with the value `true`? You can do this in the UI as shown in the screenshot below.

![Screenshot 2021-06-02 at 19 08 14](https://user-images.githubusercontent.com/4162329/120530999-06d56c80-c3d6-11eb-8518-5a003c825376.png)

This will enable a functionality that we're planning to roll out next week, and from my tests it should fix your issue. Let me know how you get on.

Thanks!

**Comment by hrahimi270** [comment]
Hi @eduardoboucas. Yes, it works fine now with that variable 🤘🏼
So, for now, I just need to use this variable until this functionality gets available by default?
And thanks for your time.

**Comment by eduardoboucas** [comment]
> Hi @eduardoboucas. Yes, it works fine now with that variable 🤘🏼
> So, for now, I just need to use this variable until this functionality gets available by default?
> And thanks for your time.

I'm glad it works! 🎉

And yes, please use that variable until this change is rolled out. I'll update this issue once that happens.

Thanks!

**Comment by eduardoboucas** [comment]
> Hi @eduardoboucas. Yes, it works fine now with that variable 🤘🏼
> So, for now, I just need to use this variable until this functionality gets available by default?
> And thanks for your time.

This has now been rolled out.

@hrahimi270 can you please check if it works without the environment variable? Thanks!

**Comment by hrahimi270** [comment]
@eduardoboucas 
Yes, it works without the variable.
Great job.
Thanks.
