### ISSUE TITLE
"out" directory does not exist

### ISSUE THREAD

**Issue by gragland** [netlify/netlify-plugin-nextjs#373]
**Describe the bug**
When attempting to deploy manually with `netlify deploy` I get the error:
```
Error: No such directory /Users/gaberagland/projects/next-netlify/out! Did you forget to run a build?
```

It appears this is because `next build` stores all build files in the `.next` directory, not `out`. The `out` directory is only generated when running `next export`, but the [readme](https://github.com/netlify/netlify-plugin-nextjs#manual-installation) specifically says not to use `next export`.

**To Reproduce**
1. Start a new Next.js project
2. Add the netlify.toml file from the [readme](https://github.com/netlify/netlify-plugin-nextjs#manual-installation)
3. Make sure the build script in your package.json calls `next build`
4. Run `npm run build`
5. Run `netlify deploy`

**Versions**
- Next.js: 10.2.3
- plugin (if installed at fixed version): 3.3.1

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows] macOS
 - netlify/cli version: 3.31.16

**If you're using file-based installation**
- netlify.toml:
```
[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by saidattax** [comment]
I got this error too, then realized deploying manually doesn't work. It works only when connected to a git repository

**Comment by lindsaylevine** [comment]
hey @gragland @saidattax. are you running `netlify build` or `netlify deploy --build` before `netlify deploy` or `netlify deploy --prod? this step actually _runs_ the build process locally (including running the plugin). `netlify build` or `netlify deploy --build` is a prerequisite to deploying locally when using any plugin. if this ends up fixing your problem, please do let us know how we can improve our README/docs so this is clearer!

**Comment by gragland** [comment]
Thanks @lindsaylevine! The issue was that I was running `npm run build` before deployment, not `netlify deploy --build`.
