### ISSUE TITLE
Deprecate `netlify-plugin-cache-nextjs`?

### ISSUE THREAD

**Issue by jonahsnider** [netlify/netlify-plugin-nextjs#391]
I noticed that #185 introduced caching functionality that works as a replacement to my [Next.js cache plugin](https://github.com/jonahsnider/netlify-cache-nextjs).

Should I deprecate that plugin in favor of this one?

(also: consider updating [this blog post](https://www.netlify.com/blog/2020/11/30/how-to-deploy-next.js-sites-to-netlify/#optional-add-the-next-js-cache-plugin) to remove references to my plugin)

**Comment by lindsaylevine** [comment]
@jonahsnider hey jonah, thanks for noticing and opening this with us! cc @jlengstorf on the blog post but yes, you can deprecate your plugin! you don't _need_ to, but as you saw, we wanted to offer what your plugin so generously offered automatically for all next.js sites :)

**Comment by jonahsnider** [comment]
I think the current cache functionality is slightly lacking compared to my plugin (ex. output on success/error), so I'll wait a few months and then mark my package as deprecated.

**Comment by lindsaylevine** [comment]
@jonahsnider what exactly is lacking? we reviewed your src before adding caching here. pls don't hesitate to open a PR to us for whatever you feel is missing.

**Comment by jonahsnider** [comment]
It's not a very important feature but my plugin uses rich status information in the deploy summary for success.
More valuable would be using a warning ([once that gets added](https://github.com/netlify/build/issues/2629#issuecomment-824976842)) on errors.

![deploy summary](https://user-images.githubusercontent.com/7608555/121265650-fa399400-c86d-11eb-853d-1f973df67db0.png)

**Comment by ascorbic** [comment]
This is fixed in #400
