### ISSUE TITLE
Deploy is stuck on  "info  - Collecting page data..."

### ISSUE THREAD

**Issue by MohammadSaad1** [netlify/netlify-plugin-nextjs#404]
**Describe the bug**
I've just migrated to this new plugin and I can't seem to deploy my project. It builds fine locally with "netlify build" (takes about 11 min), but when deploying it to netlify it is stuck on
" info  - Collecting page data..."

**To Reproduce**
Not quiet sure how to reproduce

**Expected behavior**

**Versions**
- Next.js: 10.2.3
- plugin (if installed at fixed version): latest

**If you're using the CLI to build**
 - OS: macOS
 - netlify/cli version: 3.35.3"

**Comment by lindsaylevine** [comment]
hey @MohammadSaad1 - unfortunately there's not much we can do to help without a repo that definitely reproduces your issue :(. it's hard to offer any advice or guidance either with so little information. if you'd like more help, pls provide a repro! 🙏
