### ISSUE TITLE
Support Next.js 10

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#42]
Both this plugin and `next-on-netlify` should officially support Next.js 10.

If this is easy enough to do, we should run tests both on Next.js 9 and 10 too.

**Comment by erezrokah** [comment]
Possibly related to Next.js 10 support https://community.netlify.com/t/nextjs-website-wont-build/27365

**Comment by erezrokah** [comment]
https://github.com/netlify/next-on-netlify/issues/103 is also related
