### ISSUE TITLE
Remove intermediary copy steps

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#43]
All Next.js page/function files are initially copied by `next-on-netlify` to `out_functions` and `out_publish`. 
This plugin then copies all those files from `out_functions` and `out_publish` to the site's Functions/publish directories.

If those are lots of files, this additional copy step might end take lots of build time. Instead, we could remove that intermediary step:
  - Make the main function exported by `netlify-on-netlify` accepts an `options` object so users can customize the location of `out_functions` and `out_publish`: 

https://github.com/netlify/next-on-netlify/blob/a9dade3824d1288770d967cc6f57f238d5947367/index.js#L7

```js
const nextOnNetlify = ({ functionsDir = "out_functions", publishDir = "out_publish" } = {}) => {
```

  - Pass `constants.FUNCTIONS_SRC` and `constants.PUBLISH_DIR` to `next-on-netlify`
  - Remove the additional copy step :tada: 

https://github.com/netlify/netlify-plugin-nextjs/blob/84c6f7f4ccfd6d814bd642d0a27921ef49b67c25/index.js#L74

As a follow-up, we can also expose those to `next-on-netlify` CLI.

What do you think @lindsaylevine?

**Comment by lindsaylevine** [comment]
i think this is a great callout. especially with the CLI, it'll avoid making those additional dirs locally :). let's do it!

**Comment by ehmicky** [comment]
Note: several users have asked for it in https://github.com/netlify/next-on-netlify/issues/36 and https://github.com/netlify/next-on-netlify/issues/73

**Comment by lindsaylevine** [comment]
yeah, long awaited ask. was gonna just wait til we fully transitioned off NoN, but this is great. i'll take care of it shortly :)

**Comment by lindsaylevine** [comment]
> Note: several users have asked for it in [netlify/next-on-netlify#36](https://github.com/netlify/next-on-netlify/issues/36) and [netlify/next-on-netlify#73](https://github.com/netlify/next-on-netlify/issues/73)

to-do for me before closing this issue:
reply to these issues (and any other relevant ones?) about the plugin and this functionality

**Comment by lindsaylevine** [comment]
to-do:
add specific test to next-on-netlify for functionsDir and publishDir
