### ISSUE TITLE
Image function times out without logging any error

### ISSUE THREAD

**Issue by gavinhenderson** [netlify/netlify-plugin-nextjs#435]
**Describe the bug**
Requesting an image times out but doesn't say why

Repo: https://github.com/AceCentre/acecentre.org.uk
Hosted: https://acecentreorguk.netlify.app/

**To Reproduce**
1. Go to 'https://acecentreorguk.netlify.app'
2. Wait ~10 seconds
3. Scroll down see images dont load
4. Check network tab in console
5. See 502 responses with server timeout
6. Check function logs and see nothing besides the timeout message

**Expected behavior**

- Logs explaining why its hanging
- A way to override the function (to add logs)
- The function doesn't hang

**Versions**
- Next.js: 11.0.1
- plugin (if installed at fixed version): 3.4.2

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]: Linux
 - netlify/cli version: 3.38.7

**Comment by gavinhenderson** [comment]
You might see some mixed content warnings, ignore those, thats a separate issue on my side

**Comment by surjithctly** [comment]
I can also see images are loading as 301 redirect instead of rendering it as `webp` on modern browsers. 

![image](https://user-images.githubusercontent.com/1884712/123225318-71cf0c00-d487-11eb-86fd-fbfed7844074.png)

Also, This plugin does not work well with next 11 image import

`import heroImg from "../public/img/hero.png"` This also causes some errors like Timeouts, mixed content warnings etc..

**Comment by gavinhenderson** [comment]
The 301 seems like the intended behaviour of the plugin. It doesn't override the loader, instead it just redirects from the default next path to the custom function. The request made subsequent to the redirect is the one that times out

I've avoided using any next11 imports as I assumed they wouldnt be supported yet.

**Comment by ascorbic** [comment]
Thanks for the report. I'm investigating now. However can I suggest that you start by converting your hero image from png to jpg. It's 2.4MB, and by default we'll keep the same format as the input file.

**Comment by ascorbic** [comment]
Unfortunately I can't build your site, because I don't have acess to redis. I'm going to look into adding better error handling. Could you try running it locally, via `netlify dev`, and see if you get an error message.

**Comment by surjithctly** [comment]
@ascorbic Would be great if the docs are updated on what Next 11 features are supported and not. It would avoid any confusion.

**Comment by ascorbic** [comment]
All the Next 11 features should work. SVG files and GIFs are returned unchanged.

**Comment by surjithctly** [comment]
SVG with Next 11 import throws error when hosted on netlify.

**Comment by NoahBres** [comment]
@ascorbic Do you need another sample to try and reproduce this issue? Most of the images in our site do not work with next 11 images and run into this timeout issue.

**Comment by ascorbic** [comment]
Can you try installing 3.5.0 and see if that fixes it?

**Comment by NoahBres** [comment]
That did not seem seem to change anything.

Uninstalling the plugin, reinstalling, and clearing the build cache and redeploying should have used the latest version right? I did not specify a version in netlify.toml

**Comment by lindsaylevine** [comment]
@NoahBres no, currently we're autoinstalling at 3.4.2. you need to manually `npm install --save @netlify/plugin-nextjs@3.5.0` to enforce that version. itll show you in the build/deploy logs which plugin version you're using.

**Comment by ascorbic** [comment]
Make that `3.6.0` now, as there's another release

**Comment by NoahBres** [comment]
Tested with 3.6.0 (you can see at https://www.operationmedicalcare.org if you'd like) and it is definitely better!

But there are still a loooot of timeouts

![Screen Shot 2021-06-30 at 2 59 30 PM](https://user-images.githubusercontent.com/6739076/124023651-c6a4e200-d9b3-11eb-9de9-154c250fb877.jpg)

In addition to that, are all the images built synchronously? It is very slow.

**Comment by ascorbic** [comment]
Yes, they're build synchronously on first request, but then cached as they use [On Demand Builders](https://docs.netlify.com/configure-builds/on-demand-builders/). How large are the source images? 10s is a very long time for these. I'd expect a second at most.

**Comment by gavinhenderson** [comment]
I was seeing timeouts with images of around ~10 / ~12 MB

**Comment by NoahBres** [comment]
Most of our images are around 1-2mb

**Comment by ascorbic** [comment]
Hi. Could you upgrade the plugin to 4.0.0 or later and see if this still happens? The new plugin has a completely different image server.

**Comment by hendrikmolder** [comment]
Hi – facing a similar error with v4.0.0 on this site: https://next-molder.netlify.app/

It's been timing out with 502s consistently from the beginning.
