### ISSUE TITLE
Next 11 Serverless Functions Break - "Request be smaller than 69905067 bytes for the CreateFunction Operation"

### ISSUE THREAD

**Issue by NoahBres** [netlify/netlify-plugin-nextjs#454]
**Describe the bug**
I have a very small serverless function, 114 lines long with 2 relatively small packages, and it kills the netlify deploys after upgrading to Next 11. It was working fine on Next 10. 

The function compiles to 63.9kb according to `next build`.

![Screen Shot 2021-06-28 at 4 55 52 PM](https://user-images.githubusercontent.com/6739076/123708873-c1b82500-d831-11eb-85d4-0bfd76211344.jpg)

However, upon deploy, this function throws the error "Request must be smaller than 69905067 bytes for the CreateFunction operation." This error seems to be related to AWS lambda functions setting a package size limit of 50mb. This function is definitely under that. 

![Screen Shot 2021-06-28 at 4 58 53 PM](https://user-images.githubusercontent.com/6739076/123709138-25425280-d832-11eb-9a70-120906fbef77.jpg)

**To Reproduce**
1. Implement serverless function
    - Found here:
    https://github.com/New-Millenia-Consulting/operation-medical-care/commit/7e5a6681928335f12a8bb2a8c8365bd4ea391957#diff-bfa062de040f55a15ce910800757061ec3d2fc31d6b7c72d9fa02b75a9ad1133
2. Deploy build

**Versions**
- Next.js: 11.0.0

Here is our deploy log if helpful: https://gist.github.com/vishnuSriram/270e0a5a72122a91c1494fd4a6544524

**Comment by lindsaylevine** [comment]
@NoahBres hey noah! so sorry you're running into this!

do you have `esbuild` configured in your netlify.toml? (see docs https://docs.netlify.com/configure-builds/file-based-configuration/#functions). this should resolve your problem. let us know if it does!

**note**: esbuild in its current state breaks dynamic imports in next. if you're using dynamic imports in your site, we have a fix for the broken imports behind a feature flag. to enable it, add `NETLIFY_EXPERIMENTAL_PROCESS_DYNAMIC_IMPORTS` as an environment variable with the value set to `true`. if you do set this up and test it out, please let us know too! feedback would be invaluable!!!

**Comment by NoahBres** [comment]
This worked great! Thank you so much!!

**Comment by tgmarinho** [comment]
> @NoahBres hey noah! so sorry you're running into this!
> 
> do you have `esbuild` configured in your netlify.toml? (see docs https://docs.netlify.com/configure-builds/file-based-configuration/#functions). this should resolve your problem. let us know if it does!
> 
> **note**: esbuild in its current state breaks dynamic imports in next. if you're using dynamic imports in your site, we have a fix for the broken imports behind a feature flag. to enable it, add `NETLIFY_EXPERIMENTAL_PROCESS_DYNAMIC_IMPORTS` as an environment variable with the value set to `true`. if you do set this up and test it out, please let us know too! feedback would be invaluable!!!

it's working for me also, thanks!

**Comment by tgmarinho** [comment]
Complete solution here: https://github.com/netlify/netlify-plugin-nextjs/issues/571#issuecomment-890223687

**Comment by Gnarus-G** [comment]
I am currently wrestling with this issue.

I've applied these configurations as I've read to do.
![image](https://user-images.githubusercontent.com/37311893/136044793-1aa075d3-1f6b-4179-8a36-7126e4fc07e3.png)

![image](https://user-images.githubusercontent.com/37311893/136045109-ed3d7243-59e1-49ba-a7db-eca45d403924.png)

![image](https://user-images.githubusercontent.com/37311893/136045191-6ad338bc-f67a-40a9-bf2f-3019663dbd2d.png)

![image](https://user-images.githubusercontent.com/37311893/136045888-59ff9007-bf15-4564-89a0-f1542d0eb74b.png)

Am I missing something?

P.S. Here is the source code if you need it, https://github.com/Gnarus-G/bytin

**Comment by lindsaylevine** [comment]
@Gnarus-G just to confirm - you're getting the "request must be smaller than.." error?

**Comment by Gnarus-G** [comment]
@lindsaylevine Yes I am.
