### ISSUE TITLE
Clear publish directory before building

### ISSUE THREAD

**Issue by ascorbic** [netlify/netlify-plugin-nextjs#464]
Currently if `out` exists from a previous build, the build will fail as it refuses to overwrite the old assets. The build should clear the contents of the publish dir so that builds can happen. It needs to ensure that it hasn't accidentally been set to the root of the repo too.

**Comment by lindsaylevine** [comment]
is this for the CLI? this is what https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/lib/helpers/handleFileTracking.js is supposed to take care of

**Comment by kandizzy** [comment]
I am experiencing this issue. I cannot get my site to deploy. I had no problem deploying the starter app which I [cloned](https://github.com/kandizzy/next-netlify-starter). I found another post to the forums with the [same issue](https://answers.netlify.com/t/plugin-netlify-plugin-nextjs-internal-error-error-out-index-html-already-exists/37686). The differences I have noted between the starter app and mine are 

- starter app is  deployed with `@netlify/build 16.0.0`. My app is deploying with `@netlify/build 16.1.0`
- starter app is using Next.js 11.0.0, my app is using `Next.js 11.0.1`

The deploy logs are identical until it tries to copy files into the build directory `out`. Then it errors out even if it is the first time I try a deploy (I created a few new sites to be sure). Any suggestions on how to get around this would be much appreciated!

```
10:20:53 AM: ────────────────────────────────────────────────────────────────
10:20:53 AM:   Plugin "@netlify/plugin-nextjs" internal error                
10:20:53 AM: ────────────────────────────────────────────────────────────────
10:20:53 AM: ​
10:20:53 AM:   Error message
10:20:53 AM:   Error: '/opt/build/repo/out/index.html' already exists
10:20:53 AM: ​
10:20:53 AM:   Plugin details
10:20:53 AM:   Package:        @netlify/plugin-nextjs
10:20:53 AM:   Version:        3.7.1
10:20:53 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
10:20:53 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
10:20:53 AM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
10:20:53 AM: ​
10:20:53 AM:   Error location
10:20:53 AM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
10:20:53 AM:       at mayCopyFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:62:11)
10:20:53 AM:       at onFile (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:10)
10:20:53 AM:       at getStats (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
10:20:53 AM:       at startCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
10:20:53 AM:       at handleFilterAndCopy (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
10:20:53 AM:       at copySync (/opt/build/repo/.netlify/plugins/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
10:20:53 AM:       at setupStaticFileForPage (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/src/lib/helpers/setupStaticFileForPage.js:12:3)
10:20:53 AM: ​
10:20:53 AM:   Resolved config
10:20:53 AM:   build:
10:20:53 AM:     command: yarn build
10:20:53 AM:     commandOrigin: config
10:20:53 AM:     publish: /opt/build/repo/out
10:20:53 AM:     publishOrigin: config
10:20:53 AM:   plugins:
10:20:53 AM:     - inputs: {}
10:20:53 AM:       origin: ui
10:20:53 AM:       package: '@netlify/plugin-nextjs'
```

**Comment by lindsaylevine** [comment]
@kandizzy hey! i forked the starter repo, upgraded to next 11.0.1 and used the noted build version, and i was able to deploy. you can see logs https://app.netlify.com/sites/happy-yalow-f6a8f1/deploys/60f9688891797ee107262897. i believe you may already have an index.html in your publish folder but not entirely sure. we'd need to see your _exact_ code, deploy settings and/or netlify.toml.

**Comment by kandizzy** [comment]
@lindsaylevine hi! yes, that's exactly what happened. I had an `index.tsx` in `/pages` and an `index.html` in `/public`

**Comment by lindsaylevine** [comment]
@kandizzy awesome, so your issue is fixed? (since you shouldnt need an index.html in your /public _because_ of index.tsx presumedly using getStaticProps and trying to prerender into out)

**Comment by kandizzy** [comment]
@lindsaylevine yes, I am able to deploy now. I did change my build command to `rm -rf out && yarn build`. I am not sure that was entirely necessary though. In the meantime, I updated my original comment with this information in case anyone has a double file and runs into the same problem.

**Comment by johnclary** [comment]
hello! just want to report that i came across the same issue when migrating to next from create-react-app. CRA uses a `public/index.html` as described [here](https://create-react-app.dev/docs/using-the-public-folder/#changing-the-html), and we had overlooked it when transitioning our app structure.

```
Error: '/opt/build/repo/build/index.html' already exists
```

Deleting the file fixed my issue. Thanks!

**Comment by acollierr17** [comment]
> hello! just want to report that i came across the same issue when migrating to next from create-react-app. CRA uses a `public/index.html` file as described [here](https://create-react-app.dev/docs/using-the-public-folder/#changing-the-html), and we had overlooked it when transitioning our app structure. It would seem that a local build quietly overwrites this file, however the Netlify build was failing.
> 
> ```
> Error: '/opt/build/repo/build/index.html' already exists
> ```
> 
> Deleting the file fixed my issue. Thanks!

Would also like to confirm that deleting `/public/index.html` fixed my issue too!

**Comment by lindsaylevine** [comment]
closing since this will not be an issue in the plugin rewrite
