### ISSUE TITLE
Override templates to add custom behaviour

### ISSUE THREAD

**Issue by gavinhenderson** [netlify/netlify-plugin-nextjs#493]
**Is your feature request related to a problem? Please describe.**
As a netlify user I would like to know how many times each function is called so that I can reduce functions that are called to much to avoid getting moved up a function level.

**Describe the solution you'd like**
If the base function template was overridable then I could copy it and add metric collecting for each function. 

**Describe alternatives you've considered**
One alternative could be to provide a function to netlify-plugin-nextjs for it to call on every function to collect metrics but I am not familiar enough with the internals to know if this would make sense.

Another alternative would be to call a metric collecting function manually at the beginning of every 'getServerSideProps' however, I worry that it would be easy to miss functions doing this and I would miss things like the image function doing this.

Yet another alternative would be to add an extra step after the Next Build and before the function build to mutate the functions to add in my metric collecting. But this seems more prone to failure.

**Comment by lindsaylevine** [comment]
@gavinhenderson hey! thanks for opening this <3. this is a super great and reasonable request. sorry for the priority low label (it's relative to some big things we still have tabled 🥴). assuming we won't get to this for a bit, you could use `patch-package` for now to patch this plugin with the desired change to the function template. lmk if you want any more help w that!!

**Comment by gavinhenderson** [comment]
@lindsaylevine Thanks for the response. 

No worries about the low priority label, I appreciate the honesty.

I'll give `path-plugin` a shot, thanks for the pointer

**Comment by ascorbic** [comment]
Hi. I'm going to close this, because version 4 of the plugin works in a different way, so this doesn't as much sense
