### ISSUE TITLE
sharp is not a function: Error when using next/image in a yarn workspace that has sharp as a dependency in one of its packages

### ISSUE THREAD

**Issue by Marcelo-Figueiredo** [netlify/netlify-plugin-nextjs#508]
**Describe the bug**
Having the package **sharp** in a package of yarn workspaces makes the next_image function crash. The problem has something to do with yarn hosting behavior because the function also uses **sharp**. The nohoist parameter does not solves it.

![image](https://user-images.githubusercontent.com/43547101/125137752-b4c5ec00-e0e3-11eb-86b2-ccc23aaf00c7.png)

- the **common** package has the **sharp** dependency
- the **next-website** uses the next_image function which uses **sharp**

The error:
![image](https://user-images.githubusercontent.com/43547101/125139636-47b45580-e0e7-11eb-86bd-0cf273477b7e.png)
```
{
  "errorType": "TypeError",
  "errorMessage": "sharp(...).rotate(...).jpeg(...).png(...).webp(...).avif is not a function",
  "trace": [
    "TypeError: sharp(...).rotate(...).jpeg(...).png(...).webp(...).avif is not a function",
    "    at handler (/var/task/packages/next-website/netlify/functions/next_image.js:122:6)",
    "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
  ]
}
```

**To Reproduce**
Steps to reproduce the behavior 

[Github repository](https://github.com/Marcelo-Figueiredo/next-plugin-issue-repository)

- **master** branch has errors [(deployed here)](https://sharp-issue.marcelofg.com/)
- **no-errors** branch works fine [(deployed here)](https://no-errors.sharp-issue.marcelofg.com/)

Clone the repository above, or

1. Add sharp in one yarn workspace package (as i did in `packages/common`)
2. Have another package that is a Next.js project using next/image
3. Deploy to netlify with Next Essentials plugin

**Expected behavior**
The fact that i'm using sharp in one of my packages should not break the next/image function.

**Versions**
- Next.js: 10.2.3
- plugin (if installed at fixed version): 3.6.3 from Netlify UI

**Comment by ascorbic** [comment]
Hey. The issue is that your other version of sharp doesn't support avif, which was added in 0.27. I'm not sure why it's resolving the wrong version, but are you able to upgrade the other package to use sharp 0.27 or later?

**Comment by Marcelo-Figueiredo** [comment]
> 
> 
> Hey. The issue is that your other version of sharp doesn't support avif, which was added in 0.27. I'm not sure why it's resolving the wrong version, but are you able to upgrade the other package to use sharp 0.27 or later?

Yes, i'm able to upgrade it. In fact, i just did and the issue is gone. 

Thank you, i'll mark this as closed.
