### ISSUE TITLE
Webpack5 Errors with Serverless Mode in Next + Next-Auth + Netlify-Plugin-Nextjs

### ISSUE THREAD

**Issue by bcnichols3** [netlify/netlify-plugin-nextjs#527]
**Describe the bug**
I'm running Next 11 and @netlify/plugin-nextjs 3.6.3 and seeing this message in the `onPreBuild` step when I deploy:

```The "target" config property must be one of "serverless", "experimental-serverless-trace". Building with "serverless" target.```

However the next.js team recommends you [not use serverless](https://github.com/vercel/next.js/issues/20487#issuecomment-753884085). The results is a webpack 5 error that seems to be related to next-auth: it depends on TypeORM internally, which has a few dynamic optional imports that are used depending on the DB you hook TypeORM up to. Even when they're not being used, and should be shook, Webpack is unable to find those dependencies and you'll get errors like this:

```ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/opt/build/repo/node_modules/typeorm/platform'```

Netlify blocks me from building if it demands I use `serverless`. The only way I've been able to build locally using Next11 and Next-Auth is without a specified `target` in my `next.config.js`. Is there a way to tell the Netlify next plugin _not_ to turn on `target: serverless`?

**To Reproduce**
1. Create a Next 11 app
2. Set up Next-Auth with a database (I used PostgreSQL)
3. Don't specify a DB adapter (next-auth will use TypeORM as default)
3. Deploy to Netlify
4. See errors in log

**Expected behavior**
Next is able to complete a build that Netlify can deploy.

**Versions**
- Next.js: 11.0.0
- next-auth: 3.27.1
- netlify plugin: first no install, then 3.6.3

- netlify.toml:

```
[[plugins]]
  package = "@netlify/plugin-nextjs"
```

**Comment by ascorbic** [comment]
Hi. The Essential Next.js plugin requires a serverless target because that's how it deploys the routes to Netlify functions. The other features are then implemented in our wrapper functions. Can you try using `experimental-serverless-trace` and see if that fixes the import issue?

**Comment by bcnichols3** [comment]
I can absolutely experiment with that later tdoay @ascorbic ! Do you happen to know what the differences are between `experimental-serverless-trace` and `serverless`?

**Comment by lindsaylevine** [comment]
@bcnichols3 when using `serverless`, next tries to inline all dependencies for you, which has failed for some db providers + next on netlify like prisma, firebase and mongo in the past. with experimental-serverless-trace, next does not inline dependencies, which allows netlify to try to correctly bundle them into your functions. (see https://github.com/vercel/next.js/issues/8797#issuecomment-533841333 for more info). if e-s-t doesn't work for you, maybe give [this comment](https://github.com/netlify/netlify-plugin-nextjs/issues/154#issuecomment-855261677) a look? we've unfortunately seen a handful of next-auth + mongo pain points :/

**Comment by bcnichols3** [comment]
I greatly appreciate the extra color here. The true problem here is the lack of clarity on what's actually failing and why — and since this is caused by several techs interconnecting, obviously it's not an easy problem for just the `next-auth` team or just the `typeorm` team or just the `netlfify-plugin-nextjs` team or just the `webpack` team to address.

I will dig into e-s-t mode when I can and report back. With luck that'll solve my issue.

**Comment by lindsaylevine** [comment]
yeah, i hear you :/ do let us know about e-s-t. it's possible also adding `esbuild` as your node_bundler (https://docs.netlify.com/configure-builds/file-based-configuration/#functions) could help. we'll get to the bottom of it!

**Comment by tbooth-prog** [comment]
Hi, I was having the exact same issue and can confirm that setting the `target` to `experimental-serverless-trace` in `next.config.js` did the trick for me. Thanks

**Comment by lindsaylevine** [comment]
@tbooth-prog thanks for letting us know! 🙏 we'll keep open for a little til we hear from @bcnichols3. hopefully e-s-t solves their issue as well, but it may be a greater issue if their overall request is to opt out of serverless.

**Comment by bcnichols3** [comment]
@lindsaylevine e-s-t has cleared the webpack error! I'm getting a db connection timeout error ATM -- but that may be (A) my screw-up or (B) a separate issue :)

**Comment by lindsaylevine** [comment]
@bcnichols3 oh no! i'll go ahead and close this one, but if you find you can't resolve your db connection timeout, please feel free to open a new issue! we _used_ to have `netlify function timed out after 10.1 seconds` issues with some db integrations, but we patched it, so i'd be surprised if it's that.
