### ISSUE TITLE
Netlify NextJS builds are broken in 3.7.0 when using multiple npm commands

### ISSUE THREAD

**Issue by andismith** [netlify/netlify-plugin-nextjs#528]
**Describe the bug**
A bug has been introduced with version 3.7.0 where if the `netlify.toml` configuration file contains multiple npm commands such as `npm run build && npm run export`, the plugin fails with an internal error.

![image](https://user-images.githubusercontent.com/426677/125694647-d81508fa-af51-405c-87c6-8901cddc54ad.png)

![image](https://user-images.githubusercontent.com/426677/125694686-b6da1b5e-e60e-437c-a57f-1d0df5b52b62.png)

**To Reproduce**
1. Fork https://github.com/andismith/nextjs-test-blog (this is a copy of the Netlify NextJS starter blog, with an adjusted `netlify.toml` file).
2. Build it on Netlify
3. See error
4. Run `npm install @netlify/plugin-nextjs@3.6.3 --save-dev`
5. See it now passes

Example at: https://app.netlify.com/sites/elated-mcclintock-cdc73c/deploys

**Expected behavior**
The build should still work in v3.7.0

**Versions**
- Next.js: 11
- @netlify/plugin-nextjs: 3.7.0

**If you're using file-based installation**
- netlify.toml:
```
[build]
  publish = "dist"
  command = "npm run build && npm run export"
```

(this also occurs for multiple yarn commands too)

**Comment by andismith** [comment]
I think it may be a result of https://github.com/netlify/netlify-plugin-nextjs/commit/b1fd513c8ac142c335bc3ae950bd093da20466fe

**Comment by baeteja** [comment]
3.7.0 causes issues for me as well when I use multiple npm scripts

**Comment by ascorbic** [comment]
Hi both! Thanks for the report. I've isolated the issue and opened a PR with a fix and should have that released later today.

**Comment by ascorbic** [comment]
This is now published in 3.7.1. Can you check that this fixes it for you? I've added your specific command as a test case too.

**Comment by andismith** [comment]
Thanks for attending to this so quick.

For some reason when building it in Netlify it's still picking up 3.7.0 at the latest version. I guess it takes a little while to propagate the new version. Will let you know once I can test this properly.

**Comment by ascorbic** [comment]
Yeah, we don't immediately update the auto-installed version, in case issue come up. It'll be auto-installed later today, but you can try it now by installing `@netlify/plugin-nextjs@latest` from npm.

**Comment by ascorbic** [comment]
If you do a build now it should use the new version of the plugin.

**Comment by andismith** [comment]
That's now working fine, thank you!
