### ISSUE TITLE
Too much redirecting when using the image optimizer on Netlify

### ISSUE THREAD

**Issue by rayventerprise** [netlify/netlify-plugin-nextjs#540]
**Describe the bug**
I noticed the images which use the image optimizer perform much slower when accessed on our Netlify build which I assuming is due to the redirect overhead the current setup requires.

Looks like it starts here: https://github.com/netlify/netlify-plugin-nextjs/blob/7d01abaaefe86983319438b9a6bec22b90763ce6/src/lib/steps/setupRedirects.js#L58

 mydomain.com/_next/image -> mydomain.com/nextimg -> mydomain.com/.netlify/functions/whatever

**Versions**
- Next.js 11

Anyway we can avoid this / cut down on the redirecting?

**Comment by ascorbic** [comment]
Hi. The delay is unlikely to be due to the redirects, but is rather because on first load it needs to load and resize the image. It should be faster for subsequent visitors though, as the result is then cached.

**Comment by rayventerprise** [comment]
@ascorbic What your saying is correct, It is faster after first load however its still doing redirects to the "nextimg" and not ideal speed... it also just adds alot of bloat to the network tab. Is no redirect supposed to occur after initial caching and if so is there a variable I am missing perhaps? I can DM you the website specifically I am referring to.

**Comment by ascorbic** [comment]
Fixed in edge functions https://github.com/netlify/netlify-plugin-nextjs/pull/1310
