### ISSUE TITLE
Difference between npm run build/start and Netlify regarding webpack file-loader rules, locales and routing

### ISSUE THREAD

**Issue by phbernard** [netlify/netlify-plugin-nextjs#590]
**Describe the bug**
When using custom webpack rules in `next.config.js` and locales, a route such as `/[locale]/some/path.js` works with `npm run build && npm run start` but not on Netlify.

**To Reproduce**
1. Get the sample app with `git clone https://github.com/phbernard/netlify-plugin-nextjs-locale-and-route-issue`. In this app, `next.config.js` is using a file-loader webpack rule to expose a worker.
2. Start it with `npm install && npm run build && npm run start`
3. Visit the app, at http://localhost:3000
4. Using the Dev Tools, Network tab, spot the access to the worker (you may need to refresh the page). You should find a URL such as `http://localhost:3000/_next/static/worker/ff2b3b2479e7a9fbaea2244ed1875dfa.js`.
5. Open this URL in a new tab: it works.
6. Edit this URL to add `fr` (a locale configured in the app) as a path prefix. For example, `http://localhost:3000/fr/_next/static/worker/ff2b3b2479e7a9fbaea2244ed1875dfa.js`. This URL works, too.
7. The app has been deployed to https://silly-wilson-860691.netlify.app/. Visit https://silly-wilson-860691.netlify.app/_next/static/worker/a9f2364fa39c464e6ddf5fd2caccc8fd.js: it works. Visit the locale-prefixed version https://silly-wilson-860691.netlify.app/fr/_next/static/worker/a9f2364fa39c464e6ddf5fd2caccc8fd.js: it does not work

**Expected behavior**
App behavior should be identical with `npm run start` and Netlify: locale-prefixed routes should work.

**Versions**
- Next.js: 11.0.1
- plugin (if installed at fixed version): N/A

**Comment by lindsaylevine** [comment]
@phbernard lol hello again!! i think i know whats going on. ty x100 for the details/repo. will get to it when i can 🥴

**Comment by lindsaylevine** [comment]
@phbernard hey, i'm finally here! 😅 i tested this against our plugin rewrite and can confirm that it will be working in the rewrite. our goal is to release a beta of the rewrite in the next few weeks for all next users to test against. since you've always been a wonderful issue reporter over here, we'd love for you to try it out when it's ready. i'll circle back here but i wanted to give you an update since i did fork your repo and threw the label on here. hang tight!!!

**Comment by ascorbic** [comment]
I'm closing this because the new version of the plugin is out, which fixes this. Thanks for your report!
