### ISSUE TITLE
404 page does not work with custom 404 page and multiple locales

### ISSUE THREAD

**Issue by phbernard** [netlify/netlify-plugin-nextjs#591]
**Describe the bug**
Netlify displays a message "Page Not Found - Looks like you've followed a broken link or entered a URL that doesn't exist on this site." instead of a custom 404 page when the app has a custom 404 page *and* locales are configured.

**To Reproduce**

*One click*

Visit https://condescending-dubinsky-342e39.netlify.app/does-not-exist : the page is from Netlify instead of the custom 404 page the app defines.

Get the app at https://github.com/phbernard/netlify-plugin-nextjs-404-issue

*Manually*

1. Create a new NextJS app.
2. Create `pages/404.tsx` and populate it with minimalist content
3. Edit `nextjs.config.js` and configure i18n:

```
i18n: {
  defaultLocale: 'en',
  locales: ['en', 'fr'],
  localeDetection: false
}
```

4. Start the app with `npm run dev`
5. Visit http://localhost:3000/does-not-exist : the custom 404 page is returned, as expected.
6.  Deploy the app on Netlify
7. Visit the app with a wrong path: a page from Netlify is returned instead of the custom page.

Note: the error shows up only when combining a custom 404 page *and* locales. If there is no custom page, Netlify shows the default NextJS 404 page, as expected. If there is no i18n configuration, Netlify displays the custom 404 page, as expected.

**Expected behavior**
Netlify should return the custom 404 page.

**Versions**
- Next.js: 11.0.1
- plugin (if installed at fixed version): N/A

**Comment by lindsaylevine** [comment]
@phbernard hello! thanks for the thorough issue and repo as always. will take a look asap!

**Comment by lindsaylevine** [comment]
soo turns out i'd added this logic in... but only for a certain page type. https://github.com/netlify/netlify-plugin-nextjs/blob/72d34ce73f4204e41d31500a09202031b3ae5777/src/lib/pages/withoutProps/setup.js#L23. going to add for getStaticProps as well.
