### ISSUE TITLE
Does this plugin support "static" images?

### ISSUE THREAD

**Issue by stefanprobst** [netlify/netlify-plugin-nextjs#596]
**Is your feature request related to a problem? Please describe.**

This is more a question:

Next.js recently added the ability to serve "static" images, i.e. imported images will get a cache header of `public,max-age=31536000,immutable`. when deploying the project on netlify however, i get `public, max-age=0, must-revalidate`.

Is this something I need to configure somewhere, or something this plugin does not support (yet)

**Comment by lindsaylevine** [comment]
hey @stefanprobst! my teammate @ascorbic who's OOO right now would be the best person to answer this for you, but i'll try to get some info for you until he comes back. if you don't hear from me again, then i'll just be deferring to him. stay tuned 📻

**Comment by ascorbic** [comment]
Hi. We don't handle headers for static images in the build plugin, but rather let the Netlify CDN handle them. By default it sets must-revalidate, but because it uses an etag, it will quickly return a 302 not modified response from the edge.

**Comment by stefanprobst** [comment]
cool, thanks for the info!
