### ISSUE TITLE
Preview mode not working

### ISSUE THREAD

**Issue by theelk801** [netlify/netlify-plugin-nextjs#598]
I'm unable to get preview mode working, I've followed [this guide](https://github.com/vercel/next.js/tree/canary/examples/cms-contentful) to set up previews and [this guide](https://github.com/netlify/netlify-plugin-nextjs) to get it working on netlify.  It works when I run it locally but it doesn't work on netlify, it sends me to a 404 instead of a preview. Is there a different way I should set up preview mode? There's only one guide available and I followed it.

**Comment by lindsaylevine** [comment]
@theelk801 hello! could you please provide a deployable repo that reproduces your issue? that would help us quickly diagnose why you're running into issues :).
