### ISSUE TITLE
the data returned on index page built using SSG returns 404

### ISSUE THREAD

**Issue by zemachfm** [netlify/netlify-plugin-nextjs#609]
**Describe the bug**
After building the project on the index SSG, the JSON file returned at run time when preloading the pages is incorrect.
for example, I have two languages
preloading for the language en on the index page,  the JSON data for the page was supposed to be returned _data/.../en.json but the config now returns en/.json which causes a 404 page, which causes the page to reload after 3 load attempts.
remember if you change the URL from en/.json to _data.../en.json it will load and work well

The current site supports multiple languages
The same happens with other pages too.

but other pages are fine and are working perfectly this might be because it's the `index.tsx`

this actually cause the page to reload when clicked on the front page, because it can't get data for the page

---
_redirect has
`/feed/podcast /feed/podcast.xml`

next.config.js

`{
  locales: ['en', 'am'],
  defaultLocale: 'en',
  localeDetection: true,
}`
`webpacked.target = 'serverless';
webpacked.trailingSlash = true;
webpacked.exportTrailingSlash = true;`

netlify.toml
`[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"`

`[[plugins]]
  package = "@netlify/plugin-nextjs"`

`[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"`

**To Reproduce**
1. setup next with next redux wrapper
2. put a get static props in index.tsx
3. you should see this error
use

**Expected behavior**

the page JSON file was supposed to be correct

the problem exists only on index.tsx but **works perfectly locally both on development and production**

**Comment by lindsaylevine** [comment]
@zemachfm hey! thanks a bunch for opening this issue. sorry you're running into an i18n issue! with our current bandwidth i have to ask you to please provide a simple and deployable repo that reproduces your issue. we just don't have the time to set up a site with next redux wrapper and your specific use case of i18n and next. once we have that, we should be able to help much more quickly! 🙏

**Comment by zemachfm** [comment]
this was an issue related to a next.config.js file

turning off the 
`trailingslash` off or deleting it did it for me

**Comment by lindsaylevine** [comment]
ok thanks for letting us know! feel free to comment again for help if needed!
