### ISSUE TITLE
Is there a known limit/threshold for the number of pages before a timeout is triggered?

### ISSUE THREAD

**Issue by dreamyguy** [netlify/netlify-plugin-nextjs#623]
Hi all, thank you for an amazing plugin!! 👏

After nearly 3 days of constant testing our team has concluded the problems we're experiencing at build time boil down to timeouts.

The Next application builds fine and `@netlify/plugin-nextjs` takes over without a hitch, completing the build **as long as we have about maximum 12k pages**.

We're now 1k over that "limit" and we fail at every build after ~30 mins. 📉

We're considering our options, but the ideal scenario would be to get past this limitation, at least once, so that we could release and work on incremental builds past that point.

We know that many other factors play a role in build time, but if we suppose "number of pages" was a thing... **How many (usable) pages would one be able to output and deploy through `@netlify/plugin-nextjs`?** 10k? 50k? 100K?

Bonus: Does `@netlify/plugin-nextjs` have its own timeout, or is it always the sum of the whole build process?

**Comment by dreamyguy** [comment]
@lindsaylevine cheers for the quick feedback! 🎉 

I can confirm that downgrading to `3.7.1` helped us finish the build without the timeout. That is great because we can now move on to optimisation.

Below is our build log, both before and after. The "before" part would fail at different stages, depending of how long the different parts took to complete. But the time-consuming gaps were consistent. We usually would reach or get past the "🔀 Setting up redirects" step. I marked the gaps with "👉" along with the time difference.

The parts with "⚠️" were present at every build. It does make sense when it fails, but made us confuse when they show on successful builds as well (that's why we marked them).

**BEFORE**

```
2:22:26 PM: Build ready to start
👉 1:15 (Pre-build)
2:23:44 PM: $ yarn build:netlify:develop
👉 3:43 (Build)
2:27:27 PM: (build.command completed in 3m 43.1s)
---
2:27:27 PM: Detected Next.js site. Copying files...
2:27:27 PM: ** Running Next on Netlify package **
2:27:27 PM: 🚀 Next on Netlify 🚀
2:27:27 PM: 🌍️ Copying public folder to /opt/build/repo/frontend/build
2:27:27 PM: 💼 Copying static NextJS assets to /opt/build/repo/frontend/build
2:27:27 PM: 💫 Setting up API endpoints as Netlify Functions in /opt/build/repo/frontend/netlify/functions
2:27:27 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in /opt/build/repo/frontend/netlify/functions
2:27:28 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in /opt/build/repo/frontend/netlify/functions
2:27:28 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo/frontend/build
👉 6:59 (Copying static pages to their destination)
2:34:27 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in /opt/build/repo/frontend/netlify/functions
2:34:27 PM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in /opt/build/repo/frontend/netlify/functions
2:34:27 PM: 🔥 Copying pre-rendered pages without props to /opt/build/repo/frontend/build
2:34:27 PM: Building 27408 pages
2:34:34 PM: 🔀 Setting up redirects
👉14:22 (Setting up redirects)
2:49:12 PM: 🔀 Setting up headers
2:49:13 PM: ✅ Success! All done!
👉 6:16 (Time between 'success' and completion of '@netlify/plugin-nextjs onBuild')
2:56:29 PM: (@netlify/plugin-nextjs onBuild completed in 29m 2.1s)
---
2:56:30 PM: Execution timed out after 33m44.14431374s ⚠️
2:56:30 PM: Error running command: Command did not finish within the time limit ⚠️
2:56:30 PM: Failing build: Failed to build site ⚠️
2:56:30 PM: Failed during stage 'building site': Command did not finish within the time limit ⚠️
2:56:30 PM: Finished processing build request in 34m1.96035952s ⚠️
```

**AFTER**

```
10:08:54 PM: Build ready to start
👉  1.31 (Pre-build)
10:10:13 PM: $ yarn build:netlify:develop
👉  4.45 (Build)
10:14:40 PM: (build.command completed in 4m 26.9s)
---
10:14:40 PM: Detected Next.js site. Copying files...
10:14:40 PM: ** Running Next on Netlify package **
10:14:40 PM: 🚀 Next on Netlify 🚀
10:14:40 PM: 🌍️ Copying public folder to /opt/build/repo/frontend/build
10:14:40 PM: 💼 Copying static NextJS assets to /opt/build/repo/frontend/build
10:14:40 PM: 💫 Setting up API endpoints as Netlify Functions in /opt/build/repo/frontend/netlify/functions
10:14:40 PM: 💫 Setting up pages with getInitialProps as Netlify Functions in /opt/build/repo/frontend/netlify/functions
10:14:40 PM: 💫 Setting up pages with getServerSideProps as Netlify Functions in /opt/build/repo/frontend/netlify/functions
10:14:41 PM: 🔥 Copying pre-rendered pages with getStaticProps and JSON data to /opt/build/repo/frontend/build
10:14:42 PM: 💫 Setting up pages with getStaticProps and fallback: true as Netlify Functions in /opt/build/repo/frontend/netlify/functions
10:14:42 PM: 💫 Setting up pages with getStaticProps and revalidation interval as Netlify Functions in /opt/build/repo/frontend/netlify/functions
10:14:42 PM: 🔥 Copying pre-rendered pages without props to /opt/build/repo/frontend/build
10:14:42 PM: Building 27408 pages
10:14:50 PM: 🔀 Setting up redirects
👉  0:31 (Setting up redirects)
10:15:09 PM: 🔀 Setting up headers
10:15:09 PM: ✅ Success! All done!
👉  6:49 (Time between 'success' and completion of '@netlify/plugin-nextjs onBuild')
10:21:58 PM: (@netlify/plugin-nextjs onBuild completed in 7m 18.5s)
---
👉  1:22
10:23:20 PM: (Functions bundling completed in 1m 21.8s)
10:23:20 PM:
10:23:20 PM: ───────────────────────────────────
10:23:20 PM:   6. onPostBuild command from @netlify/plugin-nextjs
10:23:20 PM: ───────────────────────────────────
10:23:20 PM:
10:23:22 PM: Next.js cache saved.
10:23:22 PM:
10:23:22 PM: (@netlify/plugin-nextjs onPostBuild completed in 1.9s)
10:23:22 PM:
10:23:22 PM: ───────────────────────────────────
10:23:22 PM:   7. onPostBuild command from netlify-plugin-cache-nextjs
10:23:22 PM: ───────────────────────────────────
10:23:22 PM:
10:23:22 PM: Cached the .next folder at the location `.next/cache`
10:23:23 PM:
10:23:23 PM: (netlify-plugin-cache-nextjs onPostBuild completed in 541ms)
10:23:23 PM:
10:23:23 PM: ───────────────────────────────────
10:23:23 PM:   8. Deploy site
10:23:23 PM: ───────────────────────────────────
10:23:23 PM:
10:23:23 PM: Starting to deploy site from 'frontend/build'
10:23:25 PM: Creating deploy tree asynchronously
10:23:26 PM: Creating deploy upload records
10:23:38 PM: 13702 new files to upload
10:23:38 PM: 17 new functions to upload
10:26:44 PM: Site deploy was successfully initiated
10:26:44 PM:
10:26:44 PM: (Deploy site completed in 3m 21.8s)
10:26:45 PM:
10:26:45 PM: ───────────────────────────────────
10:26:45 PM:   Netlify Build Complete
10:26:45 PM: ───────────────────────────────────
10:26:45 PM:
10:26:45 PM: (Netlify Build completed in 16m 35.7s)
10:26:45 PM: Execution timed out after 17m25.704874586s ⚠️
10:26:45 PM: Error running command: Command did not finish within the time limit ⚠️
10:26:45 PM: Creating deploy upload records
10:26:45 PM: Failing build: Failed to build site ⚠️
10:26:45 PM: Failed during stage 'building site': Command did not finish within the time limit ⚠️
10:26:45 PM: Finished processing build request in 17m48.94167918s ⚠️
10:26:54 PM: Starting post processing
10:26:54 PM: Post processing - HTML
10:49:02 PM: Post processing - header rules
10:49:02 PM: Post processing - redirect rules
10:49:11 PM: Post processing done
10:49:12 PM: Site is live ✨
```

Note how the build "fails" but still keeps going. I suppose we're at border of failure here.

We're going to use [Incremental Static Regeneration](https://vercel.com/docs/next.js/incremental-static-regeneration) to improve our build-times. Excerpt from docs:

> **Generating Paths**
> Next.js defines which pages to generate at build-time based on the paths returned by `getStaticPaths` . For example, you can generate the most popular 1,000 products at build-time by returning the paths for the top 1,000 product IDs in `getStaticPaths`.
>
>The remaining pages can be generated on-demand by specifying fallback as blocking or true in `getStaticPaths`:
>
> - fallback: blocking (preferred) - when a request is made to a page that hasn't been generated, Next.js will server-render the page on the first request. Future requests will serve the static file from the cache.

This will enable us to build the most crucial pages statically and have all others be rendered server-side. That way we can have zillions of pages, if we must.

@wein-hillary thanks for approaching! We appreciate knowing that we could get some more minutes, but we're confident we found a more robust approach to our scenario (mentioned above).

We hope this information can help others find a solution to time-out limitations! 🙌

**Comment by lindsaylevine** [comment]
@dreamyguy hey! thanks for the detailed writeup. i want to make sure we can help you optimize as much as possible!

1. yeah, i can't explain why there'd be the build failure logs with a complete site deploy. if you think it could be more than just teetering the edge of the limits and want us to investigate more, you could send us the direct link to that deploy's logs.
2. please note that ISR behaves differently on netlify than it does on vercel or other alternatives. see: https://github.com/netlify/netlify-plugin-nextjs/blob/main/docs/caveats.md. 

the main problem with 3.8.0 increasing build times is that fallback: true or fallback: blocking, as stated in the docs linked above, now uses netlify's `on demand builders` to cache the first page built demand. that caused an issue with preview mode, where users want to preview completely dynamic content, but the first results/drafts built on demand get cached. in 3.8.0 we had to generate _two_ separate functions for these page types instead of 1 - a standard function for preview mode and an on demand builder for normal mode.

based on you describing you intended use of ISR, you would in fact need fallback: true or blocking to both (a) pre-render your most crucial pages and (b) SSR the rest. however, as i described above in 3.8.0, this will likely cause your builds to timeout. if you use ONLY `revalidate` on netlify (and omit fallback), it will reduce your build times in >= 3.8.0, but it will SSR 100% of the time (and not pre-render anything). therefore i either recommend using fallback: true/blocking on 3.7.1 or fallback true/blocking on 3.8.0 with extra build minutes maybe or omitting fallback on 3.8.0.

all that said, there is hope for this less than ideal workflow. we're currently working on a rewrite of the plugin where we wont have to build a function for every page/route which will dramatically improve build times. i can't give a concrete ETA right now but hopefully you can work with the recommendations above until we can get that out 🙏
