### ISSUE TITLE
Cache `.next/cache/` between builds

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#63]
We could use the [`cache` utility](https://github.com/netlify/build/blob/master/packages/cache-utils/README.md) to cache `.next/cache` between builds, to speed up Next.js builds.

An existing plugin is already doing it ([source code](https://github.com/pizzafox/netlify-cache-nextjs/blob/master/src/index.ts)). Since that plugin allows users to customize the path to `.next/cache/`, it could still be useful for the few users who need that. @lindsaylevine Do you think using a custom file path for `.next/` is common?

Without that case in mind, adding this would probably look like this:

```js
const CACHE_DIR = '.next/cache/'
const BUILD_MANIFEST = '.next/build-manifest.json'

module.exports = {
	async onPreBuild({ utils }) {
		if (await utils.cache.restore(CACHE_DIR)) {
			console.log('Next.js cache restored.')
		} else {
			console.log('No Next.js cache to restore')
		}
	},
	async onPostBuild({ utils }) {
		if (await utils.cache.save(CACHE_DIR, { digests: [BUILD_MANIFEST] })) {
			console.log('Next.js cache saved.')
		} else {
			console.log('No Next.js cache to save.')
		}
	}
}
```

What do you think?

**Comment by lindsaylevine** [comment]
yes this would be an excellent addition after everything else is in place!!
