### ISSUE TITLE
Configure where onPreBuild runs

### ISSUE THREAD

**Issue by glitteringkatie** [netlify/netlify-plugin-nextjs#633]
**Is your feature request related to a problem? Please describe.**
Hi! I have a weird set up, to avoid confusion with an entire essay, here's a picture to look at while I explain my issue!

![image](https://user-images.githubusercontent.com/5943972/131753021-8e28d560-545a-4ba7-bfb7-dfa05ae16b70.png)

So basically I have a monorepo with a content directory and a documentation engine directory that is based off of next. I originally built them side by side but now I'm encouraging the mitosis so we can have the documentation engine as something that is open sourced and stand alone. I'm in an in between state, so hence the weird set up.

Here's the situation (illustrated in the flowchart above):

1. As to not break current folks' workflows, `yarn build` exists at the root of the project, calls the content dir's yarn build which calls a script that calls the docs-engine's yarn build with some configs passed in.
2. Great, when I build locally everything is happy! Including some process.cwd() usages because the cwd is the docs engine!

Here's the problem. So my netlify build settings uses the project root as the 'base directory', `yarn build` for the 'build command', and docs-engine/out for the publish directory. Should work right? Well I don't actually _know_ because `onPreBuild` from this package fails! Guess why? process.cwd() is from the project base, not my engine base. So trying to `scandir` an expected file in an expected place fails. (Note: this is a script that next.config.js is calling to make sure all of my content is in the right place that next.js is expecting)

**Describe the solution you'd like**
💫 Without fully understanding what `onPreBuild` does, I wish that I could tell it where to run from or what to return whenever process.cwd() gets called!

**Describe alternatives you've considered**
Honestly we're in an inbetween state and we're also doing jenkins builds--right now we're using netlify (where we started) to tide us over until we get PR previews working in jenkins. So the alternative is to just make PR previews work in our jenkins build and fully migrate off of netlify. This is clearly the easiest solution for the sake of your project! But we hadn't planned on converting this soon & figured I should pipe up since you have a bit on [monorepos](https://github.com/netlify/netlify-plugin-nextjs/blob/92e099015ce4d95c2817d95d35d0b828ee463be4/docs/monorepos.md).

**Additional context**
I also tried using the content dir as the base directory and `..` out of it and into the engine's /out directory but 1. `..` isn't supported and 2. that wouldn't avoid this problem.

cc @chandlerprall

**Comment by lindsaylevine** [comment]
@glitteringkatie can you share the exact error trace with me? and/or deploy/build logs?

**Comment by glitteringkatie** [comment]
```
3:55:53 PM: ────────────────────────────────────────────────────────────────
3:55:53 PM:   Plugin "@netlify/plugin-nextjs" internal error                
3:55:53 PM: ────────────────────────────────────────────────────────────────
3:55:53 PM: ​
3:55:53 PM:   Error message
3:55:53 PM:   UnhandledRejection: a promise was rejected but not handled: Error: ENOENT: no such file or directory, scandir '/opt/build/repo/generated/content'
3:55:53 PM: ​
3:55:53 PM:   Plugin details
3:55:53 PM:   Package:        @netlify/plugin-nextjs
3:55:53 PM:   Version:        3.9.0
3:55:53 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
3:55:53 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
3:55:53 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
3:55:53 PM: ​
3:55:53 PM:   Error location
3:55:53 PM:   In "onPreBuild" event in "@netlify/plugin-nextjs" from Netlify app
3:55:53 PM:       at Object.readdirSync (fs.js:872:3)
3:55:53 PM:       at getFilesByRegex (/opt/build/repo/docsmobile/scripts/script-helpers.js:29:25)
3:55:53 PM:       at getMdxFiles (/opt/build/repo/docsmobile/scripts/script-helpers.js:50:34)
3:55:53 PM:       at createRegistry (/opt/build/repo/docsmobile/scripts/register_docs.js:17:20)
3:55:53 PM:       at Object.<anonymous> (/opt/build/repo/docsmobile/next.config.js:42:1)
3:55:53 PM:       at Module._compile (internal/modules/cjs/loader.js:1133:30)
3:55:53 PM:       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
3:55:53 PM:       at Module.load (internal/modules/cjs/loader.js:977:32)
3:55:53 PM:       at Function.Module._load (internal/modules/cjs/loader.js:877:14)
3:55:53 PM:       at Module.require (internal/modules/cjs/loader.js:1019:19)
3:55:53 PM: ​
3:55:53 PM:   Error properties
3:55:53 PM:   {
3:55:53 PM:     errno: -2,
3:55:53 PM:     syscall: 'scandir',
3:55:53 PM:     code: 'ENOENT',
3:55:53 PM:     path: '/opt/build/repo/generated/content'
3:55:53 PM:   }
3:55:53 PM: ​
3:55:53 PM:   Resolved config
3:55:53 PM:   build:
3:55:53 PM:     command: yarn build
3:55:53 PM:     commandOrigin: ui
3:55:53 PM:     environment:
3:55:53 PM:       - GITHUB_TOKEN
3:55:53 PM:       - REVIEW_ID
3:55:53 PM:     publish: /opt/build/repo/docsmobile/out
3:55:53 PM:     publishOrigin: ui
3:55:53 PM:   plugins:
3:55:53 PM:     - inputs: {}
3:55:53 PM:       origin: ui
3:55:53 PM:       package: '@netlify/plugin-nextjs'
```

docsmobile = docs-engine in my description above. Issue: `'/opt/build/repo/generated/content'` is being derived from process.cwd() where in the build process.cwd() = `/opt/build/repo/docsmobile/` but during onPreBuild step it is `/opt/build/repo` so it can't find /generated/content because that exists _inside_ the docsmobile directory.

Additional thought: even just having an environment variable like NODE_ENV=NETLIFY_PRE_BUILD so I can do a reasonable hack around it and point at the right repo would get me around this.

**Comment by lindsaylevine** [comment]
@glitteringkatie in which directory does your next.config.js exist?

**Comment by glitteringkatie** [comment]
next.config.js is in the docsmobile (docs-engine) directory

**Comment by lindsaylevine** [comment]
@glitteringkatie hm. you could try to use patch-package to modify this function https://github.com/netlify/netlify-plugin-nextjs/blob/main/helpers/getNextRoot.js to look for your config/site root in the right place. right now i think it's not finding it in process.cwd() per your descriptions.. though if it doesn't find it there, it should be setting it to your publish dir (which you said is docs-engine/out), and the trace doesnt seem to reflect that 🤔  not sure. my recommendation for you (without giving me access to your src): try to run your build with the plugin via the CLI (if you aren't already). install @netlify/plugin-nextjs into your project (npm install --save @netlify/plugin-nextjs). play with the plugin src locally in your node_modules (specifically getNextRoot and getNextConfig helpers) to see if you can get process.cwd() where you need it to be. the other recommendation would be to do some sort of env check (kindof like you suggested) representing the netlify build env and conditionally set your path to whatever that way. for the record: i know your build is stopping at onPreBuild right now, but i don't think it's specific to that step -- as you can see here https://github.com/netlify/netlify-plugin-nextjs/blob/main/index.js#L100 we look for nextRoot at multiple stages of the plugin -- so i don't think a PRE_BUILD-specific enviro var would be accurate.

**Comment by glitteringkatie** [comment]
Okay! So locally I did what you suggested and found that getNextRoot is definitely working properly. But it still doesn't seem like it `cd`s into the next root dir like I'd want for my set up since process.cwd() remains the project root. I managed to skip past the onPreBuild just fine by wrapping the line in next.config.js that called `process.cwd()` in an `if` to make sure we only ran it if we were in the next root. It bypassed onPreBuild perfectly but then I got this error:

```
1:45:40 PM: info  - Using external babel configuration from /opt/build/repo/docsmobile/.babelrc
1:46:47 PM: Failed to compile.
1:46:47 PM: 
1:46:47 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '/opt/build/repo/node_modules/jsdom/lib/jsdom'
1:46:47 PM: > Build error occurred
1:46:47 PM: Error: > Build failed because of webpack errors
1:46:47 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:15:924
1:46:47 PM:     at runMicrotasks (<anonymous>)
1:46:47 PM:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
1:46:47 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
1:46:47 PM: error Command failed with exit code 1.
```

At this point I've been trying to force this to work for so long that I decided to cut my losses, but wanted to give you an update on what worked, what didn't, and where it got me in the end.

**Comment by lindsaylevine** [comment]
@glitteringkatie hey, thanks for the update. not sure if you meant you skipped onPreBuild altogether, but there _are_ necessary steps taken in onPreBuild to ensure a smooth build. skipping it may have yielded your specific module not found error.

we've put in extensive effort to support several common monorepo setups, but it's difficult for our plugin to predict and accommodate unique build strategies like yours where you `cd` multiple times up and down throughout a monorepo and depend on cwd in your src/config. tough to say without really seeing and fully understanding your setup and what might have made it work. all that said, we really appreciate you trying to figure it out and sharing your findings. we're working on a plugin rewrite now so we'll do our best to keep this kind of approach in mind.

**Comment by glitteringkatie** [comment]
I didn't skip onPreBuild altogether, just figured out a way to avoid my process.cwd()s during onPreBuild to allow it to pass just fine.

Thanks for the responses! Yeah I understand the `cd` multiple times being a weird thing to try to work around when people can do whatever they want for sure. Looking forward to see what the rewrite has in store!
