### ISSUE TITLE
Next.js website with Netlify Forms is not deploying

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/netlify-plugin-nextjs#634]
**Describe the bug:**

Next.JS website with a form fails to deploy. The site builds perfectly, but in the deploying phase, the log states:

```
Post processing - HTML
```

...5 times and the build fails. Post processing is completely off. Upon further investigation it was found that Netlify Forms is causing problems. This is the behaviour I could notice:

* Deploy fails without any change in default config.
* Deploy succeeds if you turn off form detection.
* Deploy succeeds if you remove `data-netlify=true` from the form in the TypeScript file, but keep form detection on.
* Deploy fails with a setup similar as the previous point, but you add a static HTML version of the form with the required attribute in the `public` folder.

**To Reproduce:**

Steps to reproduce the behaviour:

1. Clone this repo: https://github.com/Hrishikesh-K/reapertips-develop.
2. Try the various combinations of settings as mentioned above.

**Expected behaviour:**

The website should deploy fine regardless of the form.

**Versions:**

- Next.js: 11.1.0
- plugin (if installed at fixed version): N/A - pulled latest automatically (3.8.0 and 3.9.0 tested at the time of writing)

**Additional context:**

A customer reported the problem: https://answers.netlify.com/t/next-js-deployment-failed/43308/

**Comment by ingride** [comment]
The specific customer fail (https://app.netlify.com/sites/reapertips/deploys/612f8b60e0e2cf00077e61f0) seems toreport an incorrect form

```
</form>: unexpected 's' after '[:equal, "'No, it'"]' worker=Deploy::ProcessWorker job_id=d619bb595919662f60e100c6 batch_id=nil queue_name=deploy_process process_id=8 sidekiq=true thread_id=m3uc deploy_id=612f8b60e0e2cf00077e61f0 site_id=4c5161e1-9be9-43eb-9d80-9df2ec8d126c site_subdomain=reapertips account_id=612a71aa1630d0e1fb8a5998 logtype=processing reseller_id=53ce9ee971f1c34344000001
```

[logs](https://cloud.us.humio.com/netlify-us-production/search?query=%24bb%28%29%20%7C%20%22612f8b60e0e2cf00077e61f0%22%20%7C%20processing&live=false&start=1630500759618&end=1630509336425&fullscreen=false&widgetType=list-view&columns=%40rawstring%3A%3Aauto&newestAtBottom=true&showOnlyFirstLine=false)

**Comment by DaveKeehl** [comment]
I can confirm I got the website to deploy successfully 's' from the radio value. It's a bit weird however that the form is reported to be incorrect for such a small thing.

**Comment by Hrishikesh-K** [comment]
To conclude, **this is not an error with the plugin**. So, this is actually an incorrect repo to file this issue, and it might be moved in the future.

---

About the actual issue:

While yes, there could have been better info about the logs, I believe you should refrain from using `'` like characters in HTML attributes, because it's supposed to be a separator for an attribute.

But, glad to know the problem is now solved! Feel free to open another thread in the forums if you've any more questions.
