### ISSUE TITLE
Potential improvement of redirects

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#64]
One of our Netlify Build plugins generates a `_redirects` file based on the `.next/routes-manifest.json`. In particular, it uses the `dynamicRoutes` property in that file and converts those to lines appended to the `_redirects` file.

[Link to source code](https://github.com/Brikl/opensource/blob/master/libs/netlify-plugin-next-dynamic/src/index.ts)

`next-on-netlify` also includes some logic to convert Next.js redirects to Netlify. Is there anything useful in that plugin which could be added to `next-on-netlify`?

Either way, we should also consider removing that plugin from our list of plugins if `@netlify/plugin-nextjs` covers the same use cases.

@lindsaylevine

**Comment by lindsaylevine** [comment]
hmm. that regex could maybe be useful but otherwise/overall what we have is much more intricate than this. yeah we should definitely remove it.
