### ISSUE TITLE
I can't install plugin Essential Next.js in all my repositories.

### ISSUE THREAD

**Issue by jacopobonomi** [netlify/netlify-plugin-nextjs#643]
**Describe the bug**
I can't install plugin from Netlify GUI.

**To Reproduce**
1. Go to dashboard of Netlify
2. Click on plugins
3. Search for Essential Next.js. 
4. Click on install
5. Choose my repository build in Nextjs.
6. Modal show me "Error while installing the plugin.Please try again, but if the problem persists, feel free to contact us.", without any log.

How can i fix?

**Comment by lindsaylevine** [comment]
@jacopobonomi hello! sorry you're running into trouble! a few things:

1. you shouldn't need to manually install the plugin on a new next.js site on netlify. it should automatically install for you.
2. can you take a screenshot or multiple screenshots walking us through what you're doing? we appreciate the written steps you provided but i'm not able to reproduce this on our end.
3. can you also provide us the name of your site and/or a link to one of your deploy logs?

thank you!

**Comment by akshaymohite** [comment]
> you shouldn't need to manually install the plugin on a new next.js site on netlify. it should automatically install for you.

I can confirm that there is no need to install any plugin.
I tried deploying and nextjs site is working perfectly fine for me on Netlify.

---

Here's what I think is happening (based on my experience):

- People are referring official blog post on [How to Deploy Next.js Sites to Netlify](https://www.netlify.com/blog/2020/11/30/how-to-deploy-next.js-sites-to-netlify/)
- The article suggests to **Install the Next on Netlify plugin** (one-click install) with the [link](https://app.netlify.com/plugins/@netlify/plugin-nextjs/install?utm_source=blog&utm_medium=next-on-netlify-jl&utm_campaign=devex) to plugin.
- People are trying to install the plugin which (API request) gives out following exception
 `{"errors":{"plugins":["is invalid"]}}`

@lindsaylevine hope this information is helpful in taking this further.

**Comment by lindsaylevine** [comment]
@akshaymohite hello! i shared this feedback internally, thank you so much!
