### ISSUE TITLE
Next Image not working in production on Netlify

### ISSUE THREAD

**Issue by adikari** [netlify/netlify-plugin-nextjs#655]
I have deployed my nextjs site to Netlify however I am getting issues with the images. For some reason the images 404 on production but work on development. I have installed the plugin via Netlify UI.

Here is the rendered image tag on the browser on production:

```
<img alt="logo" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fadikari%2Fimage%2Fupload%2Fq_auto%2Cf_auto%2Fmonebag%2Flogo-small_uncinj&amp;w=64&amp;q=75" decoding="async" data-nimg="true" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fadikari%2Fimage%2Fupload%2Fq_auto%2Cf_auto%2Fmonebag%2Flogo-small_uncinj&amp;w=32&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fadikari%2Fimage%2Fupload%2Fq_auto%2Cf_auto%2Fmonebag%2Flogo-small_uncinj&amp;w=64&amp;q=75 2x">
```

I have configured my nextjs to work with cloudinary appropriately. Image section of netlify config looks as follows:

```
target: 'experimental-serverless-trace',
images: {
   domains: ['res.cloudinary.com']
}
```

When I check the logs on Netlify next image function, I see an error related to `sharp`

```
11:57:27 AM 2021-09-14T01:57:27.379Z	undefined	ERROR	
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/task/node_modules/sharp/lib/sharp.js
- /var/task/node_modules/sharp/lib/constructor.js
- /var/task/node_modules/sharp/lib/index.js
- /var/task/.netlify/functions-internal/next_image/next_image.js
- /var/task/next_image.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
11:57:27 AM 2021-09-14T01:57:27.669Z	undefined	ERROR	
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/task/node_modules/sharp/lib/sharp.js
- /var/task/node_modules/sharp/lib/constructor.js
- /var/task/node_modules/sharp/lib/index.js
- /var/task/.netlify/functions-internal/next_image/next_image.js
- /var/task/next_image.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
11:57:27 AM 066b82c8 Duration: 222.57 ms	Memory Usage: 17 MB
11:57:27 AM RequestId: 066b82c8-e006-4177-93d1-528ac8d95ac5 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by lindsaylevine** [comment]
@adikari do you have `sharp` included in `external_node_modules` in your netlify.toml? if not, can you add it per https://docs.netlify.com/configure-builds/file-based-configuration/#functions? i.e.

```
[functions]
  node_bundler = "esbuild"
  external_node_modules = [ "@ampproject/toolbox-optimizer", "sharp"]
```

**Comment by adikari** [comment]
Resolved this issue. Posting my resolution in case someone else runs into the similar situation.

Apparently, in order to use the cloudinary loader, the `loader` option must be specified alongside the domains. Otherwise, it will just use the default loader. The updated nextjs config looks as following:

```
images: {
   loader: 'cloudinary',
   domains: ['res.cloudinary.com'],
  path: 'https://res.cloudinary.com/<cloudinary-id>/image/upload'
}
```

Then when using the image, relative paths must be used:

```
<Image alt="some image" width="30" height="30" src="/relative/path/to/image/on/cloudinary" />
```

The error I was getting was related to sharp not being installed. The default loader seems to use `sharp` in production. By default its available in Vercel so there is no need to be installed. However, its not available in Netlify which is where I recently moved my site. To use the default loader `sharp` needs to be installed as npm dependency.

**Comment by adikari** [comment]
> @adikari do you have `sharp` included in `external_node_modules` in your netlify.toml? if not, can you add it per https://docs.netlify.com/configure-builds/file-based-configuration/#functions? i.e.
> 
> ```
> [functions]
>   node_bundler = "esbuild"
>   external_node_modules = [ "@ampproject/toolbox-optimizer", "sharp"]
> ```

Thanks for suggesting. Apparently, I need to specify `loader: cloudinary` in next config and use relative paths. See my other comment.
