### ISSUE TITLE
Netlify Deploy fails on next build due to a webpack error

### ISSUE THREAD

**Issue by nrodriguez** [netlify/netlify-plugin-nextjs#656]
**Describe the bug**
My deploy seems to be failing on `next build` while locally I can't seem to replicate the issue

```
11:45:38 PM: 
11:45:38 PM: ./node_modules/clone-deep/utils.js
11:45:38 PM: Cannot statically analyse 'require(…, …)' in line 11
11:45:38 PM: > Build error occurred
11:45:38 PM: Error: > Build failed because of webpack errors
11:45:38 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:397:19
11:45:38 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
11:45:38 PM:     at async Object.build [as default] (/opt/build/repo/node_modules/next/dist/build/index.js:77:25)
```

Netlify Deploy Log: https://app.netlify.com/sites/looter-io/deploys/613ac93454eb7c000838fdba?utm_source=github&utm_campaign=bot_dl

Code Being Deployed: https://github.com/nrodriguez/looter-io/pull/16

Relevant Netlify Forum Post: https://answers.netlify.com/t/next-js-deploy-fails-on-webpack-build/43921/2

Next.js Version: `Next.js v11.1.2`

**Comment by lindsaylevine** [comment]
@nrodriguez hey! this seems to be an issue with our plugin defaulting to target: serverless. can you set the `target` property in your next.config.js to `experimental-serverless-trace`?

**Comment by nrodriguez** [comment]
> @nrodriguez hey! this seems to be an issue with our plugin defaulting to target: serverless. can you set the `target` property in your next.config.js to `experimental-serverless-trace`?

Hi @lindsaylevine , I've added the change as well as changing my plugin-nextjs to use the latest version (v3.9.0). It worked in passing the `next build` step but I do see an error showing up at the end

Build Log: **https://app.netlify.com/sites/looter-io/deploys/614213ac22a2320007e8d262**

```
11:42:51 AM: ❯ Uploaded redirects
11:42:51 AM:   # Next-on-Netlify Redirects
11:42:51 AM:   /  /.netlify/functions/next_index  200
11:42:51 AM:   /_next/data/build/index.json  /.netlify/functions/next_index  200
11:42:51 AM:   /api/search-results  /.netlify/functions/next_api_searchresults  200
11:42:51 AM:   /_next/image*  url=:url w=:width q=:quality  /nextimg/:url/:width/:quality  301!
11:42:51 AM:   /api/scrape/:marketplace  /.netlify/functions/next_api_scrape_marketplace  200
11:42:51 AM: Starting to deploy site from 'out'
11:42:52 AM: Creating deploy tree 
11:42:53 AM: Creating deploy upload records
11:42:53 AM: 2 new files to upload
11:42:53 AM: 3 new functions to upload
11:43:02 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:05 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:06 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:09 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:12 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:16 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:22 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:31 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:38 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:43:55 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:44:14 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:44:33 AM: Request must be smaller than 69905067 bytes for the CreateFunction operation
11:44:33 AM: Failed to upload file: next_api_scrape_marketplace
11:44:33 AM:   /nextimg/*  /.netlify/functions/next_image  200
```

Is this related to the plugin or is this more of a netlify itself issue?

**Comment by lindsaylevine** [comment]
@nrodriguez it's a symptom of experimental-serverless-trace. if you add `node_bundler` as `esbuild` in your netlify.toml it should fix this issue. see https://docs.netlify.com/configure-builds/file-based-configuration/#functions

**Comment by nrodriguez** [comment]
> @nrodriguez it's a symptom of experimental-serverless-trace. if you add `node_bundler` as `esbuild` in your netlify.toml it should fix this issue. see https://docs.netlify.com/configure-builds/file-based-configuration/#functions

I've added the proposed value to my netlify.toml file but still seem to see an error


https://app.netlify.com/sites/looter-io/deploys/61422216b668ff00070996db

**Comment by nrodriguez** [comment]
I'm also using puppeteer and puppeteer-extra, is this any cause of the issues as well?

**Comment by lindsaylevine** [comment]
@nrodriguez hey - i pinged people earlier today internally at netlify who specialize in functions bundling. hopefully they can give us some more insight tomorrow!

**Comment by nrodriguez** [comment]
> @nrodriguez hey - i pinged people earlier today internally at netlify who specialize in functions bundling. hopefully they can give us some more insight tomorrow!

Awesome to hear, thanks for the follow up!

**Comment by ascorbic** [comment]
The problem with puppeteer is that it's probably bundling the whole of chromium in the function. Do you need it at runtime? You can look in `.netlify/functions/next_index.zip` and see what's in there that's making it so large, but my guess is that puppeteer is the culprit. If you don't need it, try adding `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1` to your env vars in the site UI

**Comment by ascorbic** [comment]
Ah yes sorry. Download the CLI and run `netlify build`

**Comment by nrodriguez** [comment]
@ascorbic  I've update my code to use puppeteer-core and import the `chromium-aws-lambda` package per the advice of (https://github.com/netlify-labs/netlify-functions-headless-chrome) but it still failed. 

I tried even adding that env variable you suggested but it still fails on the builds.

I built it locally but unfortunately I can't see in the zip the size of the internal components

**Comment by ascorbic** [comment]
Try `zipinfo .netlify/functions/next_index.zip` if you're on something unixy

**Comment by nrodriguez** [comment]
@ascorbic After moving to try to use the suggested code in the netlify-labs repo (also mentioned here: https://bitsofco.de/how-to-use-puppeteer-in-a-netlify-aws-lambda-function/), I see that chromium is by far the largest from the chrome-aws-lambda package. 

However, I do need to use puppeteer to scrape a page at runtime. Is there any other ways to get around netlify generating that function?

**Comment by nrodriguez** [comment]
I just found https://github.com/soofka/netlify-plugin-chromium, would this be a suitable replacement for using chromium in netlify at runtime?

**Comment by ascorbic** [comment]
Good fix! That does sound like a different error. It's almost always two copies of React. Try `npm ls react` or `yarn why react`

**Comment by nrodriguez** [comment]
@ascorbic  Hm, when I run it locally (where I don't see the error occur) I see

```
λ JustNeph-Desktop looter-io → λ git feat/add-poshmark* → npm ls react
looter-io@ /home/Projects/looter-io
├─┬ @heroicons/react@1.0.4
│ └── react@17.0.2 deduped
├─┬ @testing-library/react@11.2.7
│ └── react@17.0.2 deduped
├─┬ next@11.1.2
│ ├─┬ @next/react-dev-overlay@11.1.2
│ │ └── react@17.0.2 deduped
│ ├── react@17.0.2 deduped
│ ├─┬ styled-jsx@4.0.1
│ │ └── react@17.0.2 deduped
│ └─┬ use-subscription@1.5.1
│   └── react@17.0.2 deduped
├─┬ react-dom@17.0.2
│ └── react@17.0.2 deduped
├─┬ react-infinite-scroll-component@6.1.0
│ └── react@17.0.2 deduped
├── react@17.0.2
└─┬ swr@1.0.1
  └── react@17.0.2 deduped
  ````
  ```
  λ JustNeph-Desktop looter-io → λ git feat/add-poshmark* → yarn why react
yarn why v1.22.11
[1/4] Why do we have the module "react"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "react@17.0.2"
info Has been hoisted to "react"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "356KB"
info Disk size with unique dependencies: "404KB"
info Disk size with transitive dependencies: "432KB"
info Number of shared dependencies: 3
Done in 0.44s.
```

And when I run it in netlify (which is where I see that error occur):

```
9:46:18 AM: $ NODE_OPTIONS=--trace-deprecation yarn build
9:46:19 AM: yarn run v1.22.10
9:46:19 AM: $ npm ls react && yarn why react && next build
9:46:22 AM: /opt/build/repo
9:46:22 AM: └── react@17.0.2
9:46:22 AM: [1/4] Why do we have the module "react"...?
9:46:22 AM: [2/4] Initialising dependency graph...
9:46:22 AM: [3/4] Finding dependency...
9:46:22 AM: [4/4] Calculating file sizes...
9:46:22 AM: info
9:46:22 AM: => Found "react@17.0.2"
9:46:22 AM: info Has been hoisted to "react"
9:46:22 AM: info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "356KB"
9:46:22 AM: info Disk size with unique dependencies: "404KB"
9:46:22 AM: info Disk size with transitive dependencies: "432KB"
9:46:22 AM: info Number of shared dependencies: 3
```

**Comment by nrodriguez** [comment]
I've also tried adding a linter rule for the hooks (https://www.npmjs.com/package/eslint-plugin-react-hooks) but I really don't think this is a locally occurring issue as the linter doesn't show any errors. 

It seems like this issue is solely occuring on netlify builds.

**Comment by ascorbic** [comment]
Have you tried a clear cache and deploy?

**Comment by nrodriguez** [comment]
> Have you tried a clear cache and deploy?

Yup, a couple different times. The build doesn't show me any glaring issues: https://app.netlify.com/sites/looter-io/deploys/6149e0ba0c6a0f00b97fb364

The preview still fails unfortunately: https://6149e0ba0c6a0f00b97fb364--looter-io.netlify.app/

**Comment by lindsaylevine** [comment]
@nrodriguez hey! i know its been a few weeks, we apologize for the delay and appreciate your patience!! we JUST released the beta of our full plugin rewrite. we anticipate it will fix your issue(s). would you be open to testing it out? instructions [inside our discussion here](https://github.com/netlify/netlify-plugin-nextjs/discussions/706). let us know! 🙏

**Comment by ascorbic** [comment]
CLosing because it doesn't apply with the new plugin. If you can upgrade the plugin to 4.0.0 or later, and if you still have trouble please open a new ticket. Thanks!
