### ISSUE TITLE
`basePath` not working with images, behavior seems off for CSS/JS bundles too.

### ISSUE THREAD

**Issue by localjo** [netlify/netlify-plugin-nextjs#671]
I'm trying to deploy a Nextjs app with a `basePath`. Things work locally. The site, all images, and all CSS/JS bundles are served from the `basePath` I have set in `next.config.js`. But on Netlify, the site is served from the `basePath`, and all of the src/href attributes still include the `basePath`, but those URLs get rewritten in unexpected ways and some return 404s.

## Static assets (images, CSS, JS bundles)

URLs like `https://my-app-name.netlify.app/my-base-path/_next/static/media/background.{hash}.jpg`
Gets redirected to `https://my-app-name.netlify.app/_next/static/media/background.{hash}.jpg`
The basePath gets removed but the asset successfully loads.

This seems to be problematic when reverse proxying another domain to `https://my-app-name.netlify.app/my-base-path/_next/static/media/background.{hash}.jpg` which then returns a 404. Something seems to get lost when redirecting the proxied URL.

## Next image component with internal or external images

The next-image component generates image tags with hrefs like this:
`https://my-app-name.netlify.app/my-base-path/_next/image?url=%2Fmy-base-path%2Fimages%2Flogo.png&w=384&q=75`

But that gets rewritten to (base path removed):
`https://my-app-name.netlify.app/_next/image?url=%2Fmy-base-path%2Fimages%2Flogo.png&w=300&q=75`

**To Reproduce**
Deploy a Nextjs app that uses the next-image component with the following config:
```
// next.config.js
module.exports = {
  basePath: '/my-base-path',
};
```

```
// index.jsx
...
<Image
  src="/my-base-path/images/logo.png"
  width={300}
  height={25}
/>
...
```

```
# netlify.toml
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = "out"
```

**Expected behavior**

URLs should not have the `basePath` removed, and should return the correct assets, not a 404.

**Versions**
- Next.js: 11.1.2
- plugin (if installed at fixed version): Installed automatically by Netlify

**Comment by ascorbic** [comment]
Fixed in v4
