### ISSUE TITLE
[Bug]: netlify-plugin-nextjs@3.9.2 is running into timeouts while generating images

### ISSUE THREAD

**Issue by p0wl** [netlify/netlify-plugin-nextjs#743]
### Steps to reproduce

Hey, we saw a lot of timeouts (image processing taking longer than 10s) when running netlify-plugin-nextjs@3.9.2, which got installed as we were using `"@netlify/plugin-nextjs": "^3.9.0",` in our package.json, which lead to 3.9.2 being installed in netlify.

it seems like the 3.9.2 got removed / never existed in GitHub, but it is still available in npm: https://www.npmjs.com/package/@netlify/plugin-nextjs/v/3.9.2

Is 3.9.2 the latest, stable version? Downgrading (& pinning) to 3.9.1 did solve the timeout issues for us.

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Mac OS

**Comment by ascorbic** [comment]
Hi. Could you try this again with version 4.0.0 of the plugin or later? It uses a completely new image server, so this may no longer apply.

**Comment by eostrom** [comment]
I'm seeing a lot of timeouts after upgrading to 4.1.0 – primarily for one large "hero" image, at desktop resolution. (The URL has `w=3840` in it, so I guess what it's failing to render is a 3840x2421 image.)

This might be a completely different issue, given that the original post was for 3.9.2. (In fact, downgrading to 3.9.2 seems to have *solved* my problem, for now.) Just offering it as a data point.

**Comment by ascorbic** [comment]
Hi @eostrom 
What's the size of the source image? Is it a local or remote image?

**Comment by eostrom** [comment]
It was a local image, a 1.8M uncompressed PNG. Taking the hint, I just replaced it with a 431K JPEG (on v4.0.0), and it's working now.

Thanks for asking the right question! If image size is an expected gotcha, it might be worth mentioning in the README.

**Comment by trankhacvy** [comment]
@ascorbic I got timeout error too. I download the deployed source code from netlify and it's about 58mb (I have two video for background). Is this the reason of the timeout error?
