### ISSUE TITLE
[Bug]: Images in public files don't load while in preview mode

### ISSUE THREAD

**Issue by Christopotamus** [netlify/netlify-plugin-nextjs#753]
### Steps to reproduce

I've created a project with create-next-app that simply includes an image on the page as well as the /api/ preview files taken from the demo project of this repo.

To see what's happening:

1. https://naughty-borg-b1bb33.netlify.app to see the index page which includes an img tag that loads an image from the public directory
2. https://naughty-borg-b1bb33.netlify.app/api/enterPreview to enter preview mode 
3. Go back here https://naughty-borg-b1bb33.netlify.app to see that the image no longer loads

I'm not quite sure why this is happening yet, but maybe the route handling for preview mode isn't handling images in the public folder? 

This only seems to affect preview mode as far as I can tell. I've tested in another repository and it seems to affect any file located in the public directory.

### A link to a reproduction repository

https://github.com/Christopotamus/next-netlify-preview-images

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

**Comment by ascorbic** [comment]
Thanks for the report. I've isolated this, and it's related to the redirects we add for preview mode to ensure it uses SSR. It's overriding the static files. We need to be more specific with the redirects to avoid this.

**Comment by Christopotamus** [comment]
Sorry to resurrect this, but this looks like this is broken again with the latest release (rc.0) 

I've updated my repo above and following the same steps shows the same behavior

I looked through https://github.com/netlify/netlify-plugin-nextjs/blob/release-v4.0.0/src/helpers/redirects.ts which looks like where the issue would be, but don't know the codebase well enough to help out with a pull request yet
