### ISSUE TITLE
Netlify plugin nuxtjs for SSR

### ISSUE THREAD

**Issue by yangwao** [netlify/netlify-plugin-nextjs#759]
Hello, we would like to stay with Netlify -- [kodadot/nft-gallery](https://github.com/kodadot/nft-gallery) running over 10k visits and we've just finished rewriting to the Nuxt for various reasons and intent is to switch to SSR for faster speed loads. I've found only Vercel support SSR and I guess if we could fork this plugin -- **netlify-plugin-nextjs**  and accommodate it to work with Nuxt, do you think it would work?
cc @vikiival

**Comment by ascorbic** [comment]
Hi. If you use Nuxt 3, or Nitro Bridge, SSR should work out of the box, with no plugin required. See this post for details https://www.netlify.com/blog/2021/10/12/nuxt-3-is-live-in-public-beta-and-ready-to-deploy-on-netlify-today/

**Comment by vikiival** [comment]
What about Nuxt 2 ?

**Comment by ascorbic** [comment]
You can use Nitro Bridge
