### ISSUE TITLE
[Bug]: Next.js 12 Middleware not working

### ISSUE THREAD

**Issue by janakitti** [netlify/netlify-plugin-nextjs#760]
### Steps to reproduce

We were experimenting with the new Middleware feature introduced in Next.js 12. When running the app locally, everything works as expected. However, when we deploy to Netlify (using v4 of the Essential Next.js plugin), we get 404s on all URL paths. Even a simple Middleware function such as the following results in this issue:

```ts
// pages/_middleware.ts

export function middleware(req: NextRequest, ev: NextFetchEvent) {
  return new Response('Hello, world!');
}
```

### A link to a reproduction repository

https://github.com/janakitti/next-test/tree/middleware

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (netlify.toml)

### Your `netlify.toml` file

No `netlify.toml` file

### Relevant log output (or link to your logs)

[deploy_log.txt](https://github.com/netlify/netlify-plugin-nextjs/files/7464707/deploy_log.txt)

**Comment by ascorbic** [comment]
Hi. Sorry to hear you're having issues with this. Can you include a minimal reproduction so we can look into it?

**Comment by janakitti** [comment]
Here is the repo: https://github.com/janakitti/next-test/tree/middleware

And here is the deploy log: [deploy_log.txt](https://github.com/netlify/netlify-plugin-nextjs/files/7464707/deploy_log.txt)

**Comment by ascorbic** [comment]
Thank you. I'll look into it today

**Comment by leethree** [comment]
we are seeing the same issue. middleware is not running at all.

**Comment by ascorbic** [comment]
Hi. I have a fix for this which I will be releasing later today
