### ISSUE TITLE
[Bug]: `/api` routes remove the query parameters on the req object

### ISSUE THREAD

**Issue by koraysels** [netlify/netlify-plugin-nextjs#765]
### Steps to reproduce

use the latest beta.4 or beta.5 version of netlify-plugin-nextjs v4
and add a file called test.js in the pages/api with the following content:

```js
export default async function test(req, res) {
  res.status(200).json({query: req.query})
}

```

then deploy on netl;ify and test the route.. `/api/test?foo=pbar`

the result is 
```json
 {"query":{}}
``` 
and it shoud be 
```json
 {"query":{"foo":"pbar"}}
```

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (netlify.toml)

### What OS are you using?

Mac OS

### Your `netlify.toml` file

```shell
[build]
  command = "next build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

### other Relevant info: 

When i downgrade back to 3.9.2 it works again..

**Comment by ascorbic** [comment]
Hi. Can you share a reproduction? I've had a few people report this, but haven't been able to reproduce it. Could you also send me the full request? If you open the network panel in dev tools, right click on the request and choose "Copy as cURL", then share it?

**Comment by koraysels** [comment]
sure when i have time i'll try to set something up.. right now i lost alsmost a full day trying to figure out why my clients previews stopped working. ;)

**Comment by koraysels** [comment]
We reverted back to using v3.9.2.. now the initial load time is extremely slow.. but the preview function is working at least 😅

**Comment by ascorbic** [comment]
OK, glad it's working for you. If you do try again and reproduce the issue, please do send me the request details as it would be good to be able to fix this.
