### ISSUE TITLE
Support ES modules in `next.config.js`

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-nextjs#80]
ES modules are only supported in Node.js 12, and `import()` must be used instead of `require()`.
We currently use `require()` because we support Node 10.

https://github.com/netlify/netlify-plugin-nextjs/blob/59ee2bbb2ffb971e964a07245eaa478ba1c07cbd/package.json#L55

It seems like some users are trying to use ES modules in their `next.config.js`, which currently fails. 
Bugsnag errors [here](https://app.bugsnag.com/netlify/netlify-build/errors/5fd926901a0c860018ef58ad), [here](https://app.bugsnag.com/netlify/netlify-build/errors/5ff15295be2cb100174074df) and [there](https://app.bugsnag.com/netlify/netlify-build/errors/5fda5151d0f0a2001790dfe6).

This will be a growing problem in 3 months (April 2021) when Node 10 becomes officially unsupported.

**Comment by ascorbic** [comment]
This is an upstream issue: Next.js doesn't support it either. See https://github.com/vercel/next.js/issues/9607
This should no longer show up on BugSnag though, as it's a user build failure now.
