### ISSUE TITLE
[Bug]: netlify.toml redirect changes during build not picked up by the plugin

### ISSUE THREAD

**Issue by alvarl** [netlify/netlify-plugin-nextjs#810]
### Steps to reproduce

1. preprocess your netlify.toml file in your build phase, e.g. making substitutions in target URLs
2. trigger build, observe behaviour:
```
10:42:09 AM: $ ./preprocess_netlify_config.sh && yarn build # this outputs the updated netlify.toml, seen below
10:42:09 AM: [build]
10:42:09 AM: command = "./preprocess_netlify_config.sh && yarn build"
10:42:09 AM: publish = ".next"
10:42:09 AM: [[redirects]]
10:42:09 AM: from = "/blog/*"
10:42:09 AM: to = "https://blog.grunfin.com/blog/:splat"
10:42:09 AM: status = 200
10:42:09 AM: force = true
10:42:09 AM: headers = { X-From = "Netlify", X-Forwarded-Host = "www.grunfin.com", X-Forwarded-Proto = "https" }
10:42:09 AM: [[plugins]]
10:42:09 AM: package = "@netlify/plugin-nextjs"
```
No original `netlify.toml` contents in plugin-nextjs phase:
```
10:45:03 AM: ────────────────────────────────────────────────────────────────
10:45:03 AM: 3. @netlify/plugin-nextjs (onBuild event)
10:45:03 AM: ────────────────────────────────────────────────────────────────
10:45:03 AM: ​
10:45:03 AM: Netlify configuration property "redirects" value changed to [
10:45:03 AM: {
10:45:03 AM: from: '/blog/*',
10:45:03 AM: query: {},
10:45:03 AM: to: 'https://BLOG_HOST_PLACEHOLDER/blog/:splat',
10:45:03 AM: status: 200,
10:45:03 AM: force: true,
10:45:03 AM: conditions: {},
10:45:03 AM: headers: {
10:45:03 AM: 'X-From': 'Netlify',
10:45:03 AM: 'X-Forwarded-Host': 'WEB_HOST_PLACEHOLDER',
10:45:03 AM: 'X-Forwarded-Proto': 'https'
10:45:03 AM: }
10:45:03 AM: },
```

Works on 3.9.2

### Plugin version

4.0.0-beta.6

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

[build]
  command = "./preprocess_netlify_config.sh && yarn build"
  publish = ".next"

[[redirects]]
from = "/blog/*"
to = "https://BLOG_HOST_PLACEHOLDER/blog/:splat"
status = 200
force = true
headers = { X-From = "Netlify", X-Forwarded-Host = "WEB_HOST_PLACEHOLDER", X-Forwarded-Proto = "https" }

[[plugins]]
package = "@netlify/plugin-nextjs"

### Relevant log output (or link to your logs)

<details>
  <summary>Build logs</summary>
```
10:42:09 AM: $ ./preprocess_netlify_config.sh && yarn build
10:42:09 AM: [build]
10:42:09 AM: command = "./preprocess_netlify_config.sh && yarn build"
10:42:09 AM: publish = ".next"
10:42:09 AM: [[redirects]]
10:42:09 AM: from = "/blog/*"
10:42:09 AM: to = "https://blog.grunfin.com/blog/:splat"
10:42:09 AM: status = 200
10:42:09 AM: force = true
10:42:09 AM: headers = { X-From = "Netlify", X-Forwarded-Host = "www.grunfin.com", X-Forwarded-Proto = "https" }
10:42:09 AM: [[plugins]]
10:42:09 AM: package = "@netlify/plugin-nextjs"
...
10:45:03 AM: ────────────────────────────────────────────────────────────────
10:45:03 AM: 3. @netlify/plugin-nextjs (onBuild event)
10:45:03 AM: ────────────────────────────────────────────────────────────────
10:45:03 AM: ​
10:45:03 AM: Netlify configuration property "redirects" value changed to [
10:45:03 AM: {
10:45:03 AM: from: '/blog/*',
10:45:03 AM: query: {},
10:45:03 AM: to: 'https://BLOG_HOST_PLACEHOLDER/blog/:splat',
10:45:03 AM: status: 200,
10:45:03 AM: force: true,
10:45:03 AM: conditions: {},
10:45:03 AM: headers: {
10:45:03 AM: 'X-From': 'Netlify',
10:45:03 AM: 'X-Forwarded-Host': 'WEB_HOST_PLACEHOLDER',
10:45:03 AM: 'X-Forwarded-Proto': 'https'
10:45:03 AM: }
10:45:03 AM: },
```
</details>

**Comment by ascorbic** [comment]
Hi,
The reason this doesn't work is because the CLI processes the toml before starting the build plugin. The build plugin needs to run commands before the build starts, so cannot see changes that are made after that. The best way to handle this would be to create your own local build plugin that has an `onPreBuild` handler which mutates the config directly, rather than editing the toml. You don't need to publish the plugin: it can be in a folder in your project. See [the plugin docs](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/) for details.

**Comment by alvarl** [comment]
Thanks, will take note of that. 

However, above is not expected behaviour, given what https://docs.netlify.com/configure-builds/file-based-configuration/ says. Is there a plan to revisit that document and remove the workaround once 4.0.0 comes out of beta?

**Comment by ascorbic** [comment]
That's a good point, and I'll open an issue to reflect it.
