### ISSUE TITLE
[Bug]: Netlify doesn't use custom Next.js error page

### ISSUE THREAD

**Issue by rettgerst** [netlify/netlify-plugin-nextjs#828]
### Steps to reproduce

1. Create a Next.js custom error page in `pages/_error.tsx`
2. Deploy to Netlify
3. Open the [deployed site](https://condescending-brown-669e11.netlify.app/)
4. When an error occurs, Netlify returns a JSON-serialized error message as plaintext instead of the custom error page.

![image](https://user-images.githubusercontent.com/11684948/142899501-e8c6bcee-b6ee-451d-af4e-6aa5482282ac.png)

![image](https://user-images.githubusercontent.com/11684948/142899587-b523cb30-19f2-469b-b93d-16ce84492505.png)

You can clone the repro repository and run `npm run build && npm run start` to see the intended behavior - Next.js renders the custom error page.

### A link to a reproduction repository

https://github.com/rettgerst/netlify-error-repro

### Plugin version

3.9.2

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Relevant log output (or link to your logs)

https://app.netlify.com/sites/condescending-brown-669e11/deploys/619bbd24a20c2c2bb4419303

**Comment by ascorbic** [comment]
Hey. Can you confirm if this is still an issue in the release candidate? See the README for how to install version 4.

**Comment by rettgerst** [comment]
the release candidate works as expected, thank you! I also noticed that image loading is much faster than v3 as well.

**Comment by ascorbic** [comment]
Great! Thanks for checking
