### ISSUE TITLE
missing "jimp" dependency

### ISSUE THREAD

**Issue by jlengstorf** [netlify/netlify-plugin-nextjs#85]
related to #84, I think

`next-on-netlify@2.8.x` introduced image support, which relies on `jimp`. however, this plugin is set to `@2.7.2` and that is somehow causing the next image support to run, but `jimp` is not installed as a dependency

I don't know how or why, but wanted to track this here

**Comment by jjojo** [comment]
![image](https://user-images.githubusercontent.com/10955000/104851684-d09bc280-58f6-11eb-8a17-169ca793523f.png)
My builds started failing unexpectedly. It also finds a next_image.js function that I don't have anywhere...

**Comment by lindsaylevine** [comment]
@jjojo hey! so sorry for this. this is because of our initial next/image support and for some reason our internal logic won't find jimp despite it being dependencies of next-on-netlify and the plugin.

>Is there a way to lock plugin versions? because what I had did work. 

this is an excellent question and something we need to address.


to resolve your issue though - can you install `jimp` to your project as a temporary workaround until i can roll this back or fix? can keep you updated!

**Comment by lindsaylevine** [comment]
@jjojo actually i think you should be able to pin your plugin version by installing the plugin into your project at whatever version. this will also solve the jimp issue.

**Comment by lindsaylevine** [comment]
hey all - heads up that i reverted next/image support to avoid any more people seeing this jimp error until we can resolve it. please track here if you want to know when support is back! :) https://github.com/netlify/next-on-netlify/issues/143

**Comment by jjojo** [comment]
Thanks for the suggestions @lindsaylevine I'll look into it! I really liked the smooth deployment, and it is a great plugin! 
For now, though, I set up a custom deploy solution and uninstalled the plugin.
Since you rolled back I'll try reinstalling the plugin tonight :)

**Comment by lindsaylevine** [comment]
@jjojo totally understand! :) apologies again for the breaking changes!!! will be much more vigilant in the future especially as we transition to auto-installing this plugin for new next.js sites 👀 all feedback is welcome!
