### ISSUE TITLE
Feature: don't fail the build if the site doesn't match the requirements

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-plugin-nextjs#93]
The plugin currently fails the build if:
1. This site is not a `next` site
2. The site is a static HTML export Next.js site
3. The site has `next-on-netlify` installed
4. The site configures a target other than `serverless` or `experimental-serverless-trace`

Per https://github.com/netlify/pod-workflow/issues/121#issuecomment-763411132 I suggest to change it to only fail if it's not a `next` site.

For all other cases we can print a relevant message and do nothing.

**Comment by lindsaylevine** [comment]
thanks for opening this officially!! this has been on the dx internal board/on my radar for several weeks but it's good to have here as well!!! :)
