### ISSUE TITLE
[Bug]: Redirects outputting by `@netlify/plugin-nextjs` are not picked up in by Netlify

### ISSUE THREAD

**Issue by gavinhenderson** [netlify/netlify-plugin-nextjs#953]
### Steps to reproduce

1. Build a Next (12) site using the @netlify/plugin-nextjs beta plugin on Github Actions
2. See that it outputs that it has created all the required redirects
3. Run deploy from CLI in Github Action
4. See in the Netlify UI that there are no redirects attached to deploy

See building here https://github.com/AceCentre/acecentre.org.uk/blob/b93f1ae59ab29e3426203d9a03c7bc9308735655/.github/workflows/deploy.yml#L100

### A link to a reproduction repository

https://github.com/AceCentre/acecentre.org.uk

### Plugin version

4.0.0-rc.1

### More information about your build

- [X] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Linux

### Your `netlify.toml` file

```
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "/netlify-plugins/sitemap"

[[plugins]]
  package = "/netlify-plugins/expose-env-variables"

[[plugins]]
  package = "/netlify-plugins/output-config"

[build]
  command = "yarn build"
  publish = ".next"
```

### Relevant log output (or link to your logs)

You can see the full logs here: https://github.com/AceCentre/acecentre.org.uk/runs/4460478115?check_suite_focus=true

<details>
  <summary>Build logs</summary>
  
```
────────────────────────────────────────────────────────────────
  5. @netlify/plugin-nextjs (onBuild event)                     
────────────────────────────────────────────────────────────────
​
Moving static page files to serve from CDN...
Moved 856 files
Netlify configuration property "redirects" value changed to [
  {
    from: '/_next/image*',
    query: { url: ':url', w: ':width', q: ':quality' },
    to: '/_ipx/w_:width,q_:quality/:url',
    status: 301
  },
  { from: '/_ipx/*', to: '/.netlify/builders/_ipx', status: 200 },
  { from: '/cache/*', to: '/404.html', status: 404, force: true },
  { from: '/server/*', to: '/404.html', status: 404, force: true },
  { from: '/serverless/*', to: '/404.html', status: 404, force: true },
  { from: '/traces', to: '/404.html', status: 404, force: true },```

</details>

**Comment by ascorbic** [comment]
Hey. Rather than running separate build and deploy commands, can you try running `netlify deploy --build`?

**Comment by gavinhenderson** [comment]
Hey, @ascorbic thanks for the reply!

Running `netlify deploy --build` did the trick for me!

Maybe this caveat of running the build and deploy together should be called out in the docs because it wasn't previously required.

It's also worth noting that you can't pass build flags into the build command when you run `netlify deploy --build`. I was previously using the `--context` flag to set the build context. Although I figured out I can still set the `CONTEXT` env var which seems to work the same.

Seems like an issue with the CLI to allow plugins to mutate the config like that and only apply the new config when you build and deploy in the same command? Do you think its worth me raising an issue there?

Appreciate all your work on this plugin! Happy to submit PRs if you have an idea for a fix for this or just want me to add docs :)

**Comment by ascorbic** [comment]
Hi @gavinhenderson 
Thanks for the update. I've opened [an issue](https://github.com/netlify/cli/issues/3792) to handle this better. I'll keep this issue open for now so that others can see it, but it's something that needs fixing in the CLI and docs.

**Comment by kaskaz** [comment]
I got into this "trap" twice:
- first, when migrating from nextjs version 11 to 12 (and netlify/plugin-nextjs version from 3.4.2 to 4.1.1) in a old project;
- second, sometime after when starting a new project with nextjs + netlify/plugin-nextjs, adding a netlify.toml file with recommended settings.

I couldn't remember this trick the second time, it's very frustrating and time consuming.
Shouldn't it be documented in the docs until it gets fixed?

Your suggestion to fix the CLI is to have back the previous behavior? (Run _build_ and then _deploy_ isolated)
