### ISSUE TITLE
Error: Your next.config.js must set the "target" property to one of: serverless, experimental-serverless-trace for conditional target

### ISSUE THREAD

**Issue by amuttsch** [netlify/netlify-plugin-nextjs#97]
I'm using a conditional to determine if our next application will be compiled in `server` or `serverless` mode. The plugin, however, does not support this kind of config:

```
const isServerless = !!process.env['NEXT_SERVERLESS'];

module.exports = withOptimizedImages(
    withBundleAnalyzer(
        withSourceMaps({
            target: isEnvProduction && isServerless ? 'serverless' : 'server',
            poweredByHeader: false,
            ...
      })
    )
);
```

My `netlify.toml` looks like this:

```
[build]
    command   = "yarn run build:serverless"
    functions = "out_functions"
    publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

The `build:serverless` task sets the environment variable `NEXT_SERVERLESS`: 

```"build:serverless": "yarn run clean && NODE_ENV=production NEXT_SERVERLESS=true SOURCE_MAPS_ENABLED=false next build",```

A workaround is to `sed` the config in our CI pipeline before running `netlify build`:

```
sed -i "s/target: isEnvProduction && isServerless ? 'serverless' : 'server',/target: 'serverless',/g" next.config.js
```

**Comment by lindsaylevine** [comment]
@amuttsch hey! i've been thinking about this one and trying to come up with a clean, straightforward solution. in the meantime, some thoughts/questions:

1. do you use the CLI or the github CI to deploy or both?
2. if i'm understanding correctly, locally you want the config to be loaded as `server`? if so, can you help me better understand your specific reasoning for that? doesn't necessarily matter to me, just curious more than anything about your setup/workflow, and also i'm wondering if it's possible to maintain multiple next configs - aka one per environment or "need". obviously a conditional in the one single file like yours (and for other similar use cases) is much cleaner and more straightforward; just brainstorming other alternatives/workarounds besides using `sed`.

we definitely do need a better way to "read" and support more complex configs. ideally we wouldn't have to check for serverless or experimental-serverless-trace at all, but the plugin will fail in all sorts of confusing ways if we don't do that check. perhaps an option is to simply extend the project's existing config and _force_ it to be serverless with a rewrite regardless?

food for thought, will run this one by some teammates this week :)

**Comment by amuttsch** [comment]
Hi @lindsaylevine thanks for your response :-)

1. We use the CLI in our GitLab CI pipeline to build and deploy our next.js application.
2. Currently we only deploy our git branches to Netlify due to company reasons. Once the changes are merged to `master` we use a different deployment mechanism where we deploy an actual server. Therefore we control the `target` using environment variables and set it accordingly.

I think we are a more exotic use case and I'm not sure how many other projects have a similar setup like ours. Having this check is super important, especially if the plugin fails with cryptic error messages instead if the `target` is wrong. Just overwriting the setting and demote the message to a warning would be a solution, but I'm not sure if that might confuse people. Maybe they expect something else if they have the target set to `server` explicitly, but then again you can use Netlify only if you build serverless-ly. 

Maybe you or your teammates have more insights into this and can reason better to one or another solution. For us and our project it would be fine when the plugin just overrides the `target` and prints a warning or info message. In the meantime the workaround with `sed` works fine! :-)

**Comment by erezrokah** [comment]
Hi @lindsaylevine and @amuttsch. I think the issue here is that the environment variables are set inside the build command script so they are not available to the plugin.

Can you try:
```toml
[build]
    command   = "yarn run build:serverless"
    functions = "out_functions"
    publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"

[context.server.environment]
NEXT_SERVERLESS = "false"
NODE_ENV = "production"
```
Then `netlify build --context production` to build with `serverless` or `netlify build --context server` to build with `server`.
Also, please make sure to run the latest CLI [`v3.8.1`](https://github.com/netlify/cli/releases/tag/v3.8.1) by running `npm install netlify-cli -g`

**Comment by amuttsch** [comment]
Hi @erezrokah Thanks for the suggestion with the context, this works fine for us and we can remove the `sed` workaround :-) As a suggestion a little note in the `README` about this possibility would be helpful for others encountering this issue.

Feel free to close this issue then if there are no more todo's on our side :-)

**Comment by erezrokah** [comment]
Thank you for following up @amuttsch. Good point about the `README`. We currently have [the deploy context feature](https://docs.netlify.com/site-deploys/overview/#deploy-contexts) linked from the [CLI docs](https://docs.netlify.com/cli/get-started/#run-builds-locally).

I would defer to @lindsaylevine about making it visible in the plugin's `README`.
Maybe under https://github.com/netlify/netlify-plugin-nextjs#publish-directory a section named `Context based configuration`
