### ISSUE TITLE
[Bug]: /bin/sh: 1: next: not found

### ISSUE THREAD

**Issue by mulyoved** [netlify/netlify-plugin-nextjs#976]
### Steps to reproduce

See repo https://github.com/the5starz/next-sample

create new nextjs 12 application in a front folder (sample monorepo) using
npx create-next-app@latest --ts front

go to netlifty and create new site from github

**Setup**
![image](https://user-images.githubusercontent.com/2309907/145803894-42862862-a77d-4d52-a426-0468666ce6ff.png)

**Result**
![image](https://user-images.githubusercontent.com/2309907/145804009-56756de8-6301-4455-ab61-fbb3191699a2.png)

### A link to a reproduction repository

https://github.com/the5starz/next-sample

### Plugin version

@netlify/plugin-nextjs@4.0.0-rc.2

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

[build]
    command = "yarn build:front"
    publish = "front/.next"

[[plugins]]
    package = "@netlify/plugin-nextjs"

### Relevant log output (or link to your logs)

1:23:32 PM: $ yarn build:front
1:23:32 PM: yarn run v1.22.10
1:23:33 PM: $ cd front && yarn build
1:23:33 PM: $ next build
1:23:33 PM: /bin/sh: 1: next: not found
1:23:33 PM: error Command failed with exit code 127.

**Comment by ascorbic** [comment]
Hi. This implies that `next` hasn't been installed. What sort of monorepo is it, and where is the `package.json` that includes `next`? If it's all installed in `front`, could you set the `baseDir` to `front` and run the build command in there instead?

**Comment by mulyoved** [comment]
I created a clean sample that demonstrates the problem

https://github.com/the5starz/next-sample

I cannot set baseDir to front as I want to use other packages from the same
monorepo in front (say common)

based on
https://github.com/netlify/netlify-plugin-nextjs/blob/v3/docs/monorepos.md
and yarn monorepo I should not set baseDir

Muly

**Comment by ascorbic** [comment]
Ah, the issue there is that your yarn workspace is setup incorrectly. Change the root `package.json` workspaces key to this:

```json
  "workspaces": {
    "packages": [
      "front"
    ]
  },
```

...and add a version number to the child package.json. You can also change the build command to `yarn workspace front build` instead of including the `cd front` part

**Comment by mulyoved** [comment]
Yes, that was the problem, so solved now, thanks
