### ISSUE TITLE
Error out/index.html already exists

### ISSUE THREAD

**Issue by iamdreo** [netlify/netlify-plugin-nextjs#98]
Hi , 

I'm using this plugin with nextjs but i keep getting out/index.html already exists even when i delete the out file

**Comment by lindsaylevine** [comment]
hey @iamdreo ! would love some more info so i can help you out!

1. are you using the CLI?
2. is your `publish` directory set to `out`?
3. if you're using file-based installation, can you share your netlify.toml?
4. can you share your package.json?

ideally, you could share a repo that reproduces your issue. that would be the fastest way for me to figure out what exactly is going on with your specific setup :)

my first guess though with the info you've shared so far: you have your own custom `index.html` in your publish directory along with /pages/index.js

**Comment by iamdreo** [comment]
Hi @lindsaylevine using getstaticprops() solved the issue but the "/" page (index.js) comes out as blank and the "/home" page with the same exact code works really well.. any ideas?

**Comment by lindsaylevine** [comment]
@iamdreo can you make a quick repo and share it with me that shows what you're seeing? like i said in my last comment that's the best way for me to help you and i'd love to figure out what's going on for you!!

off the top of my head, i don't think i've ever encountered a fully blank page with no error 🤔

**Comment by lindsaylevine** [comment]
@iamdreo hey there. any other info you can share here? otherwise i'll probably have to close out this issue due to lack of info 😦

**Comment by iamdreo** [comment]
Hi sorry, i deleted the public/index.html file and it worked. please you can close the issue

**Comment by lindsaylevine** [comment]
awesome, no worries!
